#!/bin/sh
set -eu

BETTER_AUTH_SECRET="$(cat "$BETTER_AUTH_SECRET_FILE")"
MAILFLOW_BOOTSTRAP_TOKEN="$(cat "$MAILFLOW_BOOTSTRAP_TOKEN_FILE")"
MAILFLOW_RECOVERY_CODE="$(cat "$MAILFLOW_RECOVERY_CODE_FILE")"
POSTGRES_PASSWORD="$(cat "$POSTGRES_PASSWORD_FILE")"
export BETTER_AUTH_SECRET MAILFLOW_BOOTSTRAP_TOKEN MAILFLOW_RECOVERY_CODE POSTGRES_PASSWORD
unset BETTER_AUTH_SECRET_FILE MAILFLOW_BOOTSTRAP_TOKEN_FILE MAILFLOW_RECOVERY_CODE_FILE POSTGRES_PASSWORD_FILE

exec gosu bun bun run --cwd services/auth start
