#!/bin/sh
set -eu

export BETTER_AUTH_SECRET="$(cat "$BETTER_AUTH_SECRET_FILE")"
export MAILFLOW_BOOTSTRAP_TOKEN="$(cat "$MAILFLOW_BOOTSTRAP_TOKEN_FILE")"
export POSTGRES_PASSWORD="$(cat "$POSTGRES_PASSWORD_FILE")"
unset BETTER_AUTH_SECRET_FILE MAILFLOW_BOOTSTRAP_TOKEN_FILE POSTGRES_PASSWORD_FILE

exec gosu bun bun run --cwd services/auth start
