// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: accounts.sql

package dbgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createAccount = `-- name: CreateAccount :one
INSERT INTO accounts (
  id, user_id, provider, remote_id, display_name,
  encrypted_credentials, credential_nonce, capabilities
) VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
RETURNING id, user_id, provider, remote_id, display_name, capabilities, sync_state, disabled_at, created_at, updated_at
`

type CreateAccountParams struct {
	ID                   pgtype.UUID `json:"id"`
	UserID               pgtype.UUID `json:"user_id"`
	Provider             string      `json:"provider"`
	RemoteID             string      `json:"remote_id"`
	DisplayName          string      `json:"display_name"`
	EncryptedCredentials []byte      `json:"encrypted_credentials"`
	CredentialNonce      []byte      `json:"credential_nonce"`
	Capabilities         []byte      `json:"capabilities"`
}

type CreateAccountRow struct {
	ID           pgtype.UUID        `json:"id"`
	UserID       pgtype.UUID        `json:"user_id"`
	Provider     string             `json:"provider"`
	RemoteID     string             `json:"remote_id"`
	DisplayName  string             `json:"display_name"`
	Capabilities []byte             `json:"capabilities"`
	SyncState    string             `json:"sync_state"`
	DisabledAt   pgtype.Timestamptz `json:"disabled_at"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	UpdatedAt    pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) CreateAccount(ctx context.Context, arg CreateAccountParams) (CreateAccountRow, error) {
	row := q.db.QueryRow(ctx, createAccount,
		arg.ID,
		arg.UserID,
		arg.Provider,
		arg.RemoteID,
		arg.DisplayName,
		arg.EncryptedCredentials,
		arg.CredentialNonce,
		arg.Capabilities,
	)
	var i CreateAccountRow
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Provider,
		&i.RemoteID,
		&i.DisplayName,
		&i.Capabilities,
		&i.SyncState,
		&i.DisabledAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const disableAccount = `-- name: DisableAccount :one
UPDATE accounts
SET disabled_at = COALESCE(disabled_at, now()), sync_state = 'disabled', updated_at = now()
WHERE id = $1 AND user_id = $2
RETURNING id, user_id, provider, remote_id, display_name, capabilities, sync_state, disabled_at, created_at, updated_at
`

type DisableAccountParams struct {
	ID     pgtype.UUID `json:"id"`
	UserID pgtype.UUID `json:"user_id"`
}

type DisableAccountRow struct {
	ID           pgtype.UUID        `json:"id"`
	UserID       pgtype.UUID        `json:"user_id"`
	Provider     string             `json:"provider"`
	RemoteID     string             `json:"remote_id"`
	DisplayName  string             `json:"display_name"`
	Capabilities []byte             `json:"capabilities"`
	SyncState    string             `json:"sync_state"`
	DisabledAt   pgtype.Timestamptz `json:"disabled_at"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	UpdatedAt    pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) DisableAccount(ctx context.Context, arg DisableAccountParams) (DisableAccountRow, error) {
	row := q.db.QueryRow(ctx, disableAccount, arg.ID, arg.UserID)
	var i DisableAccountRow
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Provider,
		&i.RemoteID,
		&i.DisplayName,
		&i.Capabilities,
		&i.SyncState,
		&i.DisabledAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getAccountByUser = `-- name: GetAccountByUser :one
SELECT id, user_id, provider, remote_id, display_name, capabilities, sync_state, disabled_at, created_at, updated_at
FROM accounts
WHERE id = $1 AND user_id = $2
`

type GetAccountByUserParams struct {
	ID     pgtype.UUID `json:"id"`
	UserID pgtype.UUID `json:"user_id"`
}

type GetAccountByUserRow struct {
	ID           pgtype.UUID        `json:"id"`
	UserID       pgtype.UUID        `json:"user_id"`
	Provider     string             `json:"provider"`
	RemoteID     string             `json:"remote_id"`
	DisplayName  string             `json:"display_name"`
	Capabilities []byte             `json:"capabilities"`
	SyncState    string             `json:"sync_state"`
	DisabledAt   pgtype.Timestamptz `json:"disabled_at"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	UpdatedAt    pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) GetAccountByUser(ctx context.Context, arg GetAccountByUserParams) (GetAccountByUserRow, error) {
	row := q.db.QueryRow(ctx, getAccountByUser, arg.ID, arg.UserID)
	var i GetAccountByUserRow
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Provider,
		&i.RemoteID,
		&i.DisplayName,
		&i.Capabilities,
		&i.SyncState,
		&i.DisabledAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getAccountCredentialsByUser = `-- name: GetAccountCredentialsByUser :one
SELECT encrypted_credentials, credential_nonce
FROM accounts
WHERE id = $1 AND user_id = $2
`

type GetAccountCredentialsByUserParams struct {
	ID     pgtype.UUID `json:"id"`
	UserID pgtype.UUID `json:"user_id"`
}

type GetAccountCredentialsByUserRow struct {
	EncryptedCredentials []byte `json:"encrypted_credentials"`
	CredentialNonce      []byte `json:"credential_nonce"`
}

func (q *Queries) GetAccountCredentialsByUser(ctx context.Context, arg GetAccountCredentialsByUserParams) (GetAccountCredentialsByUserRow, error) {
	row := q.db.QueryRow(ctx, getAccountCredentialsByUser, arg.ID, arg.UserID)
	var i GetAccountCredentialsByUserRow
	err := row.Scan(&i.EncryptedCredentials, &i.CredentialNonce)
	return i, err
}

const listAccountsByUser = `-- name: ListAccountsByUser :many
SELECT id, user_id, provider, remote_id, display_name, capabilities, sync_state, disabled_at, created_at, updated_at
FROM accounts
WHERE user_id = $1
ORDER BY created_at, id
`

type ListAccountsByUserRow struct {
	ID           pgtype.UUID        `json:"id"`
	UserID       pgtype.UUID        `json:"user_id"`
	Provider     string             `json:"provider"`
	RemoteID     string             `json:"remote_id"`
	DisplayName  string             `json:"display_name"`
	Capabilities []byte             `json:"capabilities"`
	SyncState    string             `json:"sync_state"`
	DisabledAt   pgtype.Timestamptz `json:"disabled_at"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	UpdatedAt    pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) ListAccountsByUser(ctx context.Context, userID pgtype.UUID) ([]ListAccountsByUserRow, error) {
	rows, err := q.db.Query(ctx, listAccountsByUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListAccountsByUserRow
	for rows.Next() {
		var i ListAccountsByUserRow
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Provider,
			&i.RemoteID,
			&i.DisplayName,
			&i.Capabilities,
			&i.SyncState,
			&i.DisabledAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateAccountCapabilities = `-- name: UpdateAccountCapabilities :one
UPDATE accounts
SET capabilities = $3, updated_at = now()
WHERE id = $1 AND user_id = $2 AND disabled_at IS NULL
RETURNING id, user_id, provider, remote_id, display_name, capabilities, sync_state, disabled_at, created_at, updated_at
`

type UpdateAccountCapabilitiesParams struct {
	ID           pgtype.UUID `json:"id"`
	UserID       pgtype.UUID `json:"user_id"`
	Capabilities []byte      `json:"capabilities"`
}

type UpdateAccountCapabilitiesRow struct {
	ID           pgtype.UUID        `json:"id"`
	UserID       pgtype.UUID        `json:"user_id"`
	Provider     string             `json:"provider"`
	RemoteID     string             `json:"remote_id"`
	DisplayName  string             `json:"display_name"`
	Capabilities []byte             `json:"capabilities"`
	SyncState    string             `json:"sync_state"`
	DisabledAt   pgtype.Timestamptz `json:"disabled_at"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	UpdatedAt    pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) UpdateAccountCapabilities(ctx context.Context, arg UpdateAccountCapabilitiesParams) (UpdateAccountCapabilitiesRow, error) {
	row := q.db.QueryRow(ctx, updateAccountCapabilities, arg.ID, arg.UserID, arg.Capabilities)
	var i UpdateAccountCapabilitiesRow
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Provider,
		&i.RemoteID,
		&i.DisplayName,
		&i.Capabilities,
		&i.SyncState,
		&i.DisabledAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
