// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: actions.sql

package dbgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const claimPendingAction = `-- name: ClaimPendingAction :one
WITH candidate AS (
  SELECT pending_actions.id
  FROM pending_actions
  JOIN accounts ON accounts.id = pending_actions.account_id
  WHERE accounts.user_id = $2
    AND accounts.disabled_at IS NULL
    AND pending_actions.status IN ('pending', 'retry_wait')
    AND pending_actions.available_at <= now()
  ORDER BY pending_actions.available_at, pending_actions.created_at
  FOR UPDATE OF pending_actions SKIP LOCKED
  LIMIT 1
)
UPDATE pending_actions
SET status = 'processing', attempts = attempts + 1,
    claim_token = $1, claimed_at = now(), updated_at = now()
FROM candidate
WHERE pending_actions.id = candidate.id
RETURNING pending_actions.id, pending_actions.account_id, pending_actions.idempotency_key, pending_actions.kind, pending_actions.desired_state, pending_actions.status, pending_actions.attempts, pending_actions.available_at, pending_actions.last_error_code, pending_actions.created_at, pending_actions.target_kind, pending_actions.target_id, pending_actions.authoritative_state, pending_actions.max_attempts, pending_actions.claim_token, pending_actions.claimed_at, pending_actions.completed_at, pending_actions.failed_at, pending_actions.updated_at
`

type ClaimPendingActionParams struct {
	ClaimToken pgtype.UUID `json:"claim_token"`
	UserID     pgtype.UUID `json:"user_id"`
}

func (q *Queries) ClaimPendingAction(ctx context.Context, arg ClaimPendingActionParams) (PendingAction, error) {
	row := q.db.QueryRow(ctx, claimPendingAction, arg.ClaimToken, arg.UserID)
	var i PendingAction
	err := row.Scan(
		&i.ID,
		&i.AccountID,
		&i.IdempotencyKey,
		&i.Kind,
		&i.DesiredState,
		&i.Status,
		&i.Attempts,
		&i.AvailableAt,
		&i.LastErrorCode,
		&i.CreatedAt,
		&i.TargetKind,
		&i.TargetID,
		&i.AuthoritativeState,
		&i.MaxAttempts,
		&i.ClaimToken,
		&i.ClaimedAt,
		&i.CompletedAt,
		&i.FailedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const completePendingAction = `-- name: CompletePendingAction :one
UPDATE pending_actions
SET status = 'completed', claim_token = NULL, claimed_at = NULL,
    completed_at = now(), last_error_code = NULL, updated_at = now()
WHERE id = $1 AND claim_token = $2 AND status = 'processing'
RETURNING id, account_id, idempotency_key, kind, desired_state, status, attempts, available_at, last_error_code, created_at, target_kind, target_id, authoritative_state, max_attempts, claim_token, claimed_at, completed_at, failed_at, updated_at
`

type CompletePendingActionParams struct {
	ID         pgtype.UUID `json:"id"`
	ClaimToken pgtype.UUID `json:"claim_token"`
}

func (q *Queries) CompletePendingAction(ctx context.Context, arg CompletePendingActionParams) (PendingAction, error) {
	row := q.db.QueryRow(ctx, completePendingAction, arg.ID, arg.ClaimToken)
	var i PendingAction
	err := row.Scan(
		&i.ID,
		&i.AccountID,
		&i.IdempotencyKey,
		&i.Kind,
		&i.DesiredState,
		&i.Status,
		&i.Attempts,
		&i.AvailableAt,
		&i.LastErrorCode,
		&i.CreatedAt,
		&i.TargetKind,
		&i.TargetID,
		&i.AuthoritativeState,
		&i.MaxAttempts,
		&i.ClaimToken,
		&i.ClaimedAt,
		&i.CompletedAt,
		&i.FailedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const conflictPendingAction = `-- name: ConflictPendingAction :one
UPDATE pending_actions
SET status = 'conflict', claim_token = NULL, claimed_at = NULL,
    authoritative_state = $1, last_error_code = $2,
    failed_at = now(), updated_at = now()
WHERE id = $3 AND claim_token = $4 AND status = 'processing'
RETURNING id, account_id, idempotency_key, kind, desired_state, status, attempts, available_at, last_error_code, created_at, target_kind, target_id, authoritative_state, max_attempts, claim_token, claimed_at, completed_at, failed_at, updated_at
`

type ConflictPendingActionParams struct {
	AuthoritativeState []byte      `json:"authoritative_state"`
	ErrorCode          pgtype.Text `json:"error_code"`
	ID                 pgtype.UUID `json:"id"`
	ClaimToken         pgtype.UUID `json:"claim_token"`
}

func (q *Queries) ConflictPendingAction(ctx context.Context, arg ConflictPendingActionParams) (PendingAction, error) {
	row := q.db.QueryRow(ctx, conflictPendingAction,
		arg.AuthoritativeState,
		arg.ErrorCode,
		arg.ID,
		arg.ClaimToken,
	)
	var i PendingAction
	err := row.Scan(
		&i.ID,
		&i.AccountID,
		&i.IdempotencyKey,
		&i.Kind,
		&i.DesiredState,
		&i.Status,
		&i.Attempts,
		&i.AvailableAt,
		&i.LastErrorCode,
		&i.CreatedAt,
		&i.TargetKind,
		&i.TargetID,
		&i.AuthoritativeState,
		&i.MaxAttempts,
		&i.ClaimToken,
		&i.ClaimedAt,
		&i.CompletedAt,
		&i.FailedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createPendingAction = `-- name: CreatePendingAction :one
INSERT INTO pending_actions (
  id, account_id, idempotency_key, kind, target_kind, target_id,
  desired_state, status, max_attempts
)
SELECT
  $1, accounts.id, $2, $3,
  $4, $5, $6,
  'pending', $7
FROM accounts
WHERE accounts.id = $8
  AND accounts.user_id = $9
  AND accounts.disabled_at IS NULL
ON CONFLICT (account_id, idempotency_key) DO NOTHING
RETURNING id, account_id, idempotency_key, kind, desired_state, status, attempts, available_at, last_error_code, created_at, target_kind, target_id, authoritative_state, max_attempts, claim_token, claimed_at, completed_at, failed_at, updated_at
`

type CreatePendingActionParams struct {
	ID             pgtype.UUID `json:"id"`
	IdempotencyKey string      `json:"idempotency_key"`
	Kind           string      `json:"kind"`
	TargetKind     string      `json:"target_kind"`
	TargetID       pgtype.UUID `json:"target_id"`
	DesiredState   []byte      `json:"desired_state"`
	MaxAttempts    int32       `json:"max_attempts"`
	AccountID      pgtype.UUID `json:"account_id"`
	UserID         pgtype.UUID `json:"user_id"`
}

func (q *Queries) CreatePendingAction(ctx context.Context, arg CreatePendingActionParams) (PendingAction, error) {
	row := q.db.QueryRow(ctx, createPendingAction,
		arg.ID,
		arg.IdempotencyKey,
		arg.Kind,
		arg.TargetKind,
		arg.TargetID,
		arg.DesiredState,
		arg.MaxAttempts,
		arg.AccountID,
		arg.UserID,
	)
	var i PendingAction
	err := row.Scan(
		&i.ID,
		&i.AccountID,
		&i.IdempotencyKey,
		&i.Kind,
		&i.DesiredState,
		&i.Status,
		&i.Attempts,
		&i.AvailableAt,
		&i.LastErrorCode,
		&i.CreatedAt,
		&i.TargetKind,
		&i.TargetID,
		&i.AuthoritativeState,
		&i.MaxAttempts,
		&i.ClaimToken,
		&i.ClaimedAt,
		&i.CompletedAt,
		&i.FailedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createPendingActionAttempt = `-- name: CreatePendingActionAttempt :exec
INSERT INTO pending_action_attempts (action_id, attempt, claim_token)
VALUES ($1, $2, $3)
`

type CreatePendingActionAttemptParams struct {
	ActionID   pgtype.UUID `json:"action_id"`
	Attempt    int32       `json:"attempt"`
	ClaimToken pgtype.UUID `json:"claim_token"`
}

func (q *Queries) CreatePendingActionAttempt(ctx context.Context, arg CreatePendingActionAttemptParams) error {
	_, err := q.db.Exec(ctx, createPendingActionAttempt, arg.ActionID, arg.Attempt, arg.ClaimToken)
	return err
}

const finishPendingActionAttempt = `-- name: FinishPendingActionAttempt :exec
UPDATE pending_action_attempts
SET status = $1, error_code = $2, finished_at = now()
WHERE action_id = $3
  AND attempt = $4
  AND claim_token = $5
  AND status = 'processing'
`

type FinishPendingActionAttemptParams struct {
	Status     string      `json:"status"`
	ErrorCode  pgtype.Text `json:"error_code"`
	ActionID   pgtype.UUID `json:"action_id"`
	Attempt    int32       `json:"attempt"`
	ClaimToken pgtype.UUID `json:"claim_token"`
}

func (q *Queries) FinishPendingActionAttempt(ctx context.Context, arg FinishPendingActionAttemptParams) error {
	_, err := q.db.Exec(ctx, finishPendingActionAttempt,
		arg.Status,
		arg.ErrorCode,
		arg.ActionID,
		arg.Attempt,
		arg.ClaimToken,
	)
	return err
}

const getClaimedPendingAction = `-- name: GetClaimedPendingAction :one
SELECT pending_actions.id, pending_actions.account_id, pending_actions.idempotency_key, pending_actions.kind, pending_actions.desired_state, pending_actions.status, pending_actions.attempts, pending_actions.available_at, pending_actions.last_error_code, pending_actions.created_at, pending_actions.target_kind, pending_actions.target_id, pending_actions.authoritative_state, pending_actions.max_attempts, pending_actions.claim_token, pending_actions.claimed_at, pending_actions.completed_at, pending_actions.failed_at, pending_actions.updated_at
FROM pending_actions
JOIN accounts ON accounts.id = pending_actions.account_id
WHERE pending_actions.id = $1
  AND pending_actions.claim_token = $2
  AND pending_actions.status = 'processing'
  AND accounts.user_id = $3
FOR UPDATE OF pending_actions
`

type GetClaimedPendingActionParams struct {
	ID         pgtype.UUID `json:"id"`
	ClaimToken pgtype.UUID `json:"claim_token"`
	UserID     pgtype.UUID `json:"user_id"`
}

func (q *Queries) GetClaimedPendingAction(ctx context.Context, arg GetClaimedPendingActionParams) (PendingAction, error) {
	row := q.db.QueryRow(ctx, getClaimedPendingAction, arg.ID, arg.ClaimToken, arg.UserID)
	var i PendingAction
	err := row.Scan(
		&i.ID,
		&i.AccountID,
		&i.IdempotencyKey,
		&i.Kind,
		&i.DesiredState,
		&i.Status,
		&i.Attempts,
		&i.AvailableAt,
		&i.LastErrorCode,
		&i.CreatedAt,
		&i.TargetKind,
		&i.TargetID,
		&i.AuthoritativeState,
		&i.MaxAttempts,
		&i.ClaimToken,
		&i.ClaimedAt,
		&i.CompletedAt,
		&i.FailedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getPendingActionByIdempotency = `-- name: GetPendingActionByIdempotency :one
SELECT pending_actions.id, pending_actions.account_id, pending_actions.idempotency_key, pending_actions.kind, pending_actions.desired_state, pending_actions.status, pending_actions.attempts, pending_actions.available_at, pending_actions.last_error_code, pending_actions.created_at, pending_actions.target_kind, pending_actions.target_id, pending_actions.authoritative_state, pending_actions.max_attempts, pending_actions.claim_token, pending_actions.claimed_at, pending_actions.completed_at, pending_actions.failed_at, pending_actions.updated_at
FROM pending_actions
JOIN accounts ON accounts.id = pending_actions.account_id
WHERE pending_actions.account_id = $1
  AND pending_actions.idempotency_key = $2
  AND accounts.user_id = $3
`

type GetPendingActionByIdempotencyParams struct {
	AccountID      pgtype.UUID `json:"account_id"`
	IdempotencyKey string      `json:"idempotency_key"`
	UserID         pgtype.UUID `json:"user_id"`
}

func (q *Queries) GetPendingActionByIdempotency(ctx context.Context, arg GetPendingActionByIdempotencyParams) (PendingAction, error) {
	row := q.db.QueryRow(ctx, getPendingActionByIdempotency, arg.AccountID, arg.IdempotencyKey, arg.UserID)
	var i PendingAction
	err := row.Scan(
		&i.ID,
		&i.AccountID,
		&i.IdempotencyKey,
		&i.Kind,
		&i.DesiredState,
		&i.Status,
		&i.Attempts,
		&i.AvailableAt,
		&i.LastErrorCode,
		&i.CreatedAt,
		&i.TargetKind,
		&i.TargetID,
		&i.AuthoritativeState,
		&i.MaxAttempts,
		&i.ClaimToken,
		&i.ClaimedAt,
		&i.CompletedAt,
		&i.FailedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const retryPendingAction = `-- name: RetryPendingAction :one
UPDATE pending_actions
SET status = 'retry_wait', claim_token = NULL, claimed_at = NULL,
    available_at = $1, last_error_code = $2, updated_at = now()
WHERE id = $3 AND claim_token = $4 AND status = 'processing'
RETURNING id, account_id, idempotency_key, kind, desired_state, status, attempts, available_at, last_error_code, created_at, target_kind, target_id, authoritative_state, max_attempts, claim_token, claimed_at, completed_at, failed_at, updated_at
`

type RetryPendingActionParams struct {
	AvailableAt pgtype.Timestamptz `json:"available_at"`
	ErrorCode   pgtype.Text        `json:"error_code"`
	ID          pgtype.UUID        `json:"id"`
	ClaimToken  pgtype.UUID        `json:"claim_token"`
}

func (q *Queries) RetryPendingAction(ctx context.Context, arg RetryPendingActionParams) (PendingAction, error) {
	row := q.db.QueryRow(ctx, retryPendingAction,
		arg.AvailableAt,
		arg.ErrorCode,
		arg.ID,
		arg.ClaimToken,
	)
	var i PendingAction
	err := row.Scan(
		&i.ID,
		&i.AccountID,
		&i.IdempotencyKey,
		&i.Kind,
		&i.DesiredState,
		&i.Status,
		&i.Attempts,
		&i.AvailableAt,
		&i.LastErrorCode,
		&i.CreatedAt,
		&i.TargetKind,
		&i.TargetID,
		&i.AuthoritativeState,
		&i.MaxAttempts,
		&i.ClaimToken,
		&i.ClaimedAt,
		&i.CompletedAt,
		&i.FailedAt,
		&i.UpdatedAt,
	)
	return i, err
}
