// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: admin.sql

package dbgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const recentLogs = `-- name: RecentLogs :many
SELECT id, occurred_at, service, module, level, event, request_id, attributes
FROM log_entries
WHERE occurred_at >= $1
ORDER BY occurred_at DESC
LIMIT $2
`

type RecentLogsParams struct {
	Since       pgtype.Timestamptz `json:"since"`
	ResultLimit int32              `json:"result_limit"`
}

func (q *Queries) RecentLogs(ctx context.Context, arg RecentLogsParams) ([]LogEntry, error) {
	rows, err := q.db.Query(ctx, recentLogs, arg.Since, arg.ResultLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []LogEntry
	for rows.Next() {
		var i LogEntry
		if err := rows.Scan(
			&i.ID,
			&i.OccurredAt,
			&i.Service,
			&i.Module,
			&i.Level,
			&i.Event,
			&i.RequestID,
			&i.Attributes,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
