// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: admin.sql

package dbgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const recentLogs = `-- name: RecentLogs :many
SELECT id, occurred_at, service, module, level, event, request_id, attributes
FROM log_entries
WHERE occurred_at >= $1
ORDER BY occurred_at DESC
LIMIT $2
`

type RecentLogsParams struct {
	Since       pgtype.Timestamptz `json:"since"`
	ResultLimit int32              `json:"result_limit"`
}

func (q *Queries) RecentLogs(ctx context.Context, arg RecentLogsParams) ([]LogEntry, error) {
	rows, err := q.db.Query(ctx, recentLogs, arg.Since, arg.ResultLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []LogEntry
	for rows.Next() {
		var i LogEntry
		if err := rows.Scan(
			&i.ID,
			&i.OccurredAt,
			&i.Service,
			&i.Module,
			&i.Level,
			&i.Event,
			&i.RequestID,
			&i.Attributes,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertMetricPoint = `-- name: UpsertMetricPoint :exec
INSERT INTO metric_points (bucket, resolution, name, kind, dimensions, value, count)
VALUES ($1, $2, $3, $4, $5, $6, $7)
ON CONFLICT (bucket, resolution, name, dimensions)
DO UPDATE SET value = EXCLUDED.value, count = metric_points.count + EXCLUDED.count
`

type UpsertMetricPointParams struct {
	Bucket     pgtype.Timestamptz `json:"bucket"`
	Resolution string             `json:"resolution"`
	Name       string             `json:"name"`
	Kind       string             `json:"kind"`
	Dimensions []byte             `json:"dimensions"`
	Value      float64            `json:"value"`
	Count      int64              `json:"count"`
}

func (q *Queries) UpsertMetricPoint(ctx context.Context, arg UpsertMetricPointParams) error {
	_, err := q.db.Exec(ctx, upsertMetricPoint,
		arg.Bucket,
		arg.Resolution,
		arg.Name,
		arg.Kind,
		arg.Dimensions,
		arg.Value,
		arg.Count,
	)
	return err
}
