// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: authbridge.sql

package dbgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getUserByAuthSubject = `-- name: GetUserByAuthSubject :one
SELECT id, email, locale
FROM users
WHERE id = $1
`

type GetUserByAuthSubjectRow struct {
	ID     pgtype.UUID `json:"id"`
	Email  string      `json:"email"`
	Locale string      `json:"locale"`
}

func (q *Queries) GetUserByAuthSubject(ctx context.Context, id pgtype.UUID) (GetUserByAuthSubjectRow, error) {
	row := q.db.QueryRow(ctx, getUserByAuthSubject, id)
	var i GetUserByAuthSubjectRow
	err := row.Scan(&i.ID, &i.Email, &i.Locale)
	return i, err
}
