// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: cdn.sql

package dbgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const deleteOrphanedAttachmentObject = `-- name: DeleteOrphanedAttachmentObject :execrows
DELETE FROM cdn_objects
WHERE cdn_objects.object_id = $1
  AND namespace = 'attachments'
  AND storage_status = 'missing'
  AND NOT EXISTS (
    SELECT 1 FROM message_attachments WHERE message_attachments.cached_object_id = cdn_objects.object_id
  )
  AND NOT EXISTS (
    SELECT 1 FROM draft_attachments WHERE draft_attachments.object_id = cdn_objects.object_id
  )
`

func (q *Queries) DeleteOrphanedAttachmentObject(ctx context.Context, objectID string) (int64, error) {
	result, err := q.db.Exec(ctx, deleteOrphanedAttachmentObject, objectID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getAttachmentObjectForUser = `-- name: GetAttachmentObjectForUser :one
SELECT cdn_objects.object_id, cdn_objects.namespace, cdn_objects.account_id, cdn_objects.recovery_reference, cdn_objects.filename, cdn_objects.media_type, cdn_objects.size_bytes, cdn_objects.etag, cdn_objects.storage_status, cdn_objects.expires_at, cdn_objects.stored_at, cdn_objects.last_accessed_at, cdn_objects.created_at, cdn_objects.updated_at FROM cdn_objects
JOIN accounts ON cdn_objects.account_id = accounts.id
WHERE cdn_objects.object_id = $1
  AND cdn_objects.namespace = 'attachments'
  AND accounts.user_id = $2
`

type GetAttachmentObjectForUserParams struct {
	ObjectID string      `json:"object_id"`
	UserID   pgtype.UUID `json:"user_id"`
}

func (q *Queries) GetAttachmentObjectForUser(ctx context.Context, arg GetAttachmentObjectForUserParams) (CdnObject, error) {
	row := q.db.QueryRow(ctx, getAttachmentObjectForUser, arg.ObjectID, arg.UserID)
	var i CdnObject
	err := row.Scan(
		&i.ObjectID,
		&i.Namespace,
		&i.AccountID,
		&i.RecoveryReference,
		&i.Filename,
		&i.MediaType,
		&i.SizeBytes,
		&i.Etag,
		&i.StorageStatus,
		&i.ExpiresAt,
		&i.StoredAt,
		&i.LastAccessedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getMessageAttachmentForUser = `-- name: GetMessageAttachmentForUser :one
SELECT message_attachments.id, message_attachments.account_id,
       message_attachments.remote_id, message_attachments.filename,
       message_attachments.media_type, message_attachments.size_bytes,
       message_attachments.cached_object_id,
       messages.remote_id AS message_remote_id,
       accounts.provider
FROM message_attachments
JOIN messages ON messages.id = message_attachments.message_id
  AND messages.account_id = message_attachments.account_id
JOIN accounts ON accounts.id = message_attachments.account_id
WHERE message_attachments.id = $1
  AND accounts.user_id = $2
`

type GetMessageAttachmentForUserParams struct {
	AttachmentID pgtype.UUID `json:"attachment_id"`
	UserID       pgtype.UUID `json:"user_id"`
}

type GetMessageAttachmentForUserRow struct {
	ID              pgtype.UUID `json:"id"`
	AccountID       pgtype.UUID `json:"account_id"`
	RemoteID        pgtype.Text `json:"remote_id"`
	Filename        pgtype.Text `json:"filename"`
	MediaType       string      `json:"media_type"`
	SizeBytes       int64       `json:"size_bytes"`
	CachedObjectID  pgtype.Text `json:"cached_object_id"`
	MessageRemoteID string      `json:"message_remote_id"`
	Provider        string      `json:"provider"`
}

func (q *Queries) GetMessageAttachmentForUser(ctx context.Context, arg GetMessageAttachmentForUserParams) (GetMessageAttachmentForUserRow, error) {
	row := q.db.QueryRow(ctx, getMessageAttachmentForUser, arg.AttachmentID, arg.UserID)
	var i GetMessageAttachmentForUserRow
	err := row.Scan(
		&i.ID,
		&i.AccountID,
		&i.RemoteID,
		&i.Filename,
		&i.MediaType,
		&i.SizeBytes,
		&i.CachedObjectID,
		&i.MessageRemoteID,
		&i.Provider,
	)
	return i, err
}

const linkMessageAttachmentObject = `-- name: LinkMessageAttachmentObject :execrows
UPDATE message_attachments
SET cached_object_id = $1, updated_at = now()
FROM accounts
WHERE message_attachments.id = $2
  AND accounts.id = message_attachments.account_id
  AND accounts.user_id = $3
  AND EXISTS (
    SELECT 1 FROM cdn_objects
    WHERE cdn_objects.object_id = $1
      AND cdn_objects.namespace = 'attachments'
      AND cdn_objects.account_id = message_attachments.account_id
      AND cdn_objects.storage_status = 'cached'
  )
`

type LinkMessageAttachmentObjectParams struct {
	ObjectID     pgtype.Text `json:"object_id"`
	AttachmentID pgtype.UUID `json:"attachment_id"`
	UserID       pgtype.UUID `json:"user_id"`
}

func (q *Queries) LinkMessageAttachmentObject(ctx context.Context, arg LinkMessageAttachmentObjectParams) (int64, error) {
	result, err := q.db.Exec(ctx, linkMessageAttachmentObject, arg.ObjectID, arg.AttachmentID, arg.UserID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const listExpiredCachedAttachmentObjects = `-- name: ListExpiredCachedAttachmentObjects :many
SELECT object_id, namespace, account_id, recovery_reference, filename, media_type, size_bytes, etag, storage_status, expires_at, stored_at, last_accessed_at, created_at, updated_at FROM cdn_objects
WHERE namespace = 'attachments'
  AND storage_status = 'cached'
  AND expires_at IS NOT NULL
  AND expires_at <= $1
  AND NOT EXISTS (
    SELECT 1 FROM draft_attachments
    JOIN drafts ON drafts.id = draft_attachments.draft_id
      AND drafts.account_id = draft_attachments.account_id
    WHERE draft_attachments.object_id = cdn_objects.object_id
      AND drafts.sync_status <> 'discarded'
  )
ORDER BY expires_at, object_id
LIMIT $2
`

type ListExpiredCachedAttachmentObjectsParams struct {
	ExpiredAt pgtype.Timestamptz `json:"expired_at"`
	BatchSize int32              `json:"batch_size"`
}

func (q *Queries) ListExpiredCachedAttachmentObjects(ctx context.Context, arg ListExpiredCachedAttachmentObjectsParams) ([]CdnObject, error) {
	rows, err := q.db.Query(ctx, listExpiredCachedAttachmentObjects, arg.ExpiredAt, arg.BatchSize)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []CdnObject
	for rows.Next() {
		var i CdnObject
		if err := rows.Scan(
			&i.ObjectID,
			&i.Namespace,
			&i.AccountID,
			&i.RecoveryReference,
			&i.Filename,
			&i.MediaType,
			&i.SizeBytes,
			&i.Etag,
			&i.StorageStatus,
			&i.ExpiresAt,
			&i.StoredAt,
			&i.LastAccessedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listOrphanedAttachmentObjects = `-- name: ListOrphanedAttachmentObjects :many
SELECT object_id, namespace, account_id, recovery_reference, filename, media_type, size_bytes, etag, storage_status, expires_at, stored_at, last_accessed_at, created_at, updated_at FROM cdn_objects
WHERE namespace = 'attachments'
  AND storage_status = 'missing'
  AND cdn_objects.updated_at <= $1
  AND NOT EXISTS (
    SELECT 1 FROM message_attachments WHERE message_attachments.cached_object_id = cdn_objects.object_id
  )
  AND NOT EXISTS (
    SELECT 1 FROM draft_attachments WHERE draft_attachments.object_id = cdn_objects.object_id
  )
ORDER BY cdn_objects.updated_at, cdn_objects.object_id
LIMIT $2
`

type ListOrphanedAttachmentObjectsParams struct {
	OrphanedBefore pgtype.Timestamptz `json:"orphaned_before"`
	BatchSize      int32              `json:"batch_size"`
}

func (q *Queries) ListOrphanedAttachmentObjects(ctx context.Context, arg ListOrphanedAttachmentObjectsParams) ([]CdnObject, error) {
	rows, err := q.db.Query(ctx, listOrphanedAttachmentObjects, arg.OrphanedBefore, arg.BatchSize)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []CdnObject
	for rows.Next() {
		var i CdnObject
		if err := rows.Scan(
			&i.ObjectID,
			&i.Namespace,
			&i.AccountID,
			&i.RecoveryReference,
			&i.Filename,
			&i.MediaType,
			&i.SizeBytes,
			&i.Etag,
			&i.StorageStatus,
			&i.ExpiresAt,
			&i.StoredAt,
			&i.LastAccessedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markAttachmentObjectMissing = `-- name: MarkAttachmentObjectMissing :exec
UPDATE cdn_objects
SET storage_status = 'missing', updated_at = $1
WHERE object_id = $2 AND namespace = 'attachments'
`

type MarkAttachmentObjectMissingParams struct {
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
	ObjectID  string             `json:"object_id"`
}

func (q *Queries) MarkAttachmentObjectMissing(ctx context.Context, arg MarkAttachmentObjectMissingParams) error {
	_, err := q.db.Exec(ctx, markAttachmentObjectMissing, arg.UpdatedAt, arg.ObjectID)
	return err
}

const touchAttachmentObject = `-- name: TouchAttachmentObject :exec
UPDATE cdn_objects
SET last_accessed_at = $1, expires_at = $2, updated_at = $1
WHERE object_id = $3 AND namespace = 'attachments' AND storage_status = 'cached'
`

type TouchAttachmentObjectParams struct {
	AccessedAt pgtype.Timestamptz `json:"accessed_at"`
	ExpiresAt  pgtype.Timestamptz `json:"expires_at"`
	ObjectID   string             `json:"object_id"`
}

func (q *Queries) TouchAttachmentObject(ctx context.Context, arg TouchAttachmentObjectParams) error {
	_, err := q.db.Exec(ctx, touchAttachmentObject, arg.AccessedAt, arg.ExpiresAt, arg.ObjectID)
	return err
}

const upsertAttachmentObject = `-- name: UpsertAttachmentObject :one
INSERT INTO cdn_objects (
  object_id, namespace, account_id, recovery_reference, filename,
  media_type, size_bytes, etag, storage_status, expires_at, stored_at, updated_at
)
SELECT $1, 'attachments', accounts.id, $2,
       $3, $4, $5, $6,
       'cached', $7, $8, $8
FROM accounts
WHERE accounts.id = $9 AND accounts.user_id = $10
ON CONFLICT (object_id) DO UPDATE SET
  recovery_reference = EXCLUDED.recovery_reference,
  filename = EXCLUDED.filename,
  media_type = EXCLUDED.media_type,
  size_bytes = EXCLUDED.size_bytes,
  etag = EXCLUDED.etag,
  storage_status = 'cached',
  expires_at = EXCLUDED.expires_at,
  stored_at = EXCLUDED.stored_at,
  updated_at = EXCLUDED.updated_at
WHERE cdn_objects.namespace = 'attachments'
  AND cdn_objects.account_id = EXCLUDED.account_id
RETURNING cdn_objects.object_id, cdn_objects.namespace, cdn_objects.account_id, cdn_objects.recovery_reference, cdn_objects.filename, cdn_objects.media_type, cdn_objects.size_bytes, cdn_objects.etag, cdn_objects.storage_status, cdn_objects.expires_at, cdn_objects.stored_at, cdn_objects.last_accessed_at, cdn_objects.created_at, cdn_objects.updated_at
`

type UpsertAttachmentObjectParams struct {
	ObjectID          string             `json:"object_id"`
	RecoveryReference pgtype.Text        `json:"recovery_reference"`
	Filename          pgtype.Text        `json:"filename"`
	MediaType         string             `json:"media_type"`
	SizeBytes         int64              `json:"size_bytes"`
	Etag              string             `json:"etag"`
	ExpiresAt         pgtype.Timestamptz `json:"expires_at"`
	StoredAt          pgtype.Timestamptz `json:"stored_at"`
	AccountID         pgtype.UUID        `json:"account_id"`
	UserID            pgtype.UUID        `json:"user_id"`
}

func (q *Queries) UpsertAttachmentObject(ctx context.Context, arg UpsertAttachmentObjectParams) (CdnObject, error) {
	row := q.db.QueryRow(ctx, upsertAttachmentObject,
		arg.ObjectID,
		arg.RecoveryReference,
		arg.Filename,
		arg.MediaType,
		arg.SizeBytes,
		arg.Etag,
		arg.ExpiresAt,
		arg.StoredAt,
		arg.AccountID,
		arg.UserID,
	)
	var i CdnObject
	err := row.Scan(
		&i.ObjectID,
		&i.Namespace,
		&i.AccountID,
		&i.RecoveryReference,
		&i.Filename,
		&i.MediaType,
		&i.SizeBytes,
		&i.Etag,
		&i.StorageStatus,
		&i.ExpiresAt,
		&i.StoredAt,
		&i.LastAccessedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
