// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: drafts.sql

package dbgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const checkpointDraftRemote = `-- name: CheckpointDraftRemote :one
UPDATE drafts
SET remote_id = $1, remote_revision = $2,
    synced_revision = $3, sync_status = 'synced',
    last_remote_synced_at = now(), updated_at = now()
WHERE id = $4
  AND account_id = $5
  AND local_revision = $3
  AND sync_status <> 'discarded'
RETURNING drafts.id, drafts.account_id, drafts.remote_id, drafts.remote_revision, drafts.subject, drafts.body_text, drafts.body_html_sanitized, drafts.local_revision, drafts.synced_revision, drafts.sync_status, drafts.remote_checkpoint_at, drafts.last_remote_synced_at, drafts.discarded_at, drafts.created_at, drafts.updated_at
`

type CheckpointDraftRemoteParams struct {
	RemoteID       pgtype.Text `json:"remote_id"`
	RemoteRevision pgtype.Text `json:"remote_revision"`
	SyncedRevision int64       `json:"synced_revision"`
	ID             pgtype.UUID `json:"id"`
	AccountID      pgtype.UUID `json:"account_id"`
}

func (q *Queries) CheckpointDraftRemote(ctx context.Context, arg CheckpointDraftRemoteParams) (Draft, error) {
	row := q.db.QueryRow(ctx, checkpointDraftRemote,
		arg.RemoteID,
		arg.RemoteRevision,
		arg.SyncedRevision,
		arg.ID,
		arg.AccountID,
	)
	var i Draft
	err := row.Scan(
		&i.ID,
		&i.AccountID,
		&i.RemoteID,
		&i.RemoteRevision,
		&i.Subject,
		&i.BodyText,
		&i.BodyHtmlSanitized,
		&i.LocalRevision,
		&i.SyncedRevision,
		&i.SyncStatus,
		&i.RemoteCheckpointAt,
		&i.LastRemoteSyncedAt,
		&i.DiscardedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createDraft = `-- name: CreateDraft :one
INSERT INTO drafts (
  id, account_id, subject, body_text, body_html_sanitized, remote_checkpoint_at
)
SELECT $1, accounts.id, $2, $3,
       $4, $5
FROM accounts
WHERE accounts.id = $6
  AND accounts.user_id = $7
  AND accounts.disabled_at IS NULL
RETURNING drafts.id, drafts.account_id, drafts.remote_id, drafts.remote_revision, drafts.subject, drafts.body_text, drafts.body_html_sanitized, drafts.local_revision, drafts.synced_revision, drafts.sync_status, drafts.remote_checkpoint_at, drafts.last_remote_synced_at, drafts.discarded_at, drafts.created_at, drafts.updated_at
`

type CreateDraftParams struct {
	ID                 pgtype.UUID        `json:"id"`
	Subject            string             `json:"subject"`
	BodyText           string             `json:"body_text"`
	BodyHtmlSanitized  string             `json:"body_html_sanitized"`
	RemoteCheckpointAt pgtype.Timestamptz `json:"remote_checkpoint_at"`
	AccountID          pgtype.UUID        `json:"account_id"`
	UserID             pgtype.UUID        `json:"user_id"`
}

func (q *Queries) CreateDraft(ctx context.Context, arg CreateDraftParams) (Draft, error) {
	row := q.db.QueryRow(ctx, createDraft,
		arg.ID,
		arg.Subject,
		arg.BodyText,
		arg.BodyHtmlSanitized,
		arg.RemoteCheckpointAt,
		arg.AccountID,
		arg.UserID,
	)
	var i Draft
	err := row.Scan(
		&i.ID,
		&i.AccountID,
		&i.RemoteID,
		&i.RemoteRevision,
		&i.Subject,
		&i.BodyText,
		&i.BodyHtmlSanitized,
		&i.LocalRevision,
		&i.SyncedRevision,
		&i.SyncStatus,
		&i.RemoteCheckpointAt,
		&i.LastRemoteSyncedAt,
		&i.DiscardedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createDraftAttachment = `-- name: CreateDraftAttachment :exec
INSERT INTO draft_attachments (draft_id, account_id, position, object_id, filename, media_type, size_bytes)
VALUES ($1, $2, $3, $4, $5, $6, $7)
`

type CreateDraftAttachmentParams struct {
	DraftID   pgtype.UUID `json:"draft_id"`
	AccountID pgtype.UUID `json:"account_id"`
	Position  int32       `json:"position"`
	ObjectID  string      `json:"object_id"`
	Filename  pgtype.Text `json:"filename"`
	MediaType string      `json:"media_type"`
	SizeBytes int64       `json:"size_bytes"`
}

func (q *Queries) CreateDraftAttachment(ctx context.Context, arg CreateDraftAttachmentParams) error {
	_, err := q.db.Exec(ctx, createDraftAttachment,
		arg.DraftID,
		arg.AccountID,
		arg.Position,
		arg.ObjectID,
		arg.Filename,
		arg.MediaType,
		arg.SizeBytes,
	)
	return err
}

const createDraftRecipient = `-- name: CreateDraftRecipient :exec
INSERT INTO draft_recipients (draft_id, account_id, role, position, display_name, address)
VALUES ($1, $2, $3, $4, $5, $6)
`

type CreateDraftRecipientParams struct {
	DraftID     pgtype.UUID `json:"draft_id"`
	AccountID   pgtype.UUID `json:"account_id"`
	Role        string      `json:"role"`
	Position    int32       `json:"position"`
	DisplayName pgtype.Text `json:"display_name"`
	Address     string      `json:"address"`
}

func (q *Queries) CreateDraftRecipient(ctx context.Context, arg CreateDraftRecipientParams) error {
	_, err := q.db.Exec(ctx, createDraftRecipient,
		arg.DraftID,
		arg.AccountID,
		arg.Role,
		arg.Position,
		arg.DisplayName,
		arg.Address,
	)
	return err
}

const deleteDraftAttachments = `-- name: DeleteDraftAttachments :exec
DELETE FROM draft_attachments WHERE draft_id = $1 AND account_id = $2
`

type DeleteDraftAttachmentsParams struct {
	DraftID   pgtype.UUID `json:"draft_id"`
	AccountID pgtype.UUID `json:"account_id"`
}

func (q *Queries) DeleteDraftAttachments(ctx context.Context, arg DeleteDraftAttachmentsParams) error {
	_, err := q.db.Exec(ctx, deleteDraftAttachments, arg.DraftID, arg.AccountID)
	return err
}

const deleteDraftRecipients = `-- name: DeleteDraftRecipients :exec
DELETE FROM draft_recipients WHERE draft_id = $1 AND account_id = $2
`

type DeleteDraftRecipientsParams struct {
	DraftID   pgtype.UUID `json:"draft_id"`
	AccountID pgtype.UUID `json:"account_id"`
}

func (q *Queries) DeleteDraftRecipients(ctx context.Context, arg DeleteDraftRecipientsParams) error {
	_, err := q.db.Exec(ctx, deleteDraftRecipients, arg.DraftID, arg.AccountID)
	return err
}

const discardDraft = `-- name: DiscardDraft :one
UPDATE drafts
SET sync_status = 'discarded', discarded_at = now(), updated_at = now()
FROM accounts
WHERE drafts.id = $1
  AND drafts.account_id = $2
  AND drafts.sync_status <> 'discarded'
  AND accounts.id = drafts.account_id
  AND accounts.user_id = $3
RETURNING drafts.id, drafts.account_id, drafts.remote_id, drafts.remote_revision, drafts.subject, drafts.body_text, drafts.body_html_sanitized, drafts.local_revision, drafts.synced_revision, drafts.sync_status, drafts.remote_checkpoint_at, drafts.last_remote_synced_at, drafts.discarded_at, drafts.created_at, drafts.updated_at
`

type DiscardDraftParams struct {
	ID        pgtype.UUID `json:"id"`
	AccountID pgtype.UUID `json:"account_id"`
	UserID    pgtype.UUID `json:"user_id"`
}

func (q *Queries) DiscardDraft(ctx context.Context, arg DiscardDraftParams) (Draft, error) {
	row := q.db.QueryRow(ctx, discardDraft, arg.ID, arg.AccountID, arg.UserID)
	var i Draft
	err := row.Scan(
		&i.ID,
		&i.AccountID,
		&i.RemoteID,
		&i.RemoteRevision,
		&i.Subject,
		&i.BodyText,
		&i.BodyHtmlSanitized,
		&i.LocalRevision,
		&i.SyncedRevision,
		&i.SyncStatus,
		&i.RemoteCheckpointAt,
		&i.LastRemoteSyncedAt,
		&i.DiscardedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getDraftByOwner = `-- name: GetDraftByOwner :one
SELECT drafts.id, drafts.account_id, drafts.remote_id, drafts.remote_revision, drafts.subject, drafts.body_text, drafts.body_html_sanitized, drafts.local_revision, drafts.synced_revision, drafts.sync_status, drafts.remote_checkpoint_at, drafts.last_remote_synced_at, drafts.discarded_at, drafts.created_at, drafts.updated_at
FROM drafts
JOIN accounts ON accounts.id = drafts.account_id
WHERE drafts.id = $1
  AND drafts.account_id = $2
  AND accounts.user_id = $3
`

type GetDraftByOwnerParams struct {
	ID        pgtype.UUID `json:"id"`
	AccountID pgtype.UUID `json:"account_id"`
	UserID    pgtype.UUID `json:"user_id"`
}

func (q *Queries) GetDraftByOwner(ctx context.Context, arg GetDraftByOwnerParams) (Draft, error) {
	row := q.db.QueryRow(ctx, getDraftByOwner, arg.ID, arg.AccountID, arg.UserID)
	var i Draft
	err := row.Scan(
		&i.ID,
		&i.AccountID,
		&i.RemoteID,
		&i.RemoteRevision,
		&i.Subject,
		&i.BodyText,
		&i.BodyHtmlSanitized,
		&i.LocalRevision,
		&i.SyncedRevision,
		&i.SyncStatus,
		&i.RemoteCheckpointAt,
		&i.LastRemoteSyncedAt,
		&i.DiscardedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listDraftAttachments = `-- name: ListDraftAttachments :many
SELECT draft_id, account_id, position, object_id, filename, media_type, size_bytes FROM draft_attachments
WHERE draft_id = $1 AND account_id = $2
ORDER BY position
`

type ListDraftAttachmentsParams struct {
	DraftID   pgtype.UUID `json:"draft_id"`
	AccountID pgtype.UUID `json:"account_id"`
}

func (q *Queries) ListDraftAttachments(ctx context.Context, arg ListDraftAttachmentsParams) ([]DraftAttachment, error) {
	rows, err := q.db.Query(ctx, listDraftAttachments, arg.DraftID, arg.AccountID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []DraftAttachment
	for rows.Next() {
		var i DraftAttachment
		if err := rows.Scan(
			&i.DraftID,
			&i.AccountID,
			&i.Position,
			&i.ObjectID,
			&i.Filename,
			&i.MediaType,
			&i.SizeBytes,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listDraftRecipients = `-- name: ListDraftRecipients :many
SELECT draft_id, account_id, role, position, display_name, address FROM draft_recipients
WHERE draft_id = $1 AND account_id = $2
ORDER BY CASE role WHEN 'to' THEN 0 WHEN 'cc' THEN 1 ELSE 2 END, position
`

type ListDraftRecipientsParams struct {
	DraftID   pgtype.UUID `json:"draft_id"`
	AccountID pgtype.UUID `json:"account_id"`
}

func (q *Queries) ListDraftRecipients(ctx context.Context, arg ListDraftRecipientsParams) ([]DraftRecipient, error) {
	rows, err := q.db.Query(ctx, listDraftRecipients, arg.DraftID, arg.AccountID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []DraftRecipient
	for rows.Next() {
		var i DraftRecipient
		if err := rows.Scan(
			&i.DraftID,
			&i.AccountID,
			&i.Role,
			&i.Position,
			&i.DisplayName,
			&i.Address,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lockDraftByOwner = `-- name: LockDraftByOwner :one
SELECT drafts.id, drafts.account_id, drafts.remote_id, drafts.remote_revision, drafts.subject, drafts.body_text, drafts.body_html_sanitized, drafts.local_revision, drafts.synced_revision, drafts.sync_status, drafts.remote_checkpoint_at, drafts.last_remote_synced_at, drafts.discarded_at, drafts.created_at, drafts.updated_at
FROM drafts
JOIN accounts ON accounts.id = drafts.account_id
WHERE drafts.id = $1
  AND drafts.account_id = $2
  AND accounts.user_id = $3
FOR UPDATE OF drafts
`

type LockDraftByOwnerParams struct {
	ID        pgtype.UUID `json:"id"`
	AccountID pgtype.UUID `json:"account_id"`
	UserID    pgtype.UUID `json:"user_id"`
}

func (q *Queries) LockDraftByOwner(ctx context.Context, arg LockDraftByOwnerParams) (Draft, error) {
	row := q.db.QueryRow(ctx, lockDraftByOwner, arg.ID, arg.AccountID, arg.UserID)
	var i Draft
	err := row.Scan(
		&i.ID,
		&i.AccountID,
		&i.RemoteID,
		&i.RemoteRevision,
		&i.Subject,
		&i.BodyText,
		&i.BodyHtmlSanitized,
		&i.LocalRevision,
		&i.SyncedRevision,
		&i.SyncStatus,
		&i.RemoteCheckpointAt,
		&i.LastRemoteSyncedAt,
		&i.DiscardedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const markDraftConflict = `-- name: MarkDraftConflict :one
UPDATE drafts
SET remote_id = COALESCE($1, remote_id),
    remote_revision = COALESCE($2, remote_revision),
    sync_status = 'conflict', updated_at = now()
FROM accounts
WHERE drafts.id = $3
  AND drafts.account_id = $4
  AND drafts.sync_status <> 'discarded'
  AND accounts.id = drafts.account_id
  AND accounts.user_id = $5
RETURNING drafts.id, drafts.account_id, drafts.remote_id, drafts.remote_revision, drafts.subject, drafts.body_text, drafts.body_html_sanitized, drafts.local_revision, drafts.synced_revision, drafts.sync_status, drafts.remote_checkpoint_at, drafts.last_remote_synced_at, drafts.discarded_at, drafts.created_at, drafts.updated_at
`

type MarkDraftConflictParams struct {
	RemoteID       pgtype.Text `json:"remote_id"`
	RemoteRevision pgtype.Text `json:"remote_revision"`
	ID             pgtype.UUID `json:"id"`
	AccountID      pgtype.UUID `json:"account_id"`
	UserID         pgtype.UUID `json:"user_id"`
}

func (q *Queries) MarkDraftConflict(ctx context.Context, arg MarkDraftConflictParams) (Draft, error) {
	row := q.db.QueryRow(ctx, markDraftConflict,
		arg.RemoteID,
		arg.RemoteRevision,
		arg.ID,
		arg.AccountID,
		arg.UserID,
	)
	var i Draft
	err := row.Scan(
		&i.ID,
		&i.AccountID,
		&i.RemoteID,
		&i.RemoteRevision,
		&i.Subject,
		&i.BodyText,
		&i.BodyHtmlSanitized,
		&i.LocalRevision,
		&i.SyncedRevision,
		&i.SyncStatus,
		&i.RemoteCheckpointAt,
		&i.LastRemoteSyncedAt,
		&i.DiscardedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateDraft = `-- name: UpdateDraft :one
UPDATE drafts
SET subject = $1, body_text = $2,
    body_html_sanitized = $3,
    local_revision = local_revision + 1, sync_status = 'queued',
    remote_checkpoint_at = $4, updated_at = now()
FROM accounts
WHERE drafts.id = $5
  AND drafts.account_id = $6
  AND drafts.local_revision = $7
  AND drafts.sync_status <> 'discarded'
  AND accounts.id = drafts.account_id
  AND accounts.user_id = $8
RETURNING drafts.id, drafts.account_id, drafts.remote_id, drafts.remote_revision, drafts.subject, drafts.body_text, drafts.body_html_sanitized, drafts.local_revision, drafts.synced_revision, drafts.sync_status, drafts.remote_checkpoint_at, drafts.last_remote_synced_at, drafts.discarded_at, drafts.created_at, drafts.updated_at
`

type UpdateDraftParams struct {
	Subject            string             `json:"subject"`
	BodyText           string             `json:"body_text"`
	BodyHtmlSanitized  string             `json:"body_html_sanitized"`
	RemoteCheckpointAt pgtype.Timestamptz `json:"remote_checkpoint_at"`
	ID                 pgtype.UUID        `json:"id"`
	AccountID          pgtype.UUID        `json:"account_id"`
	ExpectedRevision   int64              `json:"expected_revision"`
	UserID             pgtype.UUID        `json:"user_id"`
}

func (q *Queries) UpdateDraft(ctx context.Context, arg UpdateDraftParams) (Draft, error) {
	row := q.db.QueryRow(ctx, updateDraft,
		arg.Subject,
		arg.BodyText,
		arg.BodyHtmlSanitized,
		arg.RemoteCheckpointAt,
		arg.ID,
		arg.AccountID,
		arg.ExpectedRevision,
		arg.UserID,
	)
	var i Draft
	err := row.Scan(
		&i.ID,
		&i.AccountID,
		&i.RemoteID,
		&i.RemoteRevision,
		&i.Subject,
		&i.BodyText,
		&i.BodyHtmlSanitized,
		&i.LocalRevision,
		&i.SyncedRevision,
		&i.SyncStatus,
		&i.RemoteCheckpointAt,
		&i.LastRemoteSyncedAt,
		&i.DiscardedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
