// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: imap_messages.sql

package dbgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const deleteIMAPMessageLocation = `-- name: DeleteIMAPMessageLocation :execrows
DELETE FROM imap_message_locations
USING messages, mailboxes, accounts
WHERE imap_message_locations.message_id = messages.id
  AND imap_message_locations.mailbox_id = mailboxes.id
  AND imap_message_locations.account_id = messages.account_id
  AND imap_message_locations.account_id = mailboxes.account_id
  AND accounts.id = imap_message_locations.account_id
  AND accounts.user_id = $1
  AND imap_message_locations.account_id = $2
  AND messages.remote_id = $3
  AND mailboxes.remote_id = $4
  AND imap_message_locations.uid_validity = $5
  AND imap_message_locations.uid = $6
`

type DeleteIMAPMessageLocationParams struct {
	UserID          pgtype.UUID `json:"user_id"`
	AccountID       pgtype.UUID `json:"account_id"`
	MessageRemoteID string      `json:"message_remote_id"`
	MailboxRemoteID string      `json:"mailbox_remote_id"`
	UidValidity     int64       `json:"uid_validity"`
	Uid             int64       `json:"uid"`
}

func (q *Queries) DeleteIMAPMessageLocation(ctx context.Context, arg DeleteIMAPMessageLocationParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteIMAPMessageLocation,
		arg.UserID,
		arg.AccountID,
		arg.MessageRemoteID,
		arg.MailboxRemoteID,
		arg.UidValidity,
		arg.Uid,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const linkMessageMailboxByRemoteID = `-- name: LinkMessageMailboxByRemoteID :execrows
INSERT INTO message_mailboxes (message_id, mailbox_id, account_id)
SELECT $1, mailboxes.id, $2
FROM mailboxes
JOIN accounts ON accounts.id = mailboxes.account_id
WHERE mailboxes.account_id = $2
  AND accounts.user_id = $3
  AND accounts.disabled_at IS NULL
  AND mailboxes.remote_id = $4
ON CONFLICT (message_id, mailbox_id) DO NOTHING
`

type LinkMessageMailboxByRemoteIDParams struct {
	MessageID       pgtype.UUID `json:"message_id"`
	AccountID       pgtype.UUID `json:"account_id"`
	UserID          pgtype.UUID `json:"user_id"`
	MailboxRemoteID string      `json:"mailbox_remote_id"`
}

func (q *Queries) LinkMessageMailboxByRemoteID(ctx context.Context, arg LinkMessageMailboxByRemoteIDParams) (int64, error) {
	result, err := q.db.Exec(ctx, linkMessageMailboxByRemoteID,
		arg.MessageID,
		arg.AccountID,
		arg.UserID,
		arg.MailboxRemoteID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const listIMAPMessageLocations = `-- name: ListIMAPMessageLocations :many
SELECT
  messages.remote_id AS message_remote_id,
  mailboxes.remote_id AS mailbox_remote_id,
  imap_folder_cursors.wire_name,
  mailboxes.role,
  imap_message_locations.uid_validity,
  imap_message_locations.uid
FROM imap_message_locations
JOIN messages
  ON messages.id = imap_message_locations.message_id
  AND messages.account_id = imap_message_locations.account_id
JOIN mailboxes
  ON mailboxes.id = imap_message_locations.mailbox_id
  AND mailboxes.account_id = imap_message_locations.account_id
JOIN imap_folder_cursors
  ON imap_folder_cursors.mailbox_id = mailboxes.id
  AND imap_folder_cursors.account_id = mailboxes.account_id
JOIN accounts ON accounts.id = imap_message_locations.account_id
WHERE imap_message_locations.account_id = $1
  AND accounts.user_id = $2
  AND accounts.provider = 'imap'
  AND accounts.disabled_at IS NULL
  AND messages.remote_id = ANY($3::text[])
ORDER BY messages.remote_id, mailboxes.role NULLS LAST, mailboxes.remote_name
`

type ListIMAPMessageLocationsParams struct {
	AccountID        pgtype.UUID `json:"account_id"`
	UserID           pgtype.UUID `json:"user_id"`
	MessageRemoteIds []string    `json:"message_remote_ids"`
}

type ListIMAPMessageLocationsRow struct {
	MessageRemoteID string      `json:"message_remote_id"`
	MailboxRemoteID string      `json:"mailbox_remote_id"`
	WireName        string      `json:"wire_name"`
	Role            pgtype.Text `json:"role"`
	UidValidity     int64       `json:"uid_validity"`
	Uid             int64       `json:"uid"`
}

func (q *Queries) ListIMAPMessageLocations(ctx context.Context, arg ListIMAPMessageLocationsParams) ([]ListIMAPMessageLocationsRow, error) {
	rows, err := q.db.Query(ctx, listIMAPMessageLocations, arg.AccountID, arg.UserID, arg.MessageRemoteIds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListIMAPMessageLocationsRow
	for rows.Next() {
		var i ListIMAPMessageLocationsRow
		if err := rows.Scan(
			&i.MessageRemoteID,
			&i.MailboxRemoteID,
			&i.WireName,
			&i.Role,
			&i.UidValidity,
			&i.Uid,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertIMAPMessageLocation = `-- name: UpsertIMAPMessageLocation :one
INSERT INTO imap_message_locations (
  message_id, mailbox_id, account_id, uid_validity, uid
)
SELECT
  $1, mailboxes.id, $2,
  $3, $4
FROM mailboxes
JOIN accounts ON accounts.id = mailboxes.account_id
WHERE mailboxes.account_id = $2
  AND accounts.user_id = $5
  AND accounts.provider = 'imap'
  AND accounts.disabled_at IS NULL
  AND mailboxes.remote_id = $6
ON CONFLICT (message_id, mailbox_id) DO UPDATE SET
  uid_validity = EXCLUDED.uid_validity,
  uid = EXCLUDED.uid,
  updated_at = now()
RETURNING imap_message_locations.message_id, imap_message_locations.mailbox_id, imap_message_locations.account_id, imap_message_locations.uid_validity, imap_message_locations.uid, imap_message_locations.created_at, imap_message_locations.updated_at
`

type UpsertIMAPMessageLocationParams struct {
	MessageID       pgtype.UUID `json:"message_id"`
	AccountID       pgtype.UUID `json:"account_id"`
	UidValidity     int64       `json:"uid_validity"`
	Uid             int64       `json:"uid"`
	UserID          pgtype.UUID `json:"user_id"`
	MailboxRemoteID string      `json:"mailbox_remote_id"`
}

func (q *Queries) UpsertIMAPMessageLocation(ctx context.Context, arg UpsertIMAPMessageLocationParams) (ImapMessageLocation, error) {
	row := q.db.QueryRow(ctx, upsertIMAPMessageLocation,
		arg.MessageID,
		arg.AccountID,
		arg.UidValidity,
		arg.Uid,
		arg.UserID,
		arg.MailboxRemoteID,
	)
	var i ImapMessageLocation
	err := row.Scan(
		&i.MessageID,
		&i.MailboxID,
		&i.AccountID,
		&i.UidValidity,
		&i.Uid,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
