// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: imap_folders.sql

package dbgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const listIMAPFolderStatesByOwner = `-- name: ListIMAPFolderStatesByOwner :many
SELECT
  mailboxes.id AS mailbox_id,
  mailboxes.remote_id,
  mailboxes.remote_name,
  mailboxes.role,
  mailboxes.selectable,
  mailboxes.total_count,
  mailboxes.unread_count,
  imap_folder_cursors.identity_key,
  imap_folder_cursors.wire_name,
  imap_folder_cursors.namespace_prefix,
  imap_folder_cursors.delimiter,
  imap_folder_cursors.subscribed,
  imap_folder_cursors.uid_next,
  imap_folder_cursors.uid_validity,
  imap_folder_cursors.next_uid,
  imap_folder_cursors.state,
  imap_folder_cursors.version,
  imap_folder_cursors.invalidated_at,
  imap_folder_cursors.invalidation_reason,
  imap_folder_cursors.updated_at
FROM imap_folder_cursors
JOIN mailboxes
  ON mailboxes.id = imap_folder_cursors.mailbox_id
  AND mailboxes.account_id = imap_folder_cursors.account_id
JOIN accounts ON accounts.id = imap_folder_cursors.account_id
WHERE imap_folder_cursors.account_id = $1
  AND accounts.user_id = $2
ORDER BY mailboxes.remote_name, mailboxes.id
`

type ListIMAPFolderStatesByOwnerParams struct {
	AccountID pgtype.UUID `json:"account_id"`
	UserID    pgtype.UUID `json:"user_id"`
}

type ListIMAPFolderStatesByOwnerRow struct {
	MailboxID          pgtype.UUID        `json:"mailbox_id"`
	RemoteID           string             `json:"remote_id"`
	RemoteName         string             `json:"remote_name"`
	Role               pgtype.Text        `json:"role"`
	Selectable         bool               `json:"selectable"`
	TotalCount         int32              `json:"total_count"`
	UnreadCount        int32              `json:"unread_count"`
	IdentityKey        string             `json:"identity_key"`
	WireName           string             `json:"wire_name"`
	NamespacePrefix    string             `json:"namespace_prefix"`
	Delimiter          pgtype.Text        `json:"delimiter"`
	Subscribed         bool               `json:"subscribed"`
	UidNext            pgtype.Int8        `json:"uid_next"`
	UidValidity        pgtype.Int8        `json:"uid_validity"`
	NextUid            pgtype.Int8        `json:"next_uid"`
	State              string             `json:"state"`
	Version            int64              `json:"version"`
	InvalidatedAt      pgtype.Timestamptz `json:"invalidated_at"`
	InvalidationReason pgtype.Text        `json:"invalidation_reason"`
	UpdatedAt          pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) ListIMAPFolderStatesByOwner(ctx context.Context, arg ListIMAPFolderStatesByOwnerParams) ([]ListIMAPFolderStatesByOwnerRow, error) {
	rows, err := q.db.Query(ctx, listIMAPFolderStatesByOwner, arg.AccountID, arg.UserID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListIMAPFolderStatesByOwnerRow
	for rows.Next() {
		var i ListIMAPFolderStatesByOwnerRow
		if err := rows.Scan(
			&i.MailboxID,
			&i.RemoteID,
			&i.RemoteName,
			&i.Role,
			&i.Selectable,
			&i.TotalCount,
			&i.UnreadCount,
			&i.IdentityKey,
			&i.WireName,
			&i.NamespacePrefix,
			&i.Delimiter,
			&i.Subscribed,
			&i.UidNext,
			&i.UidValidity,
			&i.NextUid,
			&i.State,
			&i.Version,
			&i.InvalidatedAt,
			&i.InvalidationReason,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markIMAPFolderCursorMissing = `-- name: MarkIMAPFolderCursorMissing :exec
UPDATE imap_folder_cursors
SET state = 'missing', next_uid = NULL, invalidated_at = NULL,
    invalidation_reason = NULL, version = version + 1, updated_at = now()
FROM accounts
WHERE accounts.id = imap_folder_cursors.account_id
  AND accounts.user_id = $1
  AND imap_folder_cursors.account_id = $2
  AND imap_folder_cursors.identity_key = $3
`

type MarkIMAPFolderCursorMissingParams struct {
	UserID      pgtype.UUID `json:"user_id"`
	AccountID   pgtype.UUID `json:"account_id"`
	IdentityKey string      `json:"identity_key"`
}

func (q *Queries) MarkIMAPFolderCursorMissing(ctx context.Context, arg MarkIMAPFolderCursorMissingParams) error {
	_, err := q.db.Exec(ctx, markIMAPFolderCursorMissing, arg.UserID, arg.AccountID, arg.IdentityKey)
	return err
}

const markIMAPFolderMissing = `-- name: MarkIMAPFolderMissing :exec
UPDATE mailboxes
SET selectable = false, updated_at = now()
FROM imap_folder_cursors, accounts
WHERE mailboxes.id = imap_folder_cursors.mailbox_id
  AND mailboxes.account_id = imap_folder_cursors.account_id
  AND accounts.id = mailboxes.account_id
  AND accounts.user_id = $1
  AND mailboxes.account_id = $2
  AND imap_folder_cursors.identity_key = $3
`

type MarkIMAPFolderMissingParams struct {
	UserID      pgtype.UUID `json:"user_id"`
	AccountID   pgtype.UUID `json:"account_id"`
	IdentityKey string      `json:"identity_key"`
}

func (q *Queries) MarkIMAPFolderMissing(ctx context.Context, arg MarkIMAPFolderMissingParams) error {
	_, err := q.db.Exec(ctx, markIMAPFolderMissing, arg.UserID, arg.AccountID, arg.IdentityKey)
	return err
}

const renameIMAPMailboxIdentity = `-- name: RenameIMAPMailboxIdentity :one
UPDATE mailboxes
SET remote_id = $1,
    remote_name = $2,
    role = $3,
    selectable = $4,
    total_count = $5,
    unread_count = $6,
    remote_revision = $7,
    last_synced_at = now(),
    updated_at = now()
FROM accounts
WHERE mailboxes.id = $8
  AND mailboxes.account_id = $9
  AND accounts.id = mailboxes.account_id
  AND accounts.user_id = $10
  AND accounts.provider = 'imap'
  AND accounts.disabled_at IS NULL
RETURNING mailboxes.id, mailboxes.account_id, mailboxes.remote_id, mailboxes.remote_name, mailboxes.role, mailboxes.unread_count, mailboxes.local_name, mailboxes.selectable, mailboxes.total_count, mailboxes.remote_revision, mailboxes.last_synced_at, mailboxes.created_at, mailboxes.updated_at
`

type RenameIMAPMailboxIdentityParams struct {
	RemoteID       string      `json:"remote_id"`
	RemoteName     string      `json:"remote_name"`
	Role           pgtype.Text `json:"role"`
	Selectable     bool        `json:"selectable"`
	TotalCount     int32       `json:"total_count"`
	UnreadCount    int32       `json:"unread_count"`
	RemoteRevision pgtype.Text `json:"remote_revision"`
	MailboxID      pgtype.UUID `json:"mailbox_id"`
	AccountID      pgtype.UUID `json:"account_id"`
	UserID         pgtype.UUID `json:"user_id"`
}

func (q *Queries) RenameIMAPMailboxIdentity(ctx context.Context, arg RenameIMAPMailboxIdentityParams) (Mailbox, error) {
	row := q.db.QueryRow(ctx, renameIMAPMailboxIdentity,
		arg.RemoteID,
		arg.RemoteName,
		arg.Role,
		arg.Selectable,
		arg.TotalCount,
		arg.UnreadCount,
		arg.RemoteRevision,
		arg.MailboxID,
		arg.AccountID,
		arg.UserID,
	)
	var i Mailbox
	err := row.Scan(
		&i.ID,
		&i.AccountID,
		&i.RemoteID,
		&i.RemoteName,
		&i.Role,
		&i.UnreadCount,
		&i.LocalName,
		&i.Selectable,
		&i.TotalCount,
		&i.RemoteRevision,
		&i.LastSyncedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const upsertIMAPFolderState = `-- name: UpsertIMAPFolderState :one
INSERT INTO imap_folder_cursors (
  mailbox_id, account_id, identity_key, wire_name, namespace_prefix, delimiter,
  subscribed, uid_next, uid_validity, next_uid, state
) VALUES (
  $1, $2, $3, $4,
  $5, $6, $7,
  $8, $9, $10, $11
)
ON CONFLICT (mailbox_id, account_id) DO UPDATE SET
  identity_key = EXCLUDED.identity_key,
  wire_name = EXCLUDED.wire_name,
  namespace_prefix = EXCLUDED.namespace_prefix,
  delimiter = EXCLUDED.delimiter,
  subscribed = EXCLUDED.subscribed,
  uid_next = EXCLUDED.uid_next,
  uid_validity = EXCLUDED.uid_validity,
  next_uid = CASE
    WHEN imap_folder_cursors.uid_validity IS DISTINCT FROM EXCLUDED.uid_validity
      AND imap_folder_cursors.uid_validity IS NOT NULL
      AND EXCLUDED.uid_validity IS NOT NULL THEN 1
    ELSE EXCLUDED.next_uid
  END,
  state = CASE
    WHEN EXCLUDED.state IN ('not_selectable', 'missing') THEN EXCLUDED.state
    WHEN imap_folder_cursors.uid_validity IS DISTINCT FROM EXCLUDED.uid_validity
      AND imap_folder_cursors.uid_validity IS NOT NULL THEN 'resync_required'
    WHEN imap_folder_cursors.state = 'resync_required' THEN 'resync_required'
    ELSE EXCLUDED.state
  END,
  version = imap_folder_cursors.version + 1,
  invalidated_at = CASE
    WHEN EXCLUDED.state IN ('not_selectable', 'missing') THEN NULL
    WHEN imap_folder_cursors.uid_validity IS DISTINCT FROM EXCLUDED.uid_validity
      AND imap_folder_cursors.uid_validity IS NOT NULL
      AND EXCLUDED.uid_validity IS NOT NULL THEN now()
    WHEN imap_folder_cursors.state = 'resync_required' THEN imap_folder_cursors.invalidated_at
    ELSE NULL
  END,
  invalidation_reason = CASE
    WHEN EXCLUDED.state IN ('not_selectable', 'missing') THEN NULL
    WHEN imap_folder_cursors.uid_validity IS DISTINCT FROM EXCLUDED.uid_validity
      AND imap_folder_cursors.uid_validity IS NOT NULL
      AND EXCLUDED.uid_validity IS NOT NULL THEN 'uid_validity_changed'
    WHEN imap_folder_cursors.state = 'resync_required' THEN imap_folder_cursors.invalidation_reason
    ELSE NULL
  END,
  updated_at = now()
RETURNING mailbox_id, account_id, identity_key, namespace_prefix, delimiter, subscribed, uid_next, uid_validity, next_uid, state, version, invalidated_at, invalidation_reason, created_at, updated_at, wire_name
`

type UpsertIMAPFolderStateParams struct {
	MailboxID       pgtype.UUID `json:"mailbox_id"`
	AccountID       pgtype.UUID `json:"account_id"`
	IdentityKey     string      `json:"identity_key"`
	WireName        string      `json:"wire_name"`
	NamespacePrefix string      `json:"namespace_prefix"`
	Delimiter       pgtype.Text `json:"delimiter"`
	Subscribed      bool        `json:"subscribed"`
	UidNext         pgtype.Int8 `json:"uid_next"`
	UidValidity     pgtype.Int8 `json:"uid_validity"`
	NextUid         pgtype.Int8 `json:"next_uid"`
	State           string      `json:"state"`
}

func (q *Queries) UpsertIMAPFolderState(ctx context.Context, arg UpsertIMAPFolderStateParams) (ImapFolderCursor, error) {
	row := q.db.QueryRow(ctx, upsertIMAPFolderState,
		arg.MailboxID,
		arg.AccountID,
		arg.IdentityKey,
		arg.WireName,
		arg.NamespacePrefix,
		arg.Delimiter,
		arg.Subscribed,
		arg.UidNext,
		arg.UidValidity,
		arg.NextUid,
		arg.State,
	)
	var i ImapFolderCursor
	err := row.Scan(
		&i.MailboxID,
		&i.AccountID,
		&i.IdentityKey,
		&i.NamespacePrefix,
		&i.Delimiter,
		&i.Subscribed,
		&i.UidNext,
		&i.UidValidity,
		&i.NextUid,
		&i.State,
		&i.Version,
		&i.InvalidatedAt,
		&i.InvalidationReason,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.WireName,
	)
	return i, err
}
