// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: logs.sql

package dbgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const deleteExpiredLogEntries = `-- name: DeleteExpiredLogEntries :execrows
DELETE FROM log_entries WHERE occurred_at < $1
`

func (q *Queries) DeleteExpiredLogEntries(ctx context.Context, occurredAt pgtype.Timestamptz) (int64, error) {
	result, err := q.db.Exec(ctx, deleteExpiredLogEntries, occurredAt)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getLogDebugLease = `-- name: GetLogDebugLease :one
SELECT enabled_until FROM log_debug_lease WHERE singleton = true
`

func (q *Queries) GetLogDebugLease(ctx context.Context) (pgtype.Timestamptz, error) {
	row := q.db.QueryRow(ctx, getLogDebugLease)
	var enabled_until pgtype.Timestamptz
	err := row.Scan(&enabled_until)
	return enabled_until, err
}

const insertLogEntry = `-- name: InsertLogEntry :one
INSERT INTO log_entries (occurred_at, service, module, level, event, request_id, attributes)
VALUES ($1, $2, $3, $4, $5, $6, $7)
RETURNING id, occurred_at, service, module, level, event, request_id, attributes
`

type InsertLogEntryParams struct {
	OccurredAt pgtype.Timestamptz `json:"occurred_at"`
	Service    string             `json:"service"`
	Module     string             `json:"module"`
	Level      string             `json:"level"`
	Event      string             `json:"event"`
	RequestID  pgtype.Text        `json:"request_id"`
	Attributes []byte             `json:"attributes"`
}

func (q *Queries) InsertLogEntry(ctx context.Context, arg InsertLogEntryParams) (LogEntry, error) {
	row := q.db.QueryRow(ctx, insertLogEntry,
		arg.OccurredAt,
		arg.Service,
		arg.Module,
		arg.Level,
		arg.Event,
		arg.RequestID,
		arg.Attributes,
	)
	var i LogEntry
	err := row.Scan(
		&i.ID,
		&i.OccurredAt,
		&i.Service,
		&i.Module,
		&i.Level,
		&i.Event,
		&i.RequestID,
		&i.Attributes,
	)
	return i, err
}

const listLogEntries = `-- name: ListLogEntries :many
SELECT id, occurred_at, service, module, level, event, request_id, attributes
FROM log_entries
WHERE occurred_at >= $1 AND occurred_at < $2
  AND ($3::text = '' OR service = $3)
  AND ($4::text = '' OR module = $4)
  AND ($5::text = '' OR level = $5)
  AND ($6::text = '' OR event = $6)
  AND ($7::text = '' OR request_id = $7)
ORDER BY occurred_at DESC, id DESC
LIMIT $8
`

type ListLogEntriesParams struct {
	OccurredAt   pgtype.Timestamptz `json:"occurred_at"`
	OccurredAt_2 pgtype.Timestamptz `json:"occurred_at_2"`
	Column3      string             `json:"column_3"`
	Column4      string             `json:"column_4"`
	Column5      string             `json:"column_5"`
	Column6      string             `json:"column_6"`
	Column7      string             `json:"column_7"`
	Limit        int32              `json:"limit"`
}

func (q *Queries) ListLogEntries(ctx context.Context, arg ListLogEntriesParams) ([]LogEntry, error) {
	rows, err := q.db.Query(ctx, listLogEntries,
		arg.OccurredAt,
		arg.OccurredAt_2,
		arg.Column3,
		arg.Column4,
		arg.Column5,
		arg.Column6,
		arg.Column7,
		arg.Limit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []LogEntry
	for rows.Next() {
		var i LogEntry
		if err := rows.Scan(
			&i.ID,
			&i.OccurredAt,
			&i.Service,
			&i.Module,
			&i.Level,
			&i.Event,
			&i.RequestID,
			&i.Attributes,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setLogDebugLease = `-- name: SetLogDebugLease :one
UPDATE log_debug_lease SET enabled_until = $1, updated_at = $2
WHERE singleton = true
RETURNING enabled_until
`

type SetLogDebugLeaseParams struct {
	EnabledUntil pgtype.Timestamptz `json:"enabled_until"`
	UpdatedAt    pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) SetLogDebugLease(ctx context.Context, arg SetLogDebugLeaseParams) (pgtype.Timestamptz, error) {
	row := q.db.QueryRow(ctx, setLogDebugLease, arg.EnabledUntil, arg.UpdatedAt)
	var enabled_until pgtype.Timestamptz
	err := row.Scan(&enabled_until)
	return enabled_until, err
}
