// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: mailboxes.sql

package dbgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const ensureCategoryLabel = `-- name: EnsureCategoryLabel :one
INSERT INTO labels (
  id, account_id, remote_name, kind, category, color
)
SELECT
  $1, owned.id, $2, 'category',
  $3, $4
FROM accounts AS owned
WHERE owned.id = $5
  AND owned.user_id = $6
  AND owned.disabled_at IS NULL
ON CONFLICT (account_id, category) WHERE kind = 'category' DO UPDATE SET
  remote_name = EXCLUDED.remote_name,
  color = EXCLUDED.color,
  updated_at = now()
RETURNING id, account_id, remote_id, remote_name, local_name, kind, category, color, total_count, unread_count, remote_revision, last_synced_at, created_at, updated_at
`

type EnsureCategoryLabelParams struct {
	ID         pgtype.UUID `json:"id"`
	RemoteName string      `json:"remote_name"`
	Category   pgtype.Text `json:"category"`
	Color      pgtype.Text `json:"color"`
	AccountID  pgtype.UUID `json:"account_id"`
	UserID     pgtype.UUID `json:"user_id"`
}

func (q *Queries) EnsureCategoryLabel(ctx context.Context, arg EnsureCategoryLabelParams) (Label, error) {
	row := q.db.QueryRow(ctx, ensureCategoryLabel,
		arg.ID,
		arg.RemoteName,
		arg.Category,
		arg.Color,
		arg.AccountID,
		arg.UserID,
	)
	var i Label
	err := row.Scan(
		&i.ID,
		&i.AccountID,
		&i.RemoteID,
		&i.RemoteName,
		&i.LocalName,
		&i.Kind,
		&i.Category,
		&i.Color,
		&i.TotalCount,
		&i.UnreadCount,
		&i.RemoteRevision,
		&i.LastSyncedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listLabelsByAccount = `-- name: ListLabelsByAccount :many
SELECT labels.id, labels.account_id, labels.remote_id, labels.remote_name, labels.local_name, labels.kind, labels.category, labels.color, labels.total_count, labels.unread_count, labels.remote_revision, labels.last_synced_at, labels.created_at, labels.updated_at
FROM labels
JOIN accounts ON accounts.id = labels.account_id
WHERE labels.account_id = $1
  AND accounts.user_id = $2
ORDER BY labels.kind, COALESCE(labels.local_name, labels.remote_name), labels.id
`

type ListLabelsByAccountParams struct {
	AccountID pgtype.UUID `json:"account_id"`
	UserID    pgtype.UUID `json:"user_id"`
}

func (q *Queries) ListLabelsByAccount(ctx context.Context, arg ListLabelsByAccountParams) ([]Label, error) {
	rows, err := q.db.Query(ctx, listLabelsByAccount, arg.AccountID, arg.UserID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Label
	for rows.Next() {
		var i Label
		if err := rows.Scan(
			&i.ID,
			&i.AccountID,
			&i.RemoteID,
			&i.RemoteName,
			&i.LocalName,
			&i.Kind,
			&i.Category,
			&i.Color,
			&i.TotalCount,
			&i.UnreadCount,
			&i.RemoteRevision,
			&i.LastSyncedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMailboxesByAccount = `-- name: ListMailboxesByAccount :many
SELECT mailboxes.id, mailboxes.account_id, mailboxes.remote_id, mailboxes.remote_name, mailboxes.role, mailboxes.unread_count, mailboxes.local_name, mailboxes.selectable, mailboxes.total_count, mailboxes.remote_revision, mailboxes.last_synced_at, mailboxes.created_at, mailboxes.updated_at
FROM mailboxes
JOIN accounts ON accounts.id = mailboxes.account_id
WHERE mailboxes.account_id = $1
  AND accounts.user_id = $2
ORDER BY
  CASE mailboxes.role
    WHEN 'inbox' THEN 0
    WHEN 'sent' THEN 1
    WHEN 'drafts' THEN 2
    WHEN 'archive' THEN 3
    WHEN 'junk' THEN 4
    WHEN 'trash' THEN 5
    WHEN 'all' THEN 6
    ELSE 7
  END,
  COALESCE(mailboxes.local_name, mailboxes.remote_name),
  mailboxes.id
`

type ListMailboxesByAccountParams struct {
	AccountID pgtype.UUID `json:"account_id"`
	UserID    pgtype.UUID `json:"user_id"`
}

func (q *Queries) ListMailboxesByAccount(ctx context.Context, arg ListMailboxesByAccountParams) ([]Mailbox, error) {
	rows, err := q.db.Query(ctx, listMailboxesByAccount, arg.AccountID, arg.UserID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Mailbox
	for rows.Next() {
		var i Mailbox
		if err := rows.Scan(
			&i.ID,
			&i.AccountID,
			&i.RemoteID,
			&i.RemoteName,
			&i.Role,
			&i.UnreadCount,
			&i.LocalName,
			&i.Selectable,
			&i.TotalCount,
			&i.RemoteRevision,
			&i.LastSyncedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const reconcileMailbox = `-- name: ReconcileMailbox :one
INSERT INTO mailboxes (
  id, account_id, remote_id, remote_name, role, selectable,
  total_count, unread_count, remote_revision, last_synced_at
)
SELECT
  $1, owned.id, $2, $3,
  $4, $5, $6,
  $7, $8, $9
FROM accounts AS owned
WHERE owned.id = $10
  AND owned.user_id = $11
  AND owned.disabled_at IS NULL
ON CONFLICT (account_id, remote_id) DO UPDATE SET
  remote_name = EXCLUDED.remote_name,
  role = EXCLUDED.role,
  selectable = EXCLUDED.selectable,
  total_count = EXCLUDED.total_count,
  unread_count = EXCLUDED.unread_count,
  remote_revision = EXCLUDED.remote_revision,
  last_synced_at = EXCLUDED.last_synced_at,
  updated_at = now()
RETURNING id, account_id, remote_id, remote_name, role, unread_count, local_name, selectable, total_count, remote_revision, last_synced_at, created_at, updated_at
`

type ReconcileMailboxParams struct {
	ID             pgtype.UUID        `json:"id"`
	RemoteID       string             `json:"remote_id"`
	RemoteName     string             `json:"remote_name"`
	Role           pgtype.Text        `json:"role"`
	Selectable     bool               `json:"selectable"`
	TotalCount     int32              `json:"total_count"`
	UnreadCount    int32              `json:"unread_count"`
	RemoteRevision pgtype.Text        `json:"remote_revision"`
	LastSyncedAt   pgtype.Timestamptz `json:"last_synced_at"`
	AccountID      pgtype.UUID        `json:"account_id"`
	UserID         pgtype.UUID        `json:"user_id"`
}

func (q *Queries) ReconcileMailbox(ctx context.Context, arg ReconcileMailboxParams) (Mailbox, error) {
	row := q.db.QueryRow(ctx, reconcileMailbox,
		arg.ID,
		arg.RemoteID,
		arg.RemoteName,
		arg.Role,
		arg.Selectable,
		arg.TotalCount,
		arg.UnreadCount,
		arg.RemoteRevision,
		arg.LastSyncedAt,
		arg.AccountID,
		arg.UserID,
	)
	var i Mailbox
	err := row.Scan(
		&i.ID,
		&i.AccountID,
		&i.RemoteID,
		&i.RemoteName,
		&i.Role,
		&i.UnreadCount,
		&i.LocalName,
		&i.Selectable,
		&i.TotalCount,
		&i.RemoteRevision,
		&i.LastSyncedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const reconcileProviderLabel = `-- name: ReconcileProviderLabel :one
INSERT INTO labels (
  id, account_id, remote_id, remote_name, kind, color,
  total_count, unread_count, remote_revision, last_synced_at
)
SELECT
  $1, owned.id, $2, $3,
  $4, $5, $6,
  $7, $8, $9
FROM accounts AS owned
WHERE owned.id = $10
  AND owned.user_id = $11
  AND owned.disabled_at IS NULL
ON CONFLICT (account_id, remote_id) WHERE remote_id IS NOT NULL DO UPDATE SET
  remote_name = EXCLUDED.remote_name,
  kind = EXCLUDED.kind,
  color = EXCLUDED.color,
  total_count = EXCLUDED.total_count,
  unread_count = EXCLUDED.unread_count,
  remote_revision = EXCLUDED.remote_revision,
  last_synced_at = EXCLUDED.last_synced_at,
  updated_at = now()
RETURNING id, account_id, remote_id, remote_name, local_name, kind, category, color, total_count, unread_count, remote_revision, last_synced_at, created_at, updated_at
`

type ReconcileProviderLabelParams struct {
	ID             pgtype.UUID        `json:"id"`
	RemoteID       pgtype.Text        `json:"remote_id"`
	RemoteName     string             `json:"remote_name"`
	Kind           string             `json:"kind"`
	Color          pgtype.Text        `json:"color"`
	TotalCount     int32              `json:"total_count"`
	UnreadCount    int32              `json:"unread_count"`
	RemoteRevision pgtype.Text        `json:"remote_revision"`
	LastSyncedAt   pgtype.Timestamptz `json:"last_synced_at"`
	AccountID      pgtype.UUID        `json:"account_id"`
	UserID         pgtype.UUID        `json:"user_id"`
}

func (q *Queries) ReconcileProviderLabel(ctx context.Context, arg ReconcileProviderLabelParams) (Label, error) {
	row := q.db.QueryRow(ctx, reconcileProviderLabel,
		arg.ID,
		arg.RemoteID,
		arg.RemoteName,
		arg.Kind,
		arg.Color,
		arg.TotalCount,
		arg.UnreadCount,
		arg.RemoteRevision,
		arg.LastSyncedAt,
		arg.AccountID,
		arg.UserID,
	)
	var i Label
	err := row.Scan(
		&i.ID,
		&i.AccountID,
		&i.RemoteID,
		&i.RemoteName,
		&i.LocalName,
		&i.Kind,
		&i.Category,
		&i.Color,
		&i.TotalCount,
		&i.UnreadCount,
		&i.RemoteRevision,
		&i.LastSyncedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const renameLabelLocal = `-- name: RenameLabelLocal :one
UPDATE labels
SET local_name = NULLIF(btrim($1::text), ''), updated_at = now()
FROM accounts
WHERE labels.id = $2
  AND labels.account_id = $3
  AND accounts.id = labels.account_id
  AND accounts.user_id = $4
RETURNING labels.id, labels.account_id, labels.remote_id, labels.remote_name, labels.local_name, labels.kind, labels.category, labels.color, labels.total_count, labels.unread_count, labels.remote_revision, labels.last_synced_at, labels.created_at, labels.updated_at
`

type RenameLabelLocalParams struct {
	LocalName string      `json:"local_name"`
	ID        pgtype.UUID `json:"id"`
	AccountID pgtype.UUID `json:"account_id"`
	UserID    pgtype.UUID `json:"user_id"`
}

func (q *Queries) RenameLabelLocal(ctx context.Context, arg RenameLabelLocalParams) (Label, error) {
	row := q.db.QueryRow(ctx, renameLabelLocal,
		arg.LocalName,
		arg.ID,
		arg.AccountID,
		arg.UserID,
	)
	var i Label
	err := row.Scan(
		&i.ID,
		&i.AccountID,
		&i.RemoteID,
		&i.RemoteName,
		&i.LocalName,
		&i.Kind,
		&i.Category,
		&i.Color,
		&i.TotalCount,
		&i.UnreadCount,
		&i.RemoteRevision,
		&i.LastSyncedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const renameMailboxLocal = `-- name: RenameMailboxLocal :one
UPDATE mailboxes
SET local_name = NULLIF(btrim($1::text), ''), updated_at = now()
FROM accounts
WHERE mailboxes.id = $2
  AND mailboxes.account_id = $3
  AND accounts.id = mailboxes.account_id
  AND accounts.user_id = $4
RETURNING mailboxes.id, mailboxes.account_id, mailboxes.remote_id, mailboxes.remote_name, mailboxes.role, mailboxes.unread_count, mailboxes.local_name, mailboxes.selectable, mailboxes.total_count, mailboxes.remote_revision, mailboxes.last_synced_at, mailboxes.created_at, mailboxes.updated_at
`

type RenameMailboxLocalParams struct {
	LocalName string      `json:"local_name"`
	ID        pgtype.UUID `json:"id"`
	AccountID pgtype.UUID `json:"account_id"`
	UserID    pgtype.UUID `json:"user_id"`
}

func (q *Queries) RenameMailboxLocal(ctx context.Context, arg RenameMailboxLocalParams) (Mailbox, error) {
	row := q.db.QueryRow(ctx, renameMailboxLocal,
		arg.LocalName,
		arg.ID,
		arg.AccountID,
		arg.UserID,
	)
	var i Mailbox
	err := row.Scan(
		&i.ID,
		&i.AccountID,
		&i.RemoteID,
		&i.RemoteName,
		&i.Role,
		&i.UnreadCount,
		&i.LocalName,
		&i.Selectable,
		&i.TotalCount,
		&i.RemoteRevision,
		&i.LastSyncedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateLabelCounters = `-- name: UpdateLabelCounters :one
UPDATE labels
SET total_count = $1, unread_count = $2, updated_at = now()
FROM accounts
WHERE labels.id = $3
  AND labels.account_id = $4
  AND accounts.id = labels.account_id
  AND accounts.user_id = $5
RETURNING labels.id, labels.account_id, labels.remote_id, labels.remote_name, labels.local_name, labels.kind, labels.category, labels.color, labels.total_count, labels.unread_count, labels.remote_revision, labels.last_synced_at, labels.created_at, labels.updated_at
`

type UpdateLabelCountersParams struct {
	TotalCount  int32       `json:"total_count"`
	UnreadCount int32       `json:"unread_count"`
	ID          pgtype.UUID `json:"id"`
	AccountID   pgtype.UUID `json:"account_id"`
	UserID      pgtype.UUID `json:"user_id"`
}

func (q *Queries) UpdateLabelCounters(ctx context.Context, arg UpdateLabelCountersParams) (Label, error) {
	row := q.db.QueryRow(ctx, updateLabelCounters,
		arg.TotalCount,
		arg.UnreadCount,
		arg.ID,
		arg.AccountID,
		arg.UserID,
	)
	var i Label
	err := row.Scan(
		&i.ID,
		&i.AccountID,
		&i.RemoteID,
		&i.RemoteName,
		&i.LocalName,
		&i.Kind,
		&i.Category,
		&i.Color,
		&i.TotalCount,
		&i.UnreadCount,
		&i.RemoteRevision,
		&i.LastSyncedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateMailboxCounters = `-- name: UpdateMailboxCounters :one
UPDATE mailboxes
SET total_count = $1, unread_count = $2, updated_at = now()
FROM accounts
WHERE mailboxes.id = $3
  AND mailboxes.account_id = $4
  AND accounts.id = mailboxes.account_id
  AND accounts.user_id = $5
RETURNING mailboxes.id, mailboxes.account_id, mailboxes.remote_id, mailboxes.remote_name, mailboxes.role, mailboxes.unread_count, mailboxes.local_name, mailboxes.selectable, mailboxes.total_count, mailboxes.remote_revision, mailboxes.last_synced_at, mailboxes.created_at, mailboxes.updated_at
`

type UpdateMailboxCountersParams struct {
	TotalCount  int32       `json:"total_count"`
	UnreadCount int32       `json:"unread_count"`
	ID          pgtype.UUID `json:"id"`
	AccountID   pgtype.UUID `json:"account_id"`
	UserID      pgtype.UUID `json:"user_id"`
}

func (q *Queries) UpdateMailboxCounters(ctx context.Context, arg UpdateMailboxCountersParams) (Mailbox, error) {
	row := q.db.QueryRow(ctx, updateMailboxCounters,
		arg.TotalCount,
		arg.UnreadCount,
		arg.ID,
		arg.AccountID,
		arg.UserID,
	)
	var i Mailbox
	err := row.Scan(
		&i.ID,
		&i.AccountID,
		&i.RemoteID,
		&i.RemoteName,
		&i.Role,
		&i.UnreadCount,
		&i.LocalName,
		&i.Selectable,
		&i.TotalCount,
		&i.RemoteRevision,
		&i.LastSyncedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
