// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: message_memberships.sql

package dbgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const deleteMessageLabelMemberships = `-- name: DeleteMessageLabelMemberships :execrows
DELETE FROM message_labels
USING accounts
WHERE message_labels.message_id = $1
  AND message_labels.account_id = $2
  AND accounts.id = message_labels.account_id
  AND accounts.user_id = $3
  AND accounts.disabled_at IS NULL
`

type DeleteMessageLabelMembershipsParams struct {
	MessageID pgtype.UUID `json:"message_id"`
	AccountID pgtype.UUID `json:"account_id"`
	UserID    pgtype.UUID `json:"user_id"`
}

func (q *Queries) DeleteMessageLabelMemberships(ctx context.Context, arg DeleteMessageLabelMembershipsParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteMessageLabelMemberships, arg.MessageID, arg.AccountID, arg.UserID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteMessageMailboxMemberships = `-- name: DeleteMessageMailboxMemberships :execrows
DELETE FROM message_mailboxes
USING accounts
WHERE message_mailboxes.message_id = $1
  AND message_mailboxes.account_id = $2
  AND accounts.id = message_mailboxes.account_id
  AND accounts.user_id = $3
  AND accounts.disabled_at IS NULL
`

type DeleteMessageMailboxMembershipsParams struct {
	MessageID pgtype.UUID `json:"message_id"`
	AccountID pgtype.UUID `json:"account_id"`
	UserID    pgtype.UUID `json:"user_id"`
}

func (q *Queries) DeleteMessageMailboxMemberships(ctx context.Context, arg DeleteMessageMailboxMembershipsParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteMessageMailboxMemberships, arg.MessageID, arg.AccountID, arg.UserID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const linkMessageLabelByCategory = `-- name: LinkMessageLabelByCategory :execrows
INSERT INTO message_labels (message_id, label_id, account_id)
SELECT $1, labels.id, $2
FROM labels
JOIN accounts ON accounts.id = labels.account_id
WHERE labels.account_id = $2
  AND accounts.user_id = $3
  AND accounts.disabled_at IS NULL
  AND labels.kind = 'category'
  AND labels.category = $4
ON CONFLICT (message_id, label_id) DO NOTHING
`

type LinkMessageLabelByCategoryParams struct {
	MessageID pgtype.UUID `json:"message_id"`
	AccountID pgtype.UUID `json:"account_id"`
	UserID    pgtype.UUID `json:"user_id"`
	Category  pgtype.Text `json:"category"`
}

func (q *Queries) LinkMessageLabelByCategory(ctx context.Context, arg LinkMessageLabelByCategoryParams) (int64, error) {
	result, err := q.db.Exec(ctx, linkMessageLabelByCategory,
		arg.MessageID,
		arg.AccountID,
		arg.UserID,
		arg.Category,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const linkMessageLabelByRemoteID = `-- name: LinkMessageLabelByRemoteID :execrows
INSERT INTO message_labels (message_id, label_id, account_id)
SELECT $1, labels.id, $2
FROM labels
JOIN accounts ON accounts.id = labels.account_id
WHERE labels.account_id = $2
  AND accounts.user_id = $3
  AND accounts.disabled_at IS NULL
  AND labels.remote_id = $4
ON CONFLICT (message_id, label_id) DO NOTHING
`

type LinkMessageLabelByRemoteIDParams struct {
	MessageID     pgtype.UUID `json:"message_id"`
	AccountID     pgtype.UUID `json:"account_id"`
	UserID        pgtype.UUID `json:"user_id"`
	LabelRemoteID pgtype.Text `json:"label_remote_id"`
}

func (q *Queries) LinkMessageLabelByRemoteID(ctx context.Context, arg LinkMessageLabelByRemoteIDParams) (int64, error) {
	result, err := q.db.Exec(ctx, linkMessageLabelByRemoteID,
		arg.MessageID,
		arg.AccountID,
		arg.UserID,
		arg.LabelRemoteID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
