// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: metrics.sql

package dbgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const deleteExpiredMetricPoints = `-- name: DeleteExpiredMetricPoints :execrows
DELETE FROM metric_points
WHERE (resolution = 'minute' AND bucket < $1)
   OR (resolution = 'hour' AND bucket < $2)
`

type DeleteExpiredMetricPointsParams struct {
	Bucket   pgtype.Timestamptz `json:"bucket"`
	Bucket_2 pgtype.Timestamptz `json:"bucket_2"`
}

func (q *Queries) DeleteExpiredMetricPoints(ctx context.Context, arg DeleteExpiredMetricPointsParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteExpiredMetricPoints, arg.Bucket, arg.Bucket_2)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const listMetricPoints = `-- name: ListMetricPoints :many
SELECT bucket, resolution, name, kind, dimensions, value, count,
       min_value, max_value, histogram, updated_at
FROM metric_points
WHERE resolution = $1
  AND bucket >= $2
  AND bucket < $3
  AND ($4::text = '' OR name = $4)
ORDER BY bucket ASC, name ASC, dimensions ASC
LIMIT $5
`

type ListMetricPointsParams struct {
	Resolution string             `json:"resolution"`
	Bucket     pgtype.Timestamptz `json:"bucket"`
	Bucket_2   pgtype.Timestamptz `json:"bucket_2"`
	Column4    string             `json:"column_4"`
	Limit      int32              `json:"limit"`
}

func (q *Queries) ListMetricPoints(ctx context.Context, arg ListMetricPointsParams) ([]MetricPoint, error) {
	rows, err := q.db.Query(ctx, listMetricPoints,
		arg.Resolution,
		arg.Bucket,
		arg.Bucket_2,
		arg.Column4,
		arg.Limit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []MetricPoint
	for rows.Next() {
		var i MetricPoint
		if err := rows.Scan(
			&i.Bucket,
			&i.Resolution,
			&i.Name,
			&i.Kind,
			&i.Dimensions,
			&i.Value,
			&i.Count,
			&i.MinValue,
			&i.MaxValue,
			&i.Histogram,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMetricPointsForRollup = `-- name: ListMetricPointsForRollup :many
SELECT bucket, resolution, name, kind, dimensions, value, count,
       min_value, max_value, histogram, updated_at
FROM metric_points
WHERE resolution = $1 AND bucket >= $2 AND bucket < $3
ORDER BY bucket ASC, name ASC, dimensions ASC
`

type ListMetricPointsForRollupParams struct {
	Resolution string             `json:"resolution"`
	Bucket     pgtype.Timestamptz `json:"bucket"`
	Bucket_2   pgtype.Timestamptz `json:"bucket_2"`
}

func (q *Queries) ListMetricPointsForRollup(ctx context.Context, arg ListMetricPointsForRollupParams) ([]MetricPoint, error) {
	rows, err := q.db.Query(ctx, listMetricPointsForRollup, arg.Resolution, arg.Bucket, arg.Bucket_2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []MetricPoint
	for rows.Next() {
		var i MetricPoint
		if err := rows.Scan(
			&i.Bucket,
			&i.Resolution,
			&i.Name,
			&i.Kind,
			&i.Dimensions,
			&i.Value,
			&i.Count,
			&i.MinValue,
			&i.MaxValue,
			&i.Histogram,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const replaceMetricPoint = `-- name: ReplaceMetricPoint :exec
INSERT INTO metric_points (
  bucket, resolution, name, kind, dimensions, value, count,
  min_value, max_value, histogram, updated_at
)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11)
ON CONFLICT (bucket, resolution, name, dimensions) DO UPDATE SET
  kind = EXCLUDED.kind,
  value = EXCLUDED.value,
  count = EXCLUDED.count,
  min_value = EXCLUDED.min_value,
  max_value = EXCLUDED.max_value,
  histogram = EXCLUDED.histogram,
  updated_at = EXCLUDED.updated_at
`

type ReplaceMetricPointParams struct {
	Bucket     pgtype.Timestamptz `json:"bucket"`
	Resolution string             `json:"resolution"`
	Name       string             `json:"name"`
	Kind       string             `json:"kind"`
	Dimensions []byte             `json:"dimensions"`
	Value      float64            `json:"value"`
	Count      int64              `json:"count"`
	MinValue   float64            `json:"min_value"`
	MaxValue   float64            `json:"max_value"`
	Histogram  []int64            `json:"histogram"`
	UpdatedAt  pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) ReplaceMetricPoint(ctx context.Context, arg ReplaceMetricPointParams) error {
	_, err := q.db.Exec(ctx, replaceMetricPoint,
		arg.Bucket,
		arg.Resolution,
		arg.Name,
		arg.Kind,
		arg.Dimensions,
		arg.Value,
		arg.Count,
		arg.MinValue,
		arg.MaxValue,
		arg.Histogram,
		arg.UpdatedAt,
	)
	return err
}

const upsertMetricMinute = `-- name: UpsertMetricMinute :execrows
INSERT INTO metric_points (
  bucket, resolution, name, kind, dimensions, value, count,
  min_value, max_value, histogram, updated_at
)
VALUES ($1, 'minute', $2, $3, $4, $5, $6, $7, $8, $9, $10)
ON CONFLICT (bucket, resolution, name, dimensions) DO UPDATE SET
  value = CASE
    WHEN EXCLUDED.kind = 'gauge' THEN EXCLUDED.value
    ELSE metric_points.value + EXCLUDED.value
  END,
  count = CASE
    WHEN EXCLUDED.kind = 'gauge' THEN 1
    ELSE metric_points.count + EXCLUDED.count
  END,
  min_value = CASE
    WHEN EXCLUDED.kind = 'gauge' THEN EXCLUDED.min_value
    ELSE LEAST(metric_points.min_value, EXCLUDED.min_value)
  END,
  max_value = CASE
    WHEN EXCLUDED.kind = 'gauge' THEN EXCLUDED.max_value
    ELSE GREATEST(metric_points.max_value, EXCLUDED.max_value)
  END,
  histogram = CASE
    WHEN EXCLUDED.kind = 'histogram' THEN ARRAY(
      SELECT metric_points.histogram[index] + EXCLUDED.histogram[index]
      FROM generate_subscripts(EXCLUDED.histogram, 1) AS indexes(index)
    )
    ELSE EXCLUDED.histogram
  END,
  updated_at = EXCLUDED.updated_at
WHERE metric_points.kind = EXCLUDED.kind
`

type UpsertMetricMinuteParams struct {
	Bucket     pgtype.Timestamptz `json:"bucket"`
	Name       string             `json:"name"`
	Kind       string             `json:"kind"`
	Dimensions []byte             `json:"dimensions"`
	Value      float64            `json:"value"`
	Count      int64              `json:"count"`
	MinValue   float64            `json:"min_value"`
	MaxValue   float64            `json:"max_value"`
	Histogram  []int64            `json:"histogram"`
	UpdatedAt  pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) UpsertMetricMinute(ctx context.Context, arg UpsertMetricMinuteParams) (int64, error) {
	result, err := q.db.Exec(ctx, upsertMetricMinute,
		arg.Bucket,
		arg.Name,
		arg.Kind,
		arg.Dimensions,
		arg.Value,
		arg.Count,
		arg.MinValue,
		arg.MaxValue,
		arg.Histogram,
		arg.UpdatedAt,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
