// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package dbgen

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Account struct {
	ID                   pgtype.UUID        `json:"id"`
	UserID               pgtype.UUID        `json:"user_id"`
	Provider             string             `json:"provider"`
	DisplayName          string             `json:"display_name"`
	EncryptedCredentials []byte             `json:"encrypted_credentials"`
	CredentialNonce      []byte             `json:"credential_nonce"`
	Capabilities         []byte             `json:"capabilities"`
	SyncState            string             `json:"sync_state"`
	CreatedAt            pgtype.Timestamptz `json:"created_at"`
	UpdatedAt            pgtype.Timestamptz `json:"updated_at"`
	RemoteID             string             `json:"remote_id"`
	DisabledAt           pgtype.Timestamptz `json:"disabled_at"`
}

type AuthAccount struct {
	ID                    pgtype.UUID        `json:"id"`
	AccountID             string             `json:"account_id"`
	ProviderID            string             `json:"provider_id"`
	UserID                pgtype.UUID        `json:"user_id"`
	AccessToken           pgtype.Text        `json:"access_token"`
	RefreshToken          pgtype.Text        `json:"refresh_token"`
	IDToken               pgtype.Text        `json:"id_token"`
	AccessTokenExpiresAt  pgtype.Timestamptz `json:"access_token_expires_at"`
	RefreshTokenExpiresAt pgtype.Timestamptz `json:"refresh_token_expires_at"`
	Scope                 pgtype.Text        `json:"scope"`
	Password              pgtype.Text        `json:"password"`
	CreatedAt             pgtype.Timestamptz `json:"created_at"`
	UpdatedAt             pgtype.Timestamptz `json:"updated_at"`
}

type AuthJwk struct {
	ID         pgtype.UUID        `json:"id"`
	PublicKey  string             `json:"public_key"`
	PrivateKey string             `json:"private_key"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
	ExpiresAt  pgtype.Timestamptz `json:"expires_at"`
	Alg        pgtype.Text        `json:"alg"`
	Crv        pgtype.Text        `json:"crv"`
}

type AuthPasskey struct {
	ID           pgtype.UUID        `json:"id"`
	Name         pgtype.Text        `json:"name"`
	PublicKey    string             `json:"public_key"`
	UserID       pgtype.UUID        `json:"user_id"`
	CredentialID string             `json:"credential_id"`
	Counter      int32              `json:"counter"`
	DeviceType   string             `json:"device_type"`
	BackedUp     bool               `json:"backed_up"`
	Transports   pgtype.Text        `json:"transports"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	Aaguid       pgtype.Text        `json:"aaguid"`
}

type AuthSession struct {
	ID        pgtype.UUID        `json:"id"`
	ExpiresAt pgtype.Timestamptz `json:"expires_at"`
	Token     string             `json:"token"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
	IpAddress pgtype.Text        `json:"ip_address"`
	UserAgent pgtype.Text        `json:"user_agent"`
	UserID    pgtype.UUID        `json:"user_id"`
}

type AuthVerification struct {
	ID         pgtype.UUID        `json:"id"`
	Identifier string             `json:"identifier"`
	Value      string             `json:"value"`
	ExpiresAt  pgtype.Timestamptz `json:"expires_at"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
	UpdatedAt  pgtype.Timestamptz `json:"updated_at"`
}

type CdnObject struct {
	ObjectID          string             `json:"object_id"`
	Namespace         string             `json:"namespace"`
	AccountID         pgtype.UUID        `json:"account_id"`
	RecoveryReference pgtype.Text        `json:"recovery_reference"`
	Filename          pgtype.Text        `json:"filename"`
	MediaType         string             `json:"media_type"`
	SizeBytes         int64              `json:"size_bytes"`
	Etag              string             `json:"etag"`
	StorageStatus     string             `json:"storage_status"`
	ExpiresAt         pgtype.Timestamptz `json:"expires_at"`
	StoredAt          pgtype.Timestamptz `json:"stored_at"`
	LastAccessedAt    pgtype.Timestamptz `json:"last_accessed_at"`
	CreatedAt         pgtype.Timestamptz `json:"created_at"`
	UpdatedAt         pgtype.Timestamptz `json:"updated_at"`
}

type Draft struct {
	ID                 pgtype.UUID        `json:"id"`
	AccountID          pgtype.UUID        `json:"account_id"`
	RemoteID           pgtype.Text        `json:"remote_id"`
	RemoteRevision     pgtype.Text        `json:"remote_revision"`
	Subject            string             `json:"subject"`
	BodyText           string             `json:"body_text"`
	BodyHtmlSanitized  string             `json:"body_html_sanitized"`
	LocalRevision      int64              `json:"local_revision"`
	SyncedRevision     int64              `json:"synced_revision"`
	SyncStatus         string             `json:"sync_status"`
	RemoteCheckpointAt pgtype.Timestamptz `json:"remote_checkpoint_at"`
	LastRemoteSyncedAt pgtype.Timestamptz `json:"last_remote_synced_at"`
	DiscardedAt        pgtype.Timestamptz `json:"discarded_at"`
	CreatedAt          pgtype.Timestamptz `json:"created_at"`
	UpdatedAt          pgtype.Timestamptz `json:"updated_at"`
	ComposeMode        string             `json:"compose_mode"`
	SourceMessageID    pgtype.UUID        `json:"source_message_id"`
}

type DraftAttachment struct {
	DraftID         pgtype.UUID `json:"draft_id"`
	AccountID       pgtype.UUID `json:"account_id"`
	Position        int32       `json:"position"`
	ObjectID        string      `json:"object_id"`
	Filename        pgtype.Text `json:"filename"`
	MediaType       string      `json:"media_type"`
	SizeBytes       int64       `json:"size_bytes"`
	ObjectNamespace pgtype.Text `json:"object_namespace"`
}

type DraftRecipient struct {
	DraftID     pgtype.UUID `json:"draft_id"`
	AccountID   pgtype.UUID `json:"account_id"`
	Role        string      `json:"role"`
	Position    int32       `json:"position"`
	DisplayName pgtype.Text `json:"display_name"`
	Address     string      `json:"address"`
}

type Label struct {
	ID             pgtype.UUID        `json:"id"`
	AccountID      pgtype.UUID        `json:"account_id"`
	RemoteID       pgtype.Text        `json:"remote_id"`
	RemoteName     string             `json:"remote_name"`
	LocalName      pgtype.Text        `json:"local_name"`
	Kind           string             `json:"kind"`
	Category       pgtype.Text        `json:"category"`
	Color          pgtype.Text        `json:"color"`
	TotalCount     int32              `json:"total_count"`
	UnreadCount    int32              `json:"unread_count"`
	RemoteRevision pgtype.Text        `json:"remote_revision"`
	LastSyncedAt   pgtype.Timestamptz `json:"last_synced_at"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	UpdatedAt      pgtype.Timestamptz `json:"updated_at"`
}

type LogDebugLease struct {
	Singleton    bool               `json:"singleton"`
	EnabledUntil pgtype.Timestamptz `json:"enabled_until"`
	UpdatedAt    pgtype.Timestamptz `json:"updated_at"`
}

type LogEntry struct {
	ID         int64              `json:"id"`
	OccurredAt pgtype.Timestamptz `json:"occurred_at"`
	Service    string             `json:"service"`
	Module     string             `json:"module"`
	Level      string             `json:"level"`
	Event      string             `json:"event"`
	RequestID  pgtype.Text        `json:"request_id"`
	Attributes []byte             `json:"attributes"`
}

type Mailbox struct {
	ID             pgtype.UUID        `json:"id"`
	AccountID      pgtype.UUID        `json:"account_id"`
	RemoteID       string             `json:"remote_id"`
	RemoteName     string             `json:"remote_name"`
	Role           pgtype.Text        `json:"role"`
	UnreadCount    int32              `json:"unread_count"`
	LocalName      pgtype.Text        `json:"local_name"`
	Selectable     bool               `json:"selectable"`
	TotalCount     int32              `json:"total_count"`
	RemoteRevision pgtype.Text        `json:"remote_revision"`
	LastSyncedAt   pgtype.Timestamptz `json:"last_synced_at"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	UpdatedAt      pgtype.Timestamptz `json:"updated_at"`
}

type Message struct {
	ID                pgtype.UUID        `json:"id"`
	ThreadID          pgtype.UUID        `json:"thread_id"`
	RemoteID          string             `json:"remote_id"`
	MessageID         pgtype.Text        `json:"message_id"`
	ReferencesHeader  []string           `json:"references_header"`
	Sender            []byte             `json:"sender"`
	Recipients        []byte             `json:"recipients"`
	Subject           string             `json:"subject"`
	BodyText          string             `json:"body_text"`
	BodyHtmlSanitized string             `json:"body_html_sanitized"`
	SentAt            pgtype.Timestamptz `json:"sent_at"`
	AccountID         pgtype.UUID        `json:"account_id"`
	IsRead            bool               `json:"is_read"`
	IsStarred         bool               `json:"is_starred"`
	IsImportant       bool               `json:"is_important"`
	DeletedAt         pgtype.Timestamptz `json:"deleted_at"`
	CreatedAt         pgtype.Timestamptz `json:"created_at"`
	UpdatedAt         pgtype.Timestamptz `json:"updated_at"`
	InReplyTo         []string           `json:"in_reply_to"`
	ContentUpdatedAt  pgtype.Timestamptz `json:"content_updated_at"`
	SearchVector      interface{}        `json:"search_vector"`
}

type MessageAddress struct {
	MessageID   pgtype.UUID        `json:"message_id"`
	AccountID   pgtype.UUID        `json:"account_id"`
	Role        string             `json:"role"`
	Position    int32              `json:"position"`
	DisplayName pgtype.Text        `json:"display_name"`
	Address     string             `json:"address"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
}

type MessageAttachment struct {
	ID                    pgtype.UUID        `json:"id"`
	MessageID             pgtype.UUID        `json:"message_id"`
	AccountID             pgtype.UUID        `json:"account_id"`
	Position              int32              `json:"position"`
	RemoteID              pgtype.Text        `json:"remote_id"`
	Filename              pgtype.Text        `json:"filename"`
	MediaType             string             `json:"media_type"`
	Disposition           string             `json:"disposition"`
	ContentID             pgtype.Text        `json:"content_id"`
	SizeBytes             int64              `json:"size_bytes"`
	CreatedAt             pgtype.Timestamptz `json:"created_at"`
	UpdatedAt             pgtype.Timestamptz `json:"updated_at"`
	CachedObjectID        pgtype.Text        `json:"cached_object_id"`
	CachedObjectNamespace pgtype.Text        `json:"cached_object_namespace"`
}

type MessageLabel struct {
	MessageID pgtype.UUID        `json:"message_id"`
	LabelID   pgtype.UUID        `json:"label_id"`
	AccountID pgtype.UUID        `json:"account_id"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type MessageMailbox struct {
	MessageID pgtype.UUID        `json:"message_id"`
	MailboxID pgtype.UUID        `json:"mailbox_id"`
	AccountID pgtype.UUID        `json:"account_id"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type MetricPoint struct {
	Bucket     pgtype.Timestamptz `json:"bucket"`
	Resolution string             `json:"resolution"`
	Name       string             `json:"name"`
	Kind       string             `json:"kind"`
	Dimensions []byte             `json:"dimensions"`
	Value      float64            `json:"value"`
	Count      int64              `json:"count"`
	MinValue   float64            `json:"min_value"`
	MaxValue   float64            `json:"max_value"`
	Histogram  []int64            `json:"histogram"`
	UpdatedAt  pgtype.Timestamptz `json:"updated_at"`
}

type OutboundDelivery struct {
	ID             pgtype.UUID        `json:"id"`
	AccountID      pgtype.UUID        `json:"account_id"`
	DraftID        pgtype.UUID        `json:"draft_id"`
	IdempotencyKey string             `json:"idempotency_key"`
	PayloadHash    []byte             `json:"payload_hash"`
	Status         string             `json:"status"`
	RemoteID       pgtype.Text        `json:"remote_id"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	UpdatedAt      pgtype.Timestamptz `json:"updated_at"`
}

type PendingAction struct {
	ID                 pgtype.UUID        `json:"id"`
	AccountID          pgtype.UUID        `json:"account_id"`
	IdempotencyKey     string             `json:"idempotency_key"`
	Kind               string             `json:"kind"`
	DesiredState       []byte             `json:"desired_state"`
	Status             string             `json:"status"`
	Attempts           int32              `json:"attempts"`
	AvailableAt        pgtype.Timestamptz `json:"available_at"`
	LastErrorCode      pgtype.Text        `json:"last_error_code"`
	CreatedAt          pgtype.Timestamptz `json:"created_at"`
	TargetKind         string             `json:"target_kind"`
	TargetID           pgtype.UUID        `json:"target_id"`
	AuthoritativeState []byte             `json:"authoritative_state"`
	MaxAttempts        int32              `json:"max_attempts"`
	ClaimToken         pgtype.UUID        `json:"claim_token"`
	ClaimedAt          pgtype.Timestamptz `json:"claimed_at"`
	CompletedAt        pgtype.Timestamptz `json:"completed_at"`
	FailedAt           pgtype.Timestamptz `json:"failed_at"`
	UpdatedAt          pgtype.Timestamptz `json:"updated_at"`
}

type PendingActionAttempt struct {
	ActionID   pgtype.UUID        `json:"action_id"`
	Attempt    int32              `json:"attempt"`
	ClaimToken pgtype.UUID        `json:"claim_token"`
	Status     string             `json:"status"`
	ErrorCode  pgtype.Text        `json:"error_code"`
	StartedAt  pgtype.Timestamptz `json:"started_at"`
	FinishedAt pgtype.Timestamptz `json:"finished_at"`
}

type SentryIssue struct {
	ID          pgtype.UUID        `json:"id"`
	Fingerprint string             `json:"fingerprint"`
	Component   string             `json:"component"`
	Environment string             `json:"environment"`
	Title       string             `json:"title"`
	Status      string             `json:"status"`
	FirstSeenAt pgtype.Timestamptz `json:"first_seen_at"`
	LastSeenAt  pgtype.Timestamptz `json:"last_seen_at"`
	EventCount  int64              `json:"event_count"`
}

type SyncCursor struct {
	AccountID          pgtype.UUID        `json:"account_id"`
	Kind               string             `json:"kind"`
	Cursor             []byte             `json:"cursor"`
	UpdatedAt          pgtype.Timestamptz `json:"updated_at"`
	State              string             `json:"state"`
	Checkpoint         int64              `json:"checkpoint"`
	UidValidity        pgtype.Int8        `json:"uid_validity"`
	Version            int64              `json:"version"`
	LastSuccessAt      pgtype.Timestamptz `json:"last_success_at"`
	InvalidatedAt      pgtype.Timestamptz `json:"invalidated_at"`
	InvalidationReason pgtype.Text        `json:"invalidation_reason"`
}

type SyncRun struct {
	ID              pgtype.UUID        `json:"id"`
	AccountID       pgtype.UUID        `json:"account_id"`
	Phase           string             `json:"phase"`
	State           string             `json:"state"`
	Checkpoint      []byte             `json:"checkpoint"`
	Version         int64              `json:"version"`
	WindowStart     pgtype.Timestamptz `json:"window_start"`
	AppliedCount    int64              `json:"applied_count"`
	CancelRequested bool               `json:"cancel_requested"`
	ScheduledFor    pgtype.Timestamptz `json:"scheduled_for"`
	StartedAt       pgtype.Timestamptz `json:"started_at"`
	LastSuccessAt   pgtype.Timestamptz `json:"last_success_at"`
	CompletedAt     pgtype.Timestamptz `json:"completed_at"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
	UpdatedAt       pgtype.Timestamptz `json:"updated_at"`
}

type Thread struct {
	ID            pgtype.UUID        `json:"id"`
	AccountID     pgtype.UUID        `json:"account_id"`
	RemoteID      string             `json:"remote_id"`
	LastMessageAt pgtype.Timestamptz `json:"last_message_at"`
	IsRead        bool               `json:"is_read"`
	IsStarred     bool               `json:"is_starred"`
	Category      string             `json:"category"`
	IsImportant   bool               `json:"is_important"`
	DeletedAt     pgtype.Timestamptz `json:"deleted_at"`
	MessageCount  int32              `json:"message_count"`
	UnreadCount   int32              `json:"unread_count"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
	UpdatedAt     pgtype.Timestamptz `json:"updated_at"`
	ArchivedAt    pgtype.Timestamptz `json:"archived_at"`
}

type User struct {
	ID            pgtype.UUID        `json:"id"`
	Email         string             `json:"email"`
	Locale        string             `json:"locale"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
	UpdatedAt     pgtype.Timestamptz `json:"updated_at"`
	Name          string             `json:"name"`
	EmailVerified bool               `json:"email_verified"`
	Image         pgtype.Text        `json:"image"`
}
