// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package dbgen

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Account struct {
	ID                   pgtype.UUID        `json:"id"`
	UserID               pgtype.UUID        `json:"user_id"`
	Provider             string             `json:"provider"`
	DisplayName          string             `json:"display_name"`
	EncryptedCredentials []byte             `json:"encrypted_credentials"`
	CredentialNonce      []byte             `json:"credential_nonce"`
	Capabilities         []byte             `json:"capabilities"`
	SyncState            string             `json:"sync_state"`
	CreatedAt            pgtype.Timestamptz `json:"created_at"`
	UpdatedAt            pgtype.Timestamptz `json:"updated_at"`
}

type AuthAccount struct {
	ID                    pgtype.UUID        `json:"id"`
	AccountID             string             `json:"account_id"`
	ProviderID            string             `json:"provider_id"`
	UserID                pgtype.UUID        `json:"user_id"`
	AccessToken           pgtype.Text        `json:"access_token"`
	RefreshToken          pgtype.Text        `json:"refresh_token"`
	IDToken               pgtype.Text        `json:"id_token"`
	AccessTokenExpiresAt  pgtype.Timestamptz `json:"access_token_expires_at"`
	RefreshTokenExpiresAt pgtype.Timestamptz `json:"refresh_token_expires_at"`
	Scope                 pgtype.Text        `json:"scope"`
	Password              pgtype.Text        `json:"password"`
	CreatedAt             pgtype.Timestamptz `json:"created_at"`
	UpdatedAt             pgtype.Timestamptz `json:"updated_at"`
}

type AuthJwk struct {
	ID         pgtype.UUID        `json:"id"`
	PublicKey  string             `json:"public_key"`
	PrivateKey string             `json:"private_key"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
	ExpiresAt  pgtype.Timestamptz `json:"expires_at"`
	Alg        pgtype.Text        `json:"alg"`
	Crv        pgtype.Text        `json:"crv"`
}

type AuthPasskey struct {
	ID           pgtype.UUID        `json:"id"`
	Name         pgtype.Text        `json:"name"`
	PublicKey    string             `json:"public_key"`
	UserID       pgtype.UUID        `json:"user_id"`
	CredentialID string             `json:"credential_id"`
	Counter      int32              `json:"counter"`
	DeviceType   string             `json:"device_type"`
	BackedUp     bool               `json:"backed_up"`
	Transports   pgtype.Text        `json:"transports"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	Aaguid       pgtype.Text        `json:"aaguid"`
}

type AuthSession struct {
	ID        pgtype.UUID        `json:"id"`
	ExpiresAt pgtype.Timestamptz `json:"expires_at"`
	Token     string             `json:"token"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
	IpAddress pgtype.Text        `json:"ip_address"`
	UserAgent pgtype.Text        `json:"user_agent"`
	UserID    pgtype.UUID        `json:"user_id"`
}

type AuthVerification struct {
	ID         pgtype.UUID        `json:"id"`
	Identifier string             `json:"identifier"`
	Value      string             `json:"value"`
	ExpiresAt  pgtype.Timestamptz `json:"expires_at"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
	UpdatedAt  pgtype.Timestamptz `json:"updated_at"`
}

type LogEntry struct {
	ID         int64              `json:"id"`
	OccurredAt pgtype.Timestamptz `json:"occurred_at"`
	Service    string             `json:"service"`
	Module     string             `json:"module"`
	Level      string             `json:"level"`
	Event      string             `json:"event"`
	RequestID  pgtype.Text        `json:"request_id"`
	Attributes []byte             `json:"attributes"`
}

type Mailbox struct {
	ID          pgtype.UUID `json:"id"`
	AccountID   pgtype.UUID `json:"account_id"`
	RemoteID    string      `json:"remote_id"`
	Name        string      `json:"name"`
	Role        pgtype.Text `json:"role"`
	UnreadCount int32       `json:"unread_count"`
}

type Message struct {
	ID                pgtype.UUID        `json:"id"`
	ThreadID          pgtype.UUID        `json:"thread_id"`
	RemoteID          string             `json:"remote_id"`
	MessageID         pgtype.Text        `json:"message_id"`
	ReferencesHeader  []string           `json:"references_header"`
	Sender            []byte             `json:"sender"`
	Recipients        []byte             `json:"recipients"`
	Subject           string             `json:"subject"`
	BodyText          string             `json:"body_text"`
	BodyHtmlSanitized string             `json:"body_html_sanitized"`
	SentAt            pgtype.Timestamptz `json:"sent_at"`
	SearchVector      interface{}        `json:"search_vector"`
}

type MetricPoint struct {
	Bucket     pgtype.Timestamptz `json:"bucket"`
	Resolution string             `json:"resolution"`
	Name       string             `json:"name"`
	Kind       string             `json:"kind"`
	Dimensions []byte             `json:"dimensions"`
	Value      float64            `json:"value"`
	Count      int64              `json:"count"`
}

type PendingAction struct {
	ID             pgtype.UUID        `json:"id"`
	AccountID      pgtype.UUID        `json:"account_id"`
	IdempotencyKey string             `json:"idempotency_key"`
	Action         string             `json:"action"`
	Payload        []byte             `json:"payload"`
	Status         string             `json:"status"`
	Attempts       int32              `json:"attempts"`
	AvailableAt    pgtype.Timestamptz `json:"available_at"`
	LastErrorCode  pgtype.Text        `json:"last_error_code"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
}

type SentryIssue struct {
	ID          pgtype.UUID        `json:"id"`
	Fingerprint string             `json:"fingerprint"`
	Component   string             `json:"component"`
	Environment string             `json:"environment"`
	Title       string             `json:"title"`
	Status      string             `json:"status"`
	FirstSeenAt pgtype.Timestamptz `json:"first_seen_at"`
	LastSeenAt  pgtype.Timestamptz `json:"last_seen_at"`
	EventCount  int64              `json:"event_count"`
}

type SyncCursor struct {
	AccountID pgtype.UUID        `json:"account_id"`
	Kind      string             `json:"kind"`
	Cursor    []byte             `json:"cursor"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}

type Thread struct {
	ID            pgtype.UUID        `json:"id"`
	AccountID     pgtype.UUID        `json:"account_id"`
	RemoteID      string             `json:"remote_id"`
	LastMessageAt pgtype.Timestamptz `json:"last_message_at"`
	IsRead        bool               `json:"is_read"`
	IsStarred     bool               `json:"is_starred"`
	Category      string             `json:"category"`
}

type User struct {
	ID            pgtype.UUID        `json:"id"`
	Email         string             `json:"email"`
	Locale        string             `json:"locale"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
	UpdatedAt     pgtype.Timestamptz `json:"updated_at"`
	Name          string             `json:"name"`
	EmailVerified bool               `json:"email_verified"`
	Image         pgtype.Text        `json:"image"`
}
