// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: search.sql

package dbgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getMessagesByOwnerIDs = `-- name: GetMessagesByOwnerIDs :many
SELECT messages.id, messages.thread_id, messages.remote_id, messages.message_id, messages.references_header, messages.sender, messages.recipients, messages.subject, messages.body_text, messages.body_html_sanitized, messages.sent_at, messages.account_id, messages.is_read, messages.is_starred, messages.is_important, messages.deleted_at, messages.created_at, messages.updated_at, messages.in_reply_to, messages.content_updated_at, messages.search_vector
FROM messages
JOIN accounts ON accounts.id = messages.account_id
WHERE messages.account_id = $1
  AND accounts.user_id = $2
  AND messages.id = ANY($3::uuid[])
`

type GetMessagesByOwnerIDsParams struct {
	AccountID  pgtype.UUID   `json:"account_id"`
	UserID     pgtype.UUID   `json:"user_id"`
	MessageIds []pgtype.UUID `json:"message_ids"`
}

func (q *Queries) GetMessagesByOwnerIDs(ctx context.Context, arg GetMessagesByOwnerIDsParams) ([]Message, error) {
	rows, err := q.db.Query(ctx, getMessagesByOwnerIDs, arg.AccountID, arg.UserID, arg.MessageIds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Message
	for rows.Next() {
		var i Message
		if err := rows.Scan(
			&i.ID,
			&i.ThreadID,
			&i.RemoteID,
			&i.MessageID,
			&i.ReferencesHeader,
			&i.Sender,
			&i.Recipients,
			&i.Subject,
			&i.BodyText,
			&i.BodyHtmlSanitized,
			&i.SentAt,
			&i.AccountID,
			&i.IsRead,
			&i.IsStarred,
			&i.IsImportant,
			&i.DeletedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.InReplyTo,
			&i.ContentUpdatedAt,
			&i.SearchVector,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const searchMessageIDs = `-- name: SearchMessageIDs :many
WITH ranked AS (
  SELECT
    messages.id,
    messages.sent_at,
    CASE
      WHEN $6::text = '' THEN 0::real
      ELSE greatest(
        ts_rank_cd(messages.search_vector, websearch_to_tsquery('simple', $6)),
        similarity(messages.subject, $6) * 0.2
      )::real
    END AS rank
  FROM messages
  JOIN accounts ON accounts.id = messages.account_id
  WHERE messages.account_id = $7
    AND accounts.user_id = $8
    AND (
      $6::text = ''
      OR messages.search_vector @@ websearch_to_tsquery('simple', $6)
      OR messages.subject % $6
    )
    AND ($9::timestamptz IS NULL OR messages.sent_at >= $9)
    AND ($10::timestamptz IS NULL OR messages.sent_at < $10)
    AND (NOT $11::boolean OR NOT messages.is_read)
    AND (NOT $12::boolean OR messages.is_starred)
    AND (
      NOT $13::boolean
      OR EXISTS (
        SELECT 1 FROM message_attachments
        WHERE message_attachments.message_id = messages.id
          AND message_attachments.account_id = messages.account_id
      )
    )
    AND (
      cardinality($14::text[]) = 0
      OR NOT EXISTS (
        SELECT 1 FROM unnest($14::text[]) AS requested(value)
        WHERE NOT EXISTS (
          SELECT 1 FROM message_addresses
          WHERE message_addresses.message_id = messages.id
            AND message_addresses.account_id = messages.account_id
            AND message_addresses.role IN ('from', 'sender')
            AND strpos(lower(message_addresses.address), lower(requested.value)) > 0
        )
      )
    )
    AND (
      cardinality($15::text[]) = 0
      OR NOT EXISTS (
        SELECT 1 FROM unnest($15::text[]) AS requested(value)
        WHERE NOT EXISTS (
          SELECT 1 FROM message_addresses
          WHERE message_addresses.message_id = messages.id
            AND message_addresses.account_id = messages.account_id
            AND message_addresses.role IN ('to', 'cc', 'bcc')
            AND strpos(lower(message_addresses.address), lower(requested.value)) > 0
        )
      )
    )
    AND (
      cardinality($16::text[]) = 0
      OR NOT EXISTS (
        SELECT 1 FROM unnest($16::text[]) AS requested(value)
        WHERE strpos(lower(messages.subject), lower(requested.value)) = 0
      )
    )
    AND (
      cardinality($17::text[]) = 0
      OR NOT EXISTS (
        SELECT 1 FROM unnest($17::text[]) AS requested(value)
        WHERE NOT EXISTS (
          SELECT 1
          FROM message_labels
          JOIN labels ON labels.id = message_labels.label_id AND labels.account_id = message_labels.account_id
          WHERE message_labels.message_id = messages.id
            AND message_labels.account_id = messages.account_id
            AND lower(requested.value) IN (lower(labels.remote_name), lower(coalesce(labels.local_name, '')), lower(coalesce(labels.remote_id, '')))
        )
      )
    )
    AND (
      cardinality($18::text[]) = 0
      OR NOT EXISTS (
        SELECT 1 FROM unnest($18::text[]) AS requested(value)
        WHERE NOT EXISTS (
          SELECT 1
          FROM message_mailboxes
          JOIN mailboxes ON mailboxes.id = message_mailboxes.mailbox_id AND mailboxes.account_id = message_mailboxes.account_id
          WHERE message_mailboxes.message_id = messages.id
            AND message_mailboxes.account_id = messages.account_id
            AND lower(requested.value) IN (lower(mailboxes.remote_id), lower(mailboxes.remote_name), lower(coalesce(mailboxes.local_name, '')), lower(coalesce(mailboxes.role, '')))
        )
      )
    )
)
SELECT id, sent_at, rank
FROM ranked
WHERE NOT $1::boolean
  OR rank < $2::real
  OR (rank = $2::real AND sent_at < $3::timestamptz)
  OR (rank = $2::real AND sent_at = $3::timestamptz AND id < $4::uuid)
ORDER BY rank DESC, sent_at DESC, id DESC
LIMIT $5
`

type SearchMessageIDsParams struct {
	HasCursor         bool               `json:"has_cursor"`
	CursorRank        float32            `json:"cursor_rank"`
	CursorSentAt      pgtype.Timestamptz `json:"cursor_sent_at"`
	CursorID          pgtype.UUID        `json:"cursor_id"`
	PageLimit         int32              `json:"page_limit"`
	SearchText        string             `json:"search_text"`
	AccountID         pgtype.UUID        `json:"account_id"`
	UserID            pgtype.UUID        `json:"user_id"`
	AfterTime         pgtype.Timestamptz `json:"after_time"`
	BeforeTime        pgtype.Timestamptz `json:"before_time"`
	RequireUnread     bool               `json:"require_unread"`
	RequireStarred    bool               `json:"require_starred"`
	RequireAttachment bool               `json:"require_attachment"`
	FromValues        []string           `json:"from_values"`
	ToValues          []string           `json:"to_values"`
	SubjectValues     []string           `json:"subject_values"`
	LabelValues       []string           `json:"label_values"`
	MailboxValues     []string           `json:"mailbox_values"`
}

type SearchMessageIDsRow struct {
	ID     pgtype.UUID        `json:"id"`
	SentAt pgtype.Timestamptz `json:"sent_at"`
	Rank   float32            `json:"rank"`
}

func (q *Queries) SearchMessageIDs(ctx context.Context, arg SearchMessageIDsParams) ([]SearchMessageIDsRow, error) {
	rows, err := q.db.Query(ctx, searchMessageIDs,
		arg.HasCursor,
		arg.CursorRank,
		arg.CursorSentAt,
		arg.CursorID,
		arg.PageLimit,
		arg.SearchText,
		arg.AccountID,
		arg.UserID,
		arg.AfterTime,
		arg.BeforeTime,
		arg.RequireUnread,
		arg.RequireStarred,
		arg.RequireAttachment,
		arg.FromValues,
		arg.ToValues,
		arg.SubjectValues,
		arg.LabelValues,
		arg.MailboxValues,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SearchMessageIDsRow
	for rows.Next() {
		var i SearchMessageIDsRow
		if err := rows.Scan(&i.ID, &i.SentAt, &i.Rank); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
