// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: sentry.sql

package dbgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const deleteExpiredSentryEvents = `-- name: DeleteExpiredSentryEvents :execrows
DELETE FROM sentry_events WHERE received_at < $1
`

func (q *Queries) DeleteExpiredSentryEvents(ctx context.Context, expiredBefore pgtype.Timestamptz) (int64, error) {
	result, err := q.db.Exec(ctx, deleteExpiredSentryEvents, expiredBefore)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteSentryCDNObject = `-- name: DeleteSentryCDNObject :exec
DELETE FROM cdn_objects
WHERE object_id = $1 AND namespace = 'sentry'
`

func (q *Queries) DeleteSentryCDNObject(ctx context.Context, objectID string) error {
	_, err := q.db.Exec(ctx, deleteSentryCDNObject, objectID)
	return err
}

const getSentryProjectByArtifactToken = `-- name: GetSentryProjectByArtifactToken :one
SELECT component, enabled FROM sentry_projects
WHERE artifact_token_hash = $1 AND enabled = true
`

type GetSentryProjectByArtifactTokenRow struct {
	Component string `json:"component"`
	Enabled   bool   `json:"enabled"`
}

func (q *Queries) GetSentryProjectByArtifactToken(ctx context.Context, artifactTokenHash pgtype.Text) (GetSentryProjectByArtifactTokenRow, error) {
	row := q.db.QueryRow(ctx, getSentryProjectByArtifactToken, artifactTokenHash)
	var i GetSentryProjectByArtifactTokenRow
	err := row.Scan(&i.Component, &i.Enabled)
	return i, err
}

const getSentryProjectByKey = `-- name: GetSentryProjectByKey :one
SELECT component, public_key, enabled FROM sentry_projects
WHERE public_key = $1 AND enabled = true
`

type GetSentryProjectByKeyRow struct {
	Component string `json:"component"`
	PublicKey string `json:"public_key"`
	Enabled   bool   `json:"enabled"`
}

func (q *Queries) GetSentryProjectByKey(ctx context.Context, publicKey string) (GetSentryProjectByKeyRow, error) {
	row := q.db.QueryRow(ctx, getSentryProjectByKey, publicKey)
	var i GetSentryProjectByKeyRow
	err := row.Scan(&i.Component, &i.PublicKey, &i.Enabled)
	return i, err
}

const insertSentryCDNObject = `-- name: InsertSentryCDNObject :exec
INSERT INTO cdn_objects (
  object_id, namespace, media_type, size_bytes, etag, storage_status,
  stored_at, updated_at
) VALUES (
  $1, 'sentry', $2, $3,
  $4, 'cached', $5, $5
)
`

type InsertSentryCDNObjectParams struct {
	ObjectID  string             `json:"object_id"`
	MediaType string             `json:"media_type"`
	SizeBytes int64              `json:"size_bytes"`
	Etag      string             `json:"etag"`
	StoredAt  pgtype.Timestamptz `json:"stored_at"`
}

func (q *Queries) InsertSentryCDNObject(ctx context.Context, arg InsertSentryCDNObjectParams) error {
	_, err := q.db.Exec(ctx, insertSentryCDNObject,
		arg.ObjectID,
		arg.MediaType,
		arg.SizeBytes,
		arg.Etag,
		arg.StoredAt,
	)
	return err
}

const insertSentryEvent = `-- name: InsertSentryEvent :one
INSERT INTO sentry_events (
  event_id, component, event_type, environment, release, level, sdk_name,
  received_bytes, item_count, received_at
) VALUES (
  $1, $2, $3,
  $4, $5, $6,
  $7, $8, $9,
  $10
)
ON CONFLICT (component, event_id) DO NOTHING
RETURNING id
`

type InsertSentryEventParams struct {
	EventID       string             `json:"event_id"`
	Component     string             `json:"component"`
	EventType     string             `json:"event_type"`
	Environment   pgtype.Text        `json:"environment"`
	Release       pgtype.Text        `json:"release"`
	Level         pgtype.Text        `json:"level"`
	SdkName       pgtype.Text        `json:"sdk_name"`
	ReceivedBytes int64              `json:"received_bytes"`
	ItemCount     int64              `json:"item_count"`
	ReceivedAt    pgtype.Timestamptz `json:"received_at"`
}

func (q *Queries) InsertSentryEvent(ctx context.Context, arg InsertSentryEventParams) (int64, error) {
	row := q.db.QueryRow(ctx, insertSentryEvent,
		arg.EventID,
		arg.Component,
		arg.EventType,
		arg.Environment,
		arg.Release,
		arg.Level,
		arg.SdkName,
		arg.ReceivedBytes,
		arg.ItemCount,
		arg.ReceivedAt,
	)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const insertSentryEventItem = `-- name: InsertSentryEventItem :exec
INSERT INTO sentry_event_items (
  event_id, item_type, content_type, received_bytes, payload_sha256,
  summary, payload_object_id, discarded
) VALUES (
  $1, $2, $3,
  $4, $5, $6,
  $7, $8
)
`

type InsertSentryEventItemParams struct {
	EventID         int64       `json:"event_id"`
	ItemType        string      `json:"item_type"`
	ContentType     pgtype.Text `json:"content_type"`
	ReceivedBytes   int64       `json:"received_bytes"`
	PayloadSha256   string      `json:"payload_sha256"`
	Summary         []byte      `json:"summary"`
	PayloadObjectID pgtype.Text `json:"payload_object_id"`
	Discarded       bool        `json:"discarded"`
}

func (q *Queries) InsertSentryEventItem(ctx context.Context, arg InsertSentryEventItemParams) error {
	_, err := q.db.Exec(ctx, insertSentryEventItem,
		arg.EventID,
		arg.ItemType,
		arg.ContentType,
		arg.ReceivedBytes,
		arg.PayloadSha256,
		arg.Summary,
		arg.PayloadObjectID,
		arg.Discarded,
	)
	return err
}

const listExpiredSentryObjects = `-- name: ListExpiredSentryObjects :many
SELECT DISTINCT sentry_event_items.payload_object_id
FROM sentry_event_items
JOIN sentry_events ON sentry_events.id = sentry_event_items.event_id
WHERE sentry_events.received_at < $1
  AND sentry_event_items.payload_object_id IS NOT NULL
`

func (q *Queries) ListExpiredSentryObjects(ctx context.Context, expiredBefore pgtype.Timestamptz) ([]pgtype.Text, error) {
	rows, err := q.db.Query(ctx, listExpiredSentryObjects, expiredBefore)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []pgtype.Text
	for rows.Next() {
		var payload_object_id pgtype.Text
		if err := rows.Scan(&payload_object_id); err != nil {
			return nil, err
		}
		items = append(items, payload_object_id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const sentryStoredBytes = `-- name: SentryStoredBytes :one
SELECT COALESCE(SUM(received_bytes), 0)::bigint FROM sentry_events
`

func (q *Queries) SentryStoredBytes(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, sentryStoredBytes)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const upsertSentryProject = `-- name: UpsertSentryProject :exec
INSERT INTO sentry_projects (component, public_key, artifact_token_hash, updated_at)
VALUES ($1, $2, $3, $4)
ON CONFLICT (component) DO UPDATE SET
  public_key = EXCLUDED.public_key,
  artifact_token_hash = EXCLUDED.artifact_token_hash,
  enabled = true,
  updated_at = EXCLUDED.updated_at
`

type UpsertSentryProjectParams struct {
	Component         string             `json:"component"`
	PublicKey         string             `json:"public_key"`
	ArtifactTokenHash pgtype.Text        `json:"artifact_token_hash"`
	UpdatedAt         pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) UpsertSentryProject(ctx context.Context, arg UpsertSentryProjectParams) error {
	_, err := q.db.Exec(ctx, upsertSentryProject,
		arg.Component,
		arg.PublicKey,
		arg.ArtifactTokenHash,
		arg.UpdatedAt,
	)
	return err
}
