// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: sentry_telemetry.sql

package dbgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const deleteExpiredSentryProfiles = `-- name: DeleteExpiredSentryProfiles :execrows
DELETE FROM sentry_profiles WHERE received_at < $1
`

func (q *Queries) DeleteExpiredSentryProfiles(ctx context.Context, expiredBefore pgtype.Timestamptz) (int64, error) {
	result, err := q.db.Exec(ctx, deleteExpiredSentryProfiles, expiredBefore)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteExpiredSentryReplaySegments = `-- name: DeleteExpiredSentryReplaySegments :execrows
DELETE FROM sentry_replay_segments WHERE received_at < $1
`

func (q *Queries) DeleteExpiredSentryReplaySegments(ctx context.Context, expiredBefore pgtype.Timestamptz) (int64, error) {
	result, err := q.db.Exec(ctx, deleteExpiredSentryReplaySegments, expiredBefore)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteExpiredSentryReplays = `-- name: DeleteExpiredSentryReplays :execrows
DELETE FROM sentry_replays WHERE last_seen_at < $1
`

func (q *Queries) DeleteExpiredSentryReplays(ctx context.Context, expiredBefore pgtype.Timestamptz) (int64, error) {
	result, err := q.db.Exec(ctx, deleteExpiredSentryReplays, expiredBefore)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteExpiredSentryTraces = `-- name: DeleteExpiredSentryTraces :execrows
DELETE FROM sentry_traces WHERE received_at < $1
`

func (q *Queries) DeleteExpiredSentryTraces(ctx context.Context, expiredBefore pgtype.Timestamptz) (int64, error) {
	result, err := q.db.Exec(ctx, deleteExpiredSentryTraces, expiredBefore)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const incrementSentryReplaySegments = `-- name: IncrementSentryReplaySegments :exec
UPDATE sentry_replays SET segment_count = segment_count + 1 WHERE id = $1
`

func (q *Queries) IncrementSentryReplaySegments(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, incrementSentryReplaySegments, id)
	return err
}

const insertSentryProfile = `-- name: InsertSentryProfile :exec
INSERT INTO sentry_profiles (event_id, component, platform, sample_count, frame_count, received_at)
VALUES ($1, $2, $3, $4, $5, $6)
ON CONFLICT (event_id) DO NOTHING
`

type InsertSentryProfileParams struct {
	EventID     int64              `json:"event_id"`
	Component   string             `json:"component"`
	Platform    pgtype.Text        `json:"platform"`
	SampleCount int32              `json:"sample_count"`
	FrameCount  int32              `json:"frame_count"`
	ReceivedAt  pgtype.Timestamptz `json:"received_at"`
}

func (q *Queries) InsertSentryProfile(ctx context.Context, arg InsertSentryProfileParams) error {
	_, err := q.db.Exec(ctx, insertSentryProfile,
		arg.EventID,
		arg.Component,
		arg.Platform,
		arg.SampleCount,
		arg.FrameCount,
		arg.ReceivedAt,
	)
	return err
}

const insertSentryReplaySegment = `-- name: InsertSentryReplaySegment :execrows
INSERT INTO sentry_replay_segments (
  replay_row_id, event_id, sequence, object_id, size_bytes, checksum_sha256, received_at
) VALUES (
  $1, $2, $3, $4,
  $5, $6, $7
)
ON CONFLICT (replay_row_id, sequence) DO NOTHING
`

type InsertSentryReplaySegmentParams struct {
	ReplayRowID    int64              `json:"replay_row_id"`
	EventID        int64              `json:"event_id"`
	Sequence       int32              `json:"sequence"`
	ObjectID       string             `json:"object_id"`
	SizeBytes      int64              `json:"size_bytes"`
	ChecksumSha256 string             `json:"checksum_sha256"`
	ReceivedAt     pgtype.Timestamptz `json:"received_at"`
}

func (q *Queries) InsertSentryReplaySegment(ctx context.Context, arg InsertSentryReplaySegmentParams) (int64, error) {
	result, err := q.db.Exec(ctx, insertSentryReplaySegment,
		arg.ReplayRowID,
		arg.EventID,
		arg.Sequence,
		arg.ObjectID,
		arg.SizeBytes,
		arg.ChecksumSha256,
		arg.ReceivedAt,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const insertSentrySpan = `-- name: InsertSentrySpan :exec
INSERT INTO sentry_spans (
  trace_row_id, trace_id, span_id, parent_span_id, operation, status, started_at, duration_ms
) VALUES (
  $1, $2, $3, $4,
  $5, $6, $7, $8
)
ON CONFLICT (trace_row_id, span_id) DO NOTHING
`

type InsertSentrySpanParams struct {
	TraceRowID   int64              `json:"trace_row_id"`
	TraceID      string             `json:"trace_id"`
	SpanID       string             `json:"span_id"`
	ParentSpanID pgtype.Text        `json:"parent_span_id"`
	Operation    pgtype.Text        `json:"operation"`
	Status       pgtype.Text        `json:"status"`
	StartedAt    pgtype.Timestamptz `json:"started_at"`
	DurationMs   pgtype.Float8      `json:"duration_ms"`
}

func (q *Queries) InsertSentrySpan(ctx context.Context, arg InsertSentrySpanParams) error {
	_, err := q.db.Exec(ctx, insertSentrySpan,
		arg.TraceRowID,
		arg.TraceID,
		arg.SpanID,
		arg.ParentSpanID,
		arg.Operation,
		arg.Status,
		arg.StartedAt,
		arg.DurationMs,
	)
	return err
}

const insertSentryTrace = `-- name: InsertSentryTrace :one
INSERT INTO sentry_traces (
  event_id, component, trace_id, span_id, parent_span_id, operation, status,
  started_at, duration_ms, span_count, received_at
) VALUES (
  $1, $2, $3, $4,
  $5, $6, $7,
  $8, $9, $10, $11
)
RETURNING id
`

type InsertSentryTraceParams struct {
	EventID      int64              `json:"event_id"`
	Component    string             `json:"component"`
	TraceID      string             `json:"trace_id"`
	SpanID       string             `json:"span_id"`
	ParentSpanID pgtype.Text        `json:"parent_span_id"`
	Operation    pgtype.Text        `json:"operation"`
	Status       pgtype.Text        `json:"status"`
	StartedAt    pgtype.Timestamptz `json:"started_at"`
	DurationMs   pgtype.Float8      `json:"duration_ms"`
	SpanCount    int32              `json:"span_count"`
	ReceivedAt   pgtype.Timestamptz `json:"received_at"`
}

func (q *Queries) InsertSentryTrace(ctx context.Context, arg InsertSentryTraceParams) (int64, error) {
	row := q.db.QueryRow(ctx, insertSentryTrace,
		arg.EventID,
		arg.Component,
		arg.TraceID,
		arg.SpanID,
		arg.ParentSpanID,
		arg.Operation,
		arg.Status,
		arg.StartedAt,
		arg.DurationMs,
		arg.SpanCount,
		arg.ReceivedAt,
	)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const listExpiredSentryReplayObjects = `-- name: ListExpiredSentryReplayObjects :many
SELECT object_id FROM sentry_replay_segments WHERE received_at < $1
`

func (q *Queries) ListExpiredSentryReplayObjects(ctx context.Context, expiredBefore pgtype.Timestamptz) ([]string, error) {
	rows, err := q.db.Query(ctx, listExpiredSentryReplayObjects, expiredBefore)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var object_id string
		if err := rows.Scan(&object_id); err != nil {
			return nil, err
		}
		items = append(items, object_id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const refreshSentryReplaySegmentCounts = `-- name: RefreshSentryReplaySegmentCounts :exec
UPDATE sentry_replays
SET segment_count = (
  SELECT count(*)::integer
  FROM sentry_replay_segments
  WHERE sentry_replay_segments.replay_row_id = sentry_replays.id
)
`

func (q *Queries) RefreshSentryReplaySegmentCounts(ctx context.Context) error {
	_, err := q.db.Exec(ctx, refreshSentryReplaySegmentCounts)
	return err
}

const sentryReplayStoredBytes = `-- name: SentryReplayStoredBytes :one
SELECT COALESCE(SUM(size_bytes), 0)::bigint FROM sentry_replay_segments
`

func (q *Queries) SentryReplayStoredBytes(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, sentryReplayStoredBytes)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const sentryTelemetrySummary = `-- name: SentryTelemetrySummary :one
SELECT
  (SELECT count(*) FROM sentry_traces WHERE sentry_traces.received_at >= $1)::bigint AS traces,
  (SELECT count(*) FROM sentry_spans JOIN sentry_traces ON sentry_traces.id=sentry_spans.trace_row_id WHERE sentry_traces.received_at >= $1)::bigint AS spans,
  (SELECT count(*) FROM sentry_profiles WHERE sentry_profiles.received_at >= $1)::bigint AS profiles,
  (SELECT count(*) FROM sentry_replays WHERE sentry_replays.last_seen_at >= $1)::bigint AS replays,
  (SELECT count(*) FROM sentry_replay_segments WHERE sentry_replay_segments.received_at >= $1)::bigint AS replay_segments
`

type SentryTelemetrySummaryRow struct {
	Traces         int64 `json:"traces"`
	Spans          int64 `json:"spans"`
	Profiles       int64 `json:"profiles"`
	Replays        int64 `json:"replays"`
	ReplaySegments int64 `json:"replay_segments"`
}

func (q *Queries) SentryTelemetrySummary(ctx context.Context, since pgtype.Timestamptz) (SentryTelemetrySummaryRow, error) {
	row := q.db.QueryRow(ctx, sentryTelemetrySummary, since)
	var i SentryTelemetrySummaryRow
	err := row.Scan(
		&i.Traces,
		&i.Spans,
		&i.Profiles,
		&i.Replays,
		&i.ReplaySegments,
	)
	return i, err
}

const upsertSentryReplay = `-- name: UpsertSentryReplay :one
INSERT INTO sentry_replays (component, replay_id, environment, first_seen_at, last_seen_at)
VALUES ($1, $2, $3, $4, $4)
ON CONFLICT (component, replay_id) DO UPDATE SET
  last_seen_at = GREATEST(sentry_replays.last_seen_at, EXCLUDED.last_seen_at)
RETURNING id
`

type UpsertSentryReplayParams struct {
	Component   string             `json:"component"`
	ReplayID    string             `json:"replay_id"`
	Environment string             `json:"environment"`
	SeenAt      pgtype.Timestamptz `json:"seen_at"`
}

func (q *Queries) UpsertSentryReplay(ctx context.Context, arg UpsertSentryReplayParams) (int64, error) {
	row := q.db.QueryRow(ctx, upsertSentryReplay,
		arg.Component,
		arg.ReplayID,
		arg.Environment,
		arg.SeenAt,
	)
	var id int64
	err := row.Scan(&id)
	return id, err
}
