// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: sentry_issues.sql

package dbgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const attachSentryEventIssue = `-- name: AttachSentryEventIssue :exec
UPDATE sentry_events SET
  issue_id = $1,
  grouping_key = $2,
  normalized_stack = $3,
  symbolication_status = $4
WHERE id = $5
`

type AttachSentryEventIssueParams struct {
	IssueID             pgtype.UUID `json:"issue_id"`
	GroupingKey         pgtype.Text `json:"grouping_key"`
	NormalizedStack     []byte      `json:"normalized_stack"`
	SymbolicationStatus string      `json:"symbolication_status"`
	EventRowID          int64       `json:"event_row_id"`
}

func (q *Queries) AttachSentryEventIssue(ctx context.Context, arg AttachSentryEventIssueParams) error {
	_, err := q.db.Exec(ctx, attachSentryEventIssue,
		arg.IssueID,
		arg.GroupingKey,
		arg.NormalizedStack,
		arg.SymbolicationStatus,
		arg.EventRowID,
	)
	return err
}

const deleteExpiredSentryArtifacts = `-- name: DeleteExpiredSentryArtifacts :execrows
DELETE FROM sentry_release_artifacts
WHERE created_at < $1
`

func (q *Queries) DeleteExpiredSentryArtifacts(ctx context.Context, expiredBefore pgtype.Timestamptz) (int64, error) {
	result, err := q.db.Exec(ctx, deleteExpiredSentryArtifacts, expiredBefore)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteSentryArtifact = `-- name: DeleteSentryArtifact :exec
DELETE FROM sentry_release_artifacts WHERE id = $1
`

func (q *Queries) DeleteSentryArtifact(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, deleteSentryArtifact, id)
	return err
}

const existingSentryEvent = `-- name: ExistingSentryEvent :one
SELECT id FROM sentry_events
WHERE component = $1 AND event_id = $2
`

type ExistingSentryEventParams struct {
	Component string `json:"component"`
	EventID   string `json:"event_id"`
}

func (q *Queries) ExistingSentryEvent(ctx context.Context, arg ExistingSentryEventParams) (int64, error) {
	row := q.db.QueryRow(ctx, existingSentryEvent, arg.Component, arg.EventID)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const getSentryArtifact = `-- name: GetSentryArtifact :one
SELECT sentry_release_artifacts.id, sentry_release_artifacts.release_id, sentry_release_artifacts.object_id, sentry_release_artifacts.object_namespace, sentry_release_artifacts.name, sentry_release_artifacts.kind, sentry_release_artifacts.checksum_sha256, sentry_release_artifacts.size_bytes, sentry_release_artifacts.status, sentry_release_artifacts.attempts, sentry_release_artifacts.error_code, sentry_release_artifacts.created_at, sentry_release_artifacts.processed_at, sentry_releases.component, sentry_releases.version
FROM sentry_release_artifacts
JOIN sentry_releases ON sentry_releases.id = sentry_release_artifacts.release_id
WHERE sentry_release_artifacts.id = $1
`

type GetSentryArtifactRow struct {
	ID              int64              `json:"id"`
	ReleaseID       int64              `json:"release_id"`
	ObjectID        string             `json:"object_id"`
	ObjectNamespace pgtype.Text        `json:"object_namespace"`
	Name            string             `json:"name"`
	Kind            string             `json:"kind"`
	ChecksumSha256  string             `json:"checksum_sha256"`
	SizeBytes       int64              `json:"size_bytes"`
	Status          string             `json:"status"`
	Attempts        int32              `json:"attempts"`
	ErrorCode       pgtype.Text        `json:"error_code"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
	ProcessedAt     pgtype.Timestamptz `json:"processed_at"`
	Component       string             `json:"component"`
	Version         string             `json:"version"`
}

func (q *Queries) GetSentryArtifact(ctx context.Context, id int64) (GetSentryArtifactRow, error) {
	row := q.db.QueryRow(ctx, getSentryArtifact, id)
	var i GetSentryArtifactRow
	err := row.Scan(
		&i.ID,
		&i.ReleaseID,
		&i.ObjectID,
		&i.ObjectNamespace,
		&i.Name,
		&i.Kind,
		&i.ChecksumSha256,
		&i.SizeBytes,
		&i.Status,
		&i.Attempts,
		&i.ErrorCode,
		&i.CreatedAt,
		&i.ProcessedAt,
		&i.Component,
		&i.Version,
	)
	return i, err
}

const getSentryArtifactByName = `-- name: GetSentryArtifactByName :one
SELECT sentry_release_artifacts.id, sentry_release_artifacts.release_id, sentry_release_artifacts.object_id, sentry_release_artifacts.object_namespace, sentry_release_artifacts.name, sentry_release_artifacts.kind, sentry_release_artifacts.checksum_sha256, sentry_release_artifacts.size_bytes, sentry_release_artifacts.status, sentry_release_artifacts.attempts, sentry_release_artifacts.error_code, sentry_release_artifacts.created_at, sentry_release_artifacts.processed_at, sentry_releases.component, sentry_releases.version
FROM sentry_release_artifacts
JOIN sentry_releases ON sentry_releases.id = sentry_release_artifacts.release_id
WHERE sentry_release_artifacts.release_id = $1
  AND sentry_release_artifacts.name = $2
`

type GetSentryArtifactByNameParams struct {
	ReleaseID int64  `json:"release_id"`
	Name      string `json:"name"`
}

type GetSentryArtifactByNameRow struct {
	ID              int64              `json:"id"`
	ReleaseID       int64              `json:"release_id"`
	ObjectID        string             `json:"object_id"`
	ObjectNamespace pgtype.Text        `json:"object_namespace"`
	Name            string             `json:"name"`
	Kind            string             `json:"kind"`
	ChecksumSha256  string             `json:"checksum_sha256"`
	SizeBytes       int64              `json:"size_bytes"`
	Status          string             `json:"status"`
	Attempts        int32              `json:"attempts"`
	ErrorCode       pgtype.Text        `json:"error_code"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
	ProcessedAt     pgtype.Timestamptz `json:"processed_at"`
	Component       string             `json:"component"`
	Version         string             `json:"version"`
}

func (q *Queries) GetSentryArtifactByName(ctx context.Context, arg GetSentryArtifactByNameParams) (GetSentryArtifactByNameRow, error) {
	row := q.db.QueryRow(ctx, getSentryArtifactByName, arg.ReleaseID, arg.Name)
	var i GetSentryArtifactByNameRow
	err := row.Scan(
		&i.ID,
		&i.ReleaseID,
		&i.ObjectID,
		&i.ObjectNamespace,
		&i.Name,
		&i.Kind,
		&i.ChecksumSha256,
		&i.SizeBytes,
		&i.Status,
		&i.Attempts,
		&i.ErrorCode,
		&i.CreatedAt,
		&i.ProcessedAt,
		&i.Component,
		&i.Version,
	)
	return i, err
}

const getSentryRelease = `-- name: GetSentryRelease :one
SELECT id, component, version, status, created_at, finalized_at FROM sentry_releases
WHERE component = $1 AND version = $2
`

type GetSentryReleaseParams struct {
	Component string `json:"component"`
	Version   string `json:"version"`
}

func (q *Queries) GetSentryRelease(ctx context.Context, arg GetSentryReleaseParams) (SentryRelease, error) {
	row := q.db.QueryRow(ctx, getSentryRelease, arg.Component, arg.Version)
	var i SentryRelease
	err := row.Scan(
		&i.ID,
		&i.Component,
		&i.Version,
		&i.Status,
		&i.CreatedAt,
		&i.FinalizedAt,
	)
	return i, err
}

const insertSentryArtifact = `-- name: InsertSentryArtifact :one
INSERT INTO sentry_release_artifacts (
  release_id, object_id, name, kind, checksum_sha256, size_bytes, created_at
) VALUES (
  $1, $2, $3, $4,
  $5, $6, $7
)
ON CONFLICT (release_id, name) DO NOTHING
RETURNING id, release_id, object_id, object_namespace, name, kind, checksum_sha256, size_bytes, status, attempts, error_code, created_at, processed_at
`

type InsertSentryArtifactParams struct {
	ReleaseID      int64              `json:"release_id"`
	ObjectID       string             `json:"object_id"`
	Name           string             `json:"name"`
	Kind           string             `json:"kind"`
	ChecksumSha256 string             `json:"checksum_sha256"`
	SizeBytes      int64              `json:"size_bytes"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
}

func (q *Queries) InsertSentryArtifact(ctx context.Context, arg InsertSentryArtifactParams) (SentryReleaseArtifact, error) {
	row := q.db.QueryRow(ctx, insertSentryArtifact,
		arg.ReleaseID,
		arg.ObjectID,
		arg.Name,
		arg.Kind,
		arg.ChecksumSha256,
		arg.SizeBytes,
		arg.CreatedAt,
	)
	var i SentryReleaseArtifact
	err := row.Scan(
		&i.ID,
		&i.ReleaseID,
		&i.ObjectID,
		&i.ObjectNamespace,
		&i.Name,
		&i.Kind,
		&i.ChecksumSha256,
		&i.SizeBytes,
		&i.Status,
		&i.Attempts,
		&i.ErrorCode,
		&i.CreatedAt,
		&i.ProcessedAt,
	)
	return i, err
}

const listExpiredSentryArtifacts = `-- name: ListExpiredSentryArtifacts :many
SELECT object_id FROM sentry_release_artifacts
WHERE created_at < $1
ORDER BY id
LIMIT 10000
`

func (q *Queries) ListExpiredSentryArtifacts(ctx context.Context, expiredBefore pgtype.Timestamptz) ([]string, error) {
	rows, err := q.db.Query(ctx, listExpiredSentryArtifacts, expiredBefore)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var object_id string
		if err := rows.Scan(&object_id); err != nil {
			return nil, err
		}
		items = append(items, object_id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPendingSentryEventsForRelease = `-- name: ListPendingSentryEventsForRelease :many
SELECT id, normalized_stack FROM sentry_events
WHERE component = $1 AND release = $2
  AND symbolication_status IN ('pending', 'failed')
ORDER BY id
LIMIT 10000
`

type ListPendingSentryEventsForReleaseParams struct {
	Component string      `json:"component"`
	Version   pgtype.Text `json:"version"`
}

type ListPendingSentryEventsForReleaseRow struct {
	ID              int64  `json:"id"`
	NormalizedStack []byte `json:"normalized_stack"`
}

func (q *Queries) ListPendingSentryEventsForRelease(ctx context.Context, arg ListPendingSentryEventsForReleaseParams) ([]ListPendingSentryEventsForReleaseRow, error) {
	rows, err := q.db.Query(ctx, listPendingSentryEventsForRelease, arg.Component, arg.Version)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListPendingSentryEventsForReleaseRow
	for rows.Next() {
		var i ListPendingSentryEventsForReleaseRow
		if err := rows.Scan(&i.ID, &i.NormalizedStack); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSentryIssues = `-- name: ListSentryIssues :many
SELECT id, fingerprint, component, environment, title, status, first_seen_at, last_seen_at, event_count FROM sentry_issues
WHERE ($1::text = '' OR status = $1)
ORDER BY last_seen_at DESC, id DESC
LIMIT $2::bigint
`

type ListSentryIssuesParams struct {
	Status     string `json:"status"`
	QueryLimit int64  `json:"query_limit"`
}

func (q *Queries) ListSentryIssues(ctx context.Context, arg ListSentryIssuesParams) ([]SentryIssue, error) {
	rows, err := q.db.Query(ctx, listSentryIssues, arg.Status, arg.QueryLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SentryIssue
	for rows.Next() {
		var i SentryIssue
		if err := rows.Scan(
			&i.ID,
			&i.Fingerprint,
			&i.Component,
			&i.Environment,
			&i.Title,
			&i.Status,
			&i.FirstSeenAt,
			&i.LastSeenAt,
			&i.EventCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markSentryArtifactFailed = `-- name: MarkSentryArtifactFailed :exec
UPDATE sentry_release_artifacts SET
  status = 'failed', attempts = LEAST(attempts + 1, 20),
  error_code = $1, processed_at = NULL
WHERE id = $2
`

type MarkSentryArtifactFailedParams struct {
	ErrorCode pgtype.Text `json:"error_code"`
	ID        int64       `json:"id"`
}

func (q *Queries) MarkSentryArtifactFailed(ctx context.Context, arg MarkSentryArtifactFailedParams) error {
	_, err := q.db.Exec(ctx, markSentryArtifactFailed, arg.ErrorCode, arg.ID)
	return err
}

const markSentryArtifactProcessed = `-- name: MarkSentryArtifactProcessed :exec
UPDATE sentry_release_artifacts SET
  status = 'processed', attempts = attempts + 1, error_code = NULL,
  processed_at = $1
WHERE id = $2
`

type MarkSentryArtifactProcessedParams struct {
	ProcessedAt pgtype.Timestamptz `json:"processed_at"`
	ID          int64              `json:"id"`
}

func (q *Queries) MarkSentryArtifactProcessed(ctx context.Context, arg MarkSentryArtifactProcessedParams) error {
	_, err := q.db.Exec(ctx, markSentryArtifactProcessed, arg.ProcessedAt, arg.ID)
	return err
}

const sentryArtifactStoredBytes = `-- name: SentryArtifactStoredBytes :one
SELECT COALESCE(SUM(size_bytes), 0)::bigint FROM sentry_release_artifacts
`

func (q *Queries) SentryArtifactStoredBytes(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, sentryArtifactStoredBytes)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const setSentryIssueStatus = `-- name: SetSentryIssueStatus :one
UPDATE sentry_issues SET status = $1
WHERE id = $2
RETURNING id, fingerprint, component, environment, title, status, first_seen_at, last_seen_at, event_count
`

type SetSentryIssueStatusParams struct {
	Status string      `json:"status"`
	ID     pgtype.UUID `json:"id"`
}

func (q *Queries) SetSentryIssueStatus(ctx context.Context, arg SetSentryIssueStatusParams) (SentryIssue, error) {
	row := q.db.QueryRow(ctx, setSentryIssueStatus, arg.Status, arg.ID)
	var i SentryIssue
	err := row.Scan(
		&i.ID,
		&i.Fingerprint,
		&i.Component,
		&i.Environment,
		&i.Title,
		&i.Status,
		&i.FirstSeenAt,
		&i.LastSeenAt,
		&i.EventCount,
	)
	return i, err
}

const updateSentryEventSymbolication = `-- name: UpdateSentryEventSymbolication :exec
UPDATE sentry_events SET normalized_stack = $1, symbolication_status = 'resolved'
WHERE id = $2
`

type UpdateSentryEventSymbolicationParams struct {
	NormalizedStack []byte `json:"normalized_stack"`
	ID              int64  `json:"id"`
}

func (q *Queries) UpdateSentryEventSymbolication(ctx context.Context, arg UpdateSentryEventSymbolicationParams) error {
	_, err := q.db.Exec(ctx, updateSentryEventSymbolication, arg.NormalizedStack, arg.ID)
	return err
}

const upsertSentryIssue = `-- name: UpsertSentryIssue :one
INSERT INTO sentry_issues (
  id, fingerprint, component, environment, title, status,
  first_seen_at, last_seen_at, event_count
) VALUES (
  $1, $2, $3,
  $4, $5, 'unresolved',
  $6, $6, 1
)
ON CONFLICT (fingerprint, component, environment) DO UPDATE SET
  last_seen_at = GREATEST(sentry_issues.last_seen_at, EXCLUDED.last_seen_at),
  event_count = sentry_issues.event_count + 1
RETURNING id, fingerprint, component, environment, title, status, first_seen_at, last_seen_at, event_count
`

type UpsertSentryIssueParams struct {
	ID          pgtype.UUID        `json:"id"`
	Fingerprint string             `json:"fingerprint"`
	Component   string             `json:"component"`
	Environment string             `json:"environment"`
	Title       string             `json:"title"`
	SeenAt      pgtype.Timestamptz `json:"seen_at"`
}

func (q *Queries) UpsertSentryIssue(ctx context.Context, arg UpsertSentryIssueParams) (SentryIssue, error) {
	row := q.db.QueryRow(ctx, upsertSentryIssue,
		arg.ID,
		arg.Fingerprint,
		arg.Component,
		arg.Environment,
		arg.Title,
		arg.SeenAt,
	)
	var i SentryIssue
	err := row.Scan(
		&i.ID,
		&i.Fingerprint,
		&i.Component,
		&i.Environment,
		&i.Title,
		&i.Status,
		&i.FirstSeenAt,
		&i.LastSeenAt,
		&i.EventCount,
	)
	return i, err
}

const upsertSentryRelease = `-- name: UpsertSentryRelease :one
INSERT INTO sentry_releases (component, version, created_at)
VALUES ($1, $2, $3)
ON CONFLICT (component, version) DO UPDATE SET component = EXCLUDED.component
RETURNING id, component, version, status, created_at, finalized_at
`

type UpsertSentryReleaseParams struct {
	Component string             `json:"component"`
	Version   string             `json:"version"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

func (q *Queries) UpsertSentryRelease(ctx context.Context, arg UpsertSentryReleaseParams) (SentryRelease, error) {
	row := q.db.QueryRow(ctx, upsertSentryRelease, arg.Component, arg.Version, arg.CreatedAt)
	var i SentryRelease
	err := row.Scan(
		&i.ID,
		&i.Component,
		&i.Version,
		&i.Status,
		&i.CreatedAt,
		&i.FinalizedAt,
	)
	return i, err
}
