// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: sync_runs.sql

package dbgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const commitSyncRunPage = `-- name: CommitSyncRunPage :one
UPDATE sync_runs SET
  state = $1,
  checkpoint = $2,
  applied_count = applied_count + $3,
  version = version + 1,
  last_success_at = $4::timestamptz,
  completed_at = CASE WHEN $1::text = 'completed' THEN $4::timestamptz ELSE NULL::timestamptz END,
  updated_at = $4::timestamptz
WHERE id = $5
  AND account_id = $6
  AND version = $7
  AND state = 'running'
  AND NOT cancel_requested
RETURNING id, account_id, phase, state, checkpoint, version, window_start, applied_count, cancel_requested, scheduled_for, started_at, last_success_at, completed_at, created_at, updated_at
`

type CommitSyncRunPageParams struct {
	NextState       string             `json:"next_state"`
	Checkpoint      []byte             `json:"checkpoint"`
	AppliedCount    int64              `json:"applied_count"`
	CompletedAt     pgtype.Timestamptz `json:"completed_at"`
	ID              pgtype.UUID        `json:"id"`
	AccountID       pgtype.UUID        `json:"account_id"`
	ExpectedVersion int64              `json:"expected_version"`
}

func (q *Queries) CommitSyncRunPage(ctx context.Context, arg CommitSyncRunPageParams) (SyncRun, error) {
	row := q.db.QueryRow(ctx, commitSyncRunPage,
		arg.NextState,
		arg.Checkpoint,
		arg.AppliedCount,
		arg.CompletedAt,
		arg.ID,
		arg.AccountID,
		arg.ExpectedVersion,
	)
	var i SyncRun
	err := row.Scan(
		&i.ID,
		&i.AccountID,
		&i.Phase,
		&i.State,
		&i.Checkpoint,
		&i.Version,
		&i.WindowStart,
		&i.AppliedCount,
		&i.CancelRequested,
		&i.ScheduledFor,
		&i.StartedAt,
		&i.LastSuccessAt,
		&i.CompletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createSyncRun = `-- name: CreateSyncRun :one
INSERT INTO sync_runs (id, account_id, phase, checkpoint, window_start, scheduled_for)
SELECT $1, accounts.id, $2, $3, $4, $5
FROM accounts
WHERE accounts.id = $6
  AND accounts.user_id = $7
  AND accounts.disabled_at IS NULL
ON CONFLICT DO NOTHING
RETURNING id, account_id, phase, state, checkpoint, version, window_start, applied_count, cancel_requested, scheduled_for, started_at, last_success_at, completed_at, created_at, updated_at
`

type CreateSyncRunParams struct {
	ID           pgtype.UUID        `json:"id"`
	Phase        string             `json:"phase"`
	Checkpoint   []byte             `json:"checkpoint"`
	WindowStart  pgtype.Timestamptz `json:"window_start"`
	ScheduledFor pgtype.Timestamptz `json:"scheduled_for"`
	AccountID    pgtype.UUID        `json:"account_id"`
	UserID       pgtype.UUID        `json:"user_id"`
}

func (q *Queries) CreateSyncRun(ctx context.Context, arg CreateSyncRunParams) (SyncRun, error) {
	row := q.db.QueryRow(ctx, createSyncRun,
		arg.ID,
		arg.Phase,
		arg.Checkpoint,
		arg.WindowStart,
		arg.ScheduledFor,
		arg.AccountID,
		arg.UserID,
	)
	var i SyncRun
	err := row.Scan(
		&i.ID,
		&i.AccountID,
		&i.Phase,
		&i.State,
		&i.Checkpoint,
		&i.Version,
		&i.WindowStart,
		&i.AppliedCount,
		&i.CancelRequested,
		&i.ScheduledFor,
		&i.StartedAt,
		&i.LastSuccessAt,
		&i.CompletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getSyncRunByOwner = `-- name: GetSyncRunByOwner :one
SELECT sync_runs.id, sync_runs.account_id, sync_runs.phase, sync_runs.state, sync_runs.checkpoint, sync_runs.version, sync_runs.window_start, sync_runs.applied_count, sync_runs.cancel_requested, sync_runs.scheduled_for, sync_runs.started_at, sync_runs.last_success_at, sync_runs.completed_at, sync_runs.created_at, sync_runs.updated_at FROM sync_runs
JOIN accounts ON accounts.id = sync_runs.account_id
WHERE sync_runs.id = $1
  AND sync_runs.account_id = $2
  AND accounts.user_id = $3
`

type GetSyncRunByOwnerParams struct {
	ID        pgtype.UUID `json:"id"`
	AccountID pgtype.UUID `json:"account_id"`
	UserID    pgtype.UUID `json:"user_id"`
}

func (q *Queries) GetSyncRunByOwner(ctx context.Context, arg GetSyncRunByOwnerParams) (SyncRun, error) {
	row := q.db.QueryRow(ctx, getSyncRunByOwner, arg.ID, arg.AccountID, arg.UserID)
	var i SyncRun
	err := row.Scan(
		&i.ID,
		&i.AccountID,
		&i.Phase,
		&i.State,
		&i.Checkpoint,
		&i.Version,
		&i.WindowStart,
		&i.AppliedCount,
		&i.CancelRequested,
		&i.ScheduledFor,
		&i.StartedAt,
		&i.LastSuccessAt,
		&i.CompletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listDueSyncRuns = `-- name: ListDueSyncRuns :many
SELECT accounts.user_id, sync_runs.id, sync_runs.account_id, sync_runs.phase, sync_runs.state, sync_runs.checkpoint, sync_runs.version, sync_runs.window_start, sync_runs.applied_count, sync_runs.cancel_requested, sync_runs.scheduled_for, sync_runs.started_at, sync_runs.last_success_at, sync_runs.completed_at, sync_runs.created_at, sync_runs.updated_at FROM sync_runs
JOIN accounts ON accounts.id = sync_runs.account_id
WHERE sync_runs.state = 'queued'
  AND NOT sync_runs.cancel_requested
  AND sync_runs.scheduled_for <= $1
ORDER BY CASE sync_runs.phase WHEN 'recent' THEN 0 WHEN 'reconcile' THEN 1 WHEN 'incremental' THEN 2 ELSE 3 END,
         sync_runs.scheduled_for, sync_runs.id
LIMIT $2
`

type ListDueSyncRunsParams struct {
	DueAt     pgtype.Timestamptz `json:"due_at"`
	BatchSize int32              `json:"batch_size"`
}

type ListDueSyncRunsRow struct {
	UserID          pgtype.UUID        `json:"user_id"`
	ID              pgtype.UUID        `json:"id"`
	AccountID       pgtype.UUID        `json:"account_id"`
	Phase           string             `json:"phase"`
	State           string             `json:"state"`
	Checkpoint      []byte             `json:"checkpoint"`
	Version         int64              `json:"version"`
	WindowStart     pgtype.Timestamptz `json:"window_start"`
	AppliedCount    int64              `json:"applied_count"`
	CancelRequested bool               `json:"cancel_requested"`
	ScheduledFor    pgtype.Timestamptz `json:"scheduled_for"`
	StartedAt       pgtype.Timestamptz `json:"started_at"`
	LastSuccessAt   pgtype.Timestamptz `json:"last_success_at"`
	CompletedAt     pgtype.Timestamptz `json:"completed_at"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
	UpdatedAt       pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) ListDueSyncRuns(ctx context.Context, arg ListDueSyncRunsParams) ([]ListDueSyncRunsRow, error) {
	rows, err := q.db.Query(ctx, listDueSyncRuns, arg.DueAt, arg.BatchSize)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListDueSyncRunsRow
	for rows.Next() {
		var i ListDueSyncRunsRow
		if err := rows.Scan(
			&i.UserID,
			&i.ID,
			&i.AccountID,
			&i.Phase,
			&i.State,
			&i.Checkpoint,
			&i.Version,
			&i.WindowStart,
			&i.AppliedCount,
			&i.CancelRequested,
			&i.ScheduledFor,
			&i.StartedAt,
			&i.LastSuccessAt,
			&i.CompletedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lockSyncRunByOwner = `-- name: LockSyncRunByOwner :one
SELECT sync_runs.id, sync_runs.account_id, sync_runs.phase, sync_runs.state, sync_runs.checkpoint, sync_runs.version, sync_runs.window_start, sync_runs.applied_count, sync_runs.cancel_requested, sync_runs.scheduled_for, sync_runs.started_at, sync_runs.last_success_at, sync_runs.completed_at, sync_runs.created_at, sync_runs.updated_at FROM sync_runs
JOIN accounts ON accounts.id = sync_runs.account_id
WHERE sync_runs.id = $1
  AND sync_runs.account_id = $2
  AND accounts.user_id = $3
FOR UPDATE OF sync_runs
`

type LockSyncRunByOwnerParams struct {
	ID        pgtype.UUID `json:"id"`
	AccountID pgtype.UUID `json:"account_id"`
	UserID    pgtype.UUID `json:"user_id"`
}

func (q *Queries) LockSyncRunByOwner(ctx context.Context, arg LockSyncRunByOwnerParams) (SyncRun, error) {
	row := q.db.QueryRow(ctx, lockSyncRunByOwner, arg.ID, arg.AccountID, arg.UserID)
	var i SyncRun
	err := row.Scan(
		&i.ID,
		&i.AccountID,
		&i.Phase,
		&i.State,
		&i.Checkpoint,
		&i.Version,
		&i.WindowStart,
		&i.AppliedCount,
		&i.CancelRequested,
		&i.ScheduledFor,
		&i.StartedAt,
		&i.LastSuccessAt,
		&i.CompletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const requestSyncRunCancellation = `-- name: RequestSyncRunCancellation :one
UPDATE sync_runs SET
  cancel_requested = true,
  state = 'cancelled',
  version = version + 1,
  completed_at = $1,
  updated_at = $1
FROM accounts
WHERE sync_runs.id = $2
  AND sync_runs.account_id = $3
  AND sync_runs.account_id = accounts.id
  AND accounts.user_id = $4
  AND sync_runs.state IN ('queued', 'running')
RETURNING sync_runs.id, sync_runs.account_id, sync_runs.phase, sync_runs.state, sync_runs.checkpoint, sync_runs.version, sync_runs.window_start, sync_runs.applied_count, sync_runs.cancel_requested, sync_runs.scheduled_for, sync_runs.started_at, sync_runs.last_success_at, sync_runs.completed_at, sync_runs.created_at, sync_runs.updated_at
`

type RequestSyncRunCancellationParams struct {
	CancelledAt pgtype.Timestamptz `json:"cancelled_at"`
	ID          pgtype.UUID        `json:"id"`
	AccountID   pgtype.UUID        `json:"account_id"`
	UserID      pgtype.UUID        `json:"user_id"`
}

func (q *Queries) RequestSyncRunCancellation(ctx context.Context, arg RequestSyncRunCancellationParams) (SyncRun, error) {
	row := q.db.QueryRow(ctx, requestSyncRunCancellation,
		arg.CancelledAt,
		arg.ID,
		arg.AccountID,
		arg.UserID,
	)
	var i SyncRun
	err := row.Scan(
		&i.ID,
		&i.AccountID,
		&i.Phase,
		&i.State,
		&i.Checkpoint,
		&i.Version,
		&i.WindowStart,
		&i.AppliedCount,
		&i.CancelRequested,
		&i.ScheduledFor,
		&i.StartedAt,
		&i.LastSuccessAt,
		&i.CompletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const requeueSyncRun = `-- name: RequeueSyncRun :one
UPDATE sync_runs SET state = 'queued', updated_at = $1
WHERE id = $2
  AND account_id = $3
  AND version = $4
  AND state = 'running'
  AND NOT cancel_requested
RETURNING id, account_id, phase, state, checkpoint, version, window_start, applied_count, cancel_requested, scheduled_for, started_at, last_success_at, completed_at, created_at, updated_at
`

type RequeueSyncRunParams struct {
	RequeuedAt      pgtype.Timestamptz `json:"requeued_at"`
	ID              pgtype.UUID        `json:"id"`
	AccountID       pgtype.UUID        `json:"account_id"`
	ExpectedVersion int64              `json:"expected_version"`
}

func (q *Queries) RequeueSyncRun(ctx context.Context, arg RequeueSyncRunParams) (SyncRun, error) {
	row := q.db.QueryRow(ctx, requeueSyncRun,
		arg.RequeuedAt,
		arg.ID,
		arg.AccountID,
		arg.ExpectedVersion,
	)
	var i SyncRun
	err := row.Scan(
		&i.ID,
		&i.AccountID,
		&i.Phase,
		&i.State,
		&i.Checkpoint,
		&i.Version,
		&i.WindowStart,
		&i.AppliedCount,
		&i.CancelRequested,
		&i.ScheduledFor,
		&i.StartedAt,
		&i.LastSuccessAt,
		&i.CompletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const startSyncRun = `-- name: StartSyncRun :one
UPDATE sync_runs SET
  state = 'running',
  started_at = COALESCE(started_at, $1),
  updated_at = $1
WHERE id = $2
  AND account_id = $3
  AND version = $4
  AND state = 'queued'
  AND NOT cancel_requested
RETURNING id, account_id, phase, state, checkpoint, version, window_start, applied_count, cancel_requested, scheduled_for, started_at, last_success_at, completed_at, created_at, updated_at
`

type StartSyncRunParams struct {
	StartedAt       pgtype.Timestamptz `json:"started_at"`
	ID              pgtype.UUID        `json:"id"`
	AccountID       pgtype.UUID        `json:"account_id"`
	ExpectedVersion int64              `json:"expected_version"`
}

func (q *Queries) StartSyncRun(ctx context.Context, arg StartSyncRunParams) (SyncRun, error) {
	row := q.db.QueryRow(ctx, startSyncRun,
		arg.StartedAt,
		arg.ID,
		arg.AccountID,
		arg.ExpectedVersion,
	)
	var i SyncRun
	err := row.Scan(
		&i.ID,
		&i.AccountID,
		&i.Phase,
		&i.State,
		&i.Checkpoint,
		&i.Version,
		&i.WindowStart,
		&i.AppliedCount,
		&i.CancelRequested,
		&i.ScheduledFor,
		&i.StartedAt,
		&i.LastSuccessAt,
		&i.CompletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
