// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: sync.sql

package dbgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const advanceSyncCursor = `-- name: AdvanceSyncCursor :one
UPDATE sync_cursors
SET
  cursor = $1,
  checkpoint = checkpoint + 1,
  uid_validity = $2,
  version = version + 1,
  last_success_at = now(),
  updated_at = now()
WHERE account_id = $3
  AND version = $4
  AND state = 'active'
RETURNING account_id, kind, cursor, updated_at, state, checkpoint, uid_validity, version, last_success_at, invalidated_at, invalidation_reason
`

type AdvanceSyncCursorParams struct {
	Cursor          []byte      `json:"cursor"`
	UidValidity     pgtype.Int8 `json:"uid_validity"`
	AccountID       pgtype.UUID `json:"account_id"`
	ExpectedVersion int64       `json:"expected_version"`
}

func (q *Queries) AdvanceSyncCursor(ctx context.Context, arg AdvanceSyncCursorParams) (SyncCursor, error) {
	row := q.db.QueryRow(ctx, advanceSyncCursor,
		arg.Cursor,
		arg.UidValidity,
		arg.AccountID,
		arg.ExpectedVersion,
	)
	var i SyncCursor
	err := row.Scan(
		&i.AccountID,
		&i.Kind,
		&i.Cursor,
		&i.UpdatedAt,
		&i.State,
		&i.Checkpoint,
		&i.UidValidity,
		&i.Version,
		&i.LastSuccessAt,
		&i.InvalidatedAt,
		&i.InvalidationReason,
	)
	return i, err
}

const createSyncCursor = `-- name: CreateSyncCursor :one
INSERT INTO sync_cursors (
  account_id, kind, cursor, state, checkpoint, uid_validity,
  version, last_success_at
)
SELECT
  accounts.id, $1, $2, 'active', 0,
  $3, 1, now()
FROM accounts
WHERE accounts.id = $4
  AND accounts.user_id = $5
  AND accounts.disabled_at IS NULL
ON CONFLICT (account_id) DO NOTHING
RETURNING account_id, kind, cursor, updated_at, state, checkpoint, uid_validity, version, last_success_at, invalidated_at, invalidation_reason
`

type CreateSyncCursorParams struct {
	Kind        string      `json:"kind"`
	Cursor      []byte      `json:"cursor"`
	UidValidity pgtype.Int8 `json:"uid_validity"`
	AccountID   pgtype.UUID `json:"account_id"`
	UserID      pgtype.UUID `json:"user_id"`
}

func (q *Queries) CreateSyncCursor(ctx context.Context, arg CreateSyncCursorParams) (SyncCursor, error) {
	row := q.db.QueryRow(ctx, createSyncCursor,
		arg.Kind,
		arg.Cursor,
		arg.UidValidity,
		arg.AccountID,
		arg.UserID,
	)
	var i SyncCursor
	err := row.Scan(
		&i.AccountID,
		&i.Kind,
		&i.Cursor,
		&i.UpdatedAt,
		&i.State,
		&i.Checkpoint,
		&i.UidValidity,
		&i.Version,
		&i.LastSuccessAt,
		&i.InvalidatedAt,
		&i.InvalidationReason,
	)
	return i, err
}

const getSyncCursorByOwner = `-- name: GetSyncCursorByOwner :one
SELECT sync_cursors.account_id, sync_cursors.kind, sync_cursors.cursor, sync_cursors.updated_at, sync_cursors.state, sync_cursors.checkpoint, sync_cursors.uid_validity, sync_cursors.version, sync_cursors.last_success_at, sync_cursors.invalidated_at, sync_cursors.invalidation_reason
FROM sync_cursors
JOIN accounts ON accounts.id = sync_cursors.account_id
WHERE sync_cursors.account_id = $1
  AND accounts.user_id = $2
`

type GetSyncCursorByOwnerParams struct {
	AccountID pgtype.UUID `json:"account_id"`
	UserID    pgtype.UUID `json:"user_id"`
}

func (q *Queries) GetSyncCursorByOwner(ctx context.Context, arg GetSyncCursorByOwnerParams) (SyncCursor, error) {
	row := q.db.QueryRow(ctx, getSyncCursorByOwner, arg.AccountID, arg.UserID)
	var i SyncCursor
	err := row.Scan(
		&i.AccountID,
		&i.Kind,
		&i.Cursor,
		&i.UpdatedAt,
		&i.State,
		&i.Checkpoint,
		&i.UidValidity,
		&i.Version,
		&i.LastSuccessAt,
		&i.InvalidatedAt,
		&i.InvalidationReason,
	)
	return i, err
}

const invalidateSyncCursor = `-- name: InvalidateSyncCursor :one
UPDATE sync_cursors
SET
  state = 'resync_required',
  invalidated_at = now(),
  invalidation_reason = $1,
  version = version + 1,
  updated_at = now()
WHERE account_id = $2
RETURNING account_id, kind, cursor, updated_at, state, checkpoint, uid_validity, version, last_success_at, invalidated_at, invalidation_reason
`

type InvalidateSyncCursorParams struct {
	Reason    pgtype.Text `json:"reason"`
	AccountID pgtype.UUID `json:"account_id"`
}

func (q *Queries) InvalidateSyncCursor(ctx context.Context, arg InvalidateSyncCursorParams) (SyncCursor, error) {
	row := q.db.QueryRow(ctx, invalidateSyncCursor, arg.Reason, arg.AccountID)
	var i SyncCursor
	err := row.Scan(
		&i.AccountID,
		&i.Kind,
		&i.Cursor,
		&i.UpdatedAt,
		&i.State,
		&i.Checkpoint,
		&i.UidValidity,
		&i.Version,
		&i.LastSuccessAt,
		&i.InvalidatedAt,
		&i.InvalidationReason,
	)
	return i, err
}

const lockSyncCursorByOwner = `-- name: LockSyncCursorByOwner :one
SELECT sync_cursors.account_id, sync_cursors.kind, sync_cursors.cursor, sync_cursors.updated_at, sync_cursors.state, sync_cursors.checkpoint, sync_cursors.uid_validity, sync_cursors.version, sync_cursors.last_success_at, sync_cursors.invalidated_at, sync_cursors.invalidation_reason
FROM sync_cursors
JOIN accounts ON accounts.id = sync_cursors.account_id
WHERE sync_cursors.account_id = $1
  AND accounts.user_id = $2
FOR UPDATE OF sync_cursors
`

type LockSyncCursorByOwnerParams struct {
	AccountID pgtype.UUID `json:"account_id"`
	UserID    pgtype.UUID `json:"user_id"`
}

func (q *Queries) LockSyncCursorByOwner(ctx context.Context, arg LockSyncCursorByOwnerParams) (SyncCursor, error) {
	row := q.db.QueryRow(ctx, lockSyncCursorByOwner, arg.AccountID, arg.UserID)
	var i SyncCursor
	err := row.Scan(
		&i.AccountID,
		&i.Kind,
		&i.Cursor,
		&i.UpdatedAt,
		&i.State,
		&i.Checkpoint,
		&i.UidValidity,
		&i.Version,
		&i.LastSuccessAt,
		&i.InvalidatedAt,
		&i.InvalidationReason,
	)
	return i, err
}
