// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: threads.sql

package dbgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createMessageAddress = `-- name: CreateMessageAddress :exec
INSERT INTO message_addresses (
  message_id, account_id, role, position, display_name, address
) VALUES ($1, $2, $3, $4, $5, $6)
`

type CreateMessageAddressParams struct {
	MessageID   pgtype.UUID `json:"message_id"`
	AccountID   pgtype.UUID `json:"account_id"`
	Role        string      `json:"role"`
	Position    int32       `json:"position"`
	DisplayName pgtype.Text `json:"display_name"`
	Address     string      `json:"address"`
}

func (q *Queries) CreateMessageAddress(ctx context.Context, arg CreateMessageAddressParams) error {
	_, err := q.db.Exec(ctx, createMessageAddress,
		arg.MessageID,
		arg.AccountID,
		arg.Role,
		arg.Position,
		arg.DisplayName,
		arg.Address,
	)
	return err
}

const deleteMessageAddresses = `-- name: DeleteMessageAddresses :exec
DELETE FROM message_addresses
WHERE message_id = $1 AND account_id = $2
`

type DeleteMessageAddressesParams struct {
	MessageID pgtype.UUID `json:"message_id"`
	AccountID pgtype.UUID `json:"account_id"`
}

func (q *Queries) DeleteMessageAddresses(ctx context.Context, arg DeleteMessageAddressesParams) error {
	_, err := q.db.Exec(ctx, deleteMessageAddresses, arg.MessageID, arg.AccountID)
	return err
}

const deleteMessageAttachmentsFromPosition = `-- name: DeleteMessageAttachmentsFromPosition :exec
DELETE FROM message_attachments
WHERE message_id = $1
  AND account_id = $2
  AND position >= $3
`

type DeleteMessageAttachmentsFromPositionParams struct {
	MessageID    pgtype.UUID `json:"message_id"`
	AccountID    pgtype.UUID `json:"account_id"`
	FromPosition int32       `json:"from_position"`
}

func (q *Queries) DeleteMessageAttachmentsFromPosition(ctx context.Context, arg DeleteMessageAttachmentsFromPositionParams) error {
	_, err := q.db.Exec(ctx, deleteMessageAttachmentsFromPosition, arg.MessageID, arg.AccountID, arg.FromPosition)
	return err
}

const getExistingMessageThread = `-- name: GetExistingMessageThread :one
SELECT thread_id
FROM messages
WHERE account_id = $1 AND remote_id = $2
`

type GetExistingMessageThreadParams struct {
	AccountID pgtype.UUID `json:"account_id"`
	RemoteID  string      `json:"remote_id"`
}

func (q *Queries) GetExistingMessageThread(ctx context.Context, arg GetExistingMessageThreadParams) (pgtype.UUID, error) {
	row := q.db.QueryRow(ctx, getExistingMessageThread, arg.AccountID, arg.RemoteID)
	var thread_id pgtype.UUID
	err := row.Scan(&thread_id)
	return thread_id, err
}

const getThreadByOwner = `-- name: GetThreadByOwner :one
SELECT threads.id, threads.account_id, threads.remote_id, threads.last_message_at, threads.is_read, threads.is_starred, threads.category, threads.is_important, threads.deleted_at, threads.message_count, threads.unread_count, threads.created_at, threads.updated_at
FROM threads
JOIN accounts ON accounts.id = threads.account_id
WHERE threads.id = $1
  AND threads.account_id = $2
  AND accounts.user_id = $3
`

type GetThreadByOwnerParams struct {
	ID        pgtype.UUID `json:"id"`
	AccountID pgtype.UUID `json:"account_id"`
	UserID    pgtype.UUID `json:"user_id"`
}

func (q *Queries) GetThreadByOwner(ctx context.Context, arg GetThreadByOwnerParams) (Thread, error) {
	row := q.db.QueryRow(ctx, getThreadByOwner, arg.ID, arg.AccountID, arg.UserID)
	var i Thread
	err := row.Scan(
		&i.ID,
		&i.AccountID,
		&i.RemoteID,
		&i.LastMessageAt,
		&i.IsRead,
		&i.IsStarred,
		&i.Category,
		&i.IsImportant,
		&i.DeletedAt,
		&i.MessageCount,
		&i.UnreadCount,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listAddressesForMessages = `-- name: ListAddressesForMessages :many
SELECT message_addresses.message_id, message_addresses.account_id, message_addresses.role, message_addresses.position, message_addresses.display_name, message_addresses.address, message_addresses.created_at
FROM message_addresses
JOIN accounts ON accounts.id = message_addresses.account_id
WHERE message_addresses.message_id = ANY($1::uuid[])
  AND message_addresses.account_id = $2
  AND accounts.user_id = $3
ORDER BY message_addresses.message_id, message_addresses.role, message_addresses.position
`

type ListAddressesForMessagesParams struct {
	MessageIds []pgtype.UUID `json:"message_ids"`
	AccountID  pgtype.UUID   `json:"account_id"`
	UserID     pgtype.UUID   `json:"user_id"`
}

func (q *Queries) ListAddressesForMessages(ctx context.Context, arg ListAddressesForMessagesParams) ([]MessageAddress, error) {
	rows, err := q.db.Query(ctx, listAddressesForMessages, arg.MessageIds, arg.AccountID, arg.UserID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []MessageAddress
	for rows.Next() {
		var i MessageAddress
		if err := rows.Scan(
			&i.MessageID,
			&i.AccountID,
			&i.Role,
			&i.Position,
			&i.DisplayName,
			&i.Address,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAttachmentsForMessages = `-- name: ListAttachmentsForMessages :many
SELECT message_attachments.id, message_attachments.message_id, message_attachments.account_id, message_attachments.position, message_attachments.remote_id, message_attachments.filename, message_attachments.media_type, message_attachments.disposition, message_attachments.content_id, message_attachments.size_bytes, message_attachments.created_at, message_attachments.updated_at
FROM message_attachments
JOIN accounts ON accounts.id = message_attachments.account_id
WHERE message_attachments.message_id = ANY($1::uuid[])
  AND message_attachments.account_id = $2
  AND accounts.user_id = $3
ORDER BY message_attachments.message_id, message_attachments.position
`

type ListAttachmentsForMessagesParams struct {
	MessageIds []pgtype.UUID `json:"message_ids"`
	AccountID  pgtype.UUID   `json:"account_id"`
	UserID     pgtype.UUID   `json:"user_id"`
}

func (q *Queries) ListAttachmentsForMessages(ctx context.Context, arg ListAttachmentsForMessagesParams) ([]MessageAttachment, error) {
	rows, err := q.db.Query(ctx, listAttachmentsForMessages, arg.MessageIds, arg.AccountID, arg.UserID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []MessageAttachment
	for rows.Next() {
		var i MessageAttachment
		if err := rows.Scan(
			&i.ID,
			&i.MessageID,
			&i.AccountID,
			&i.Position,
			&i.RemoteID,
			&i.Filename,
			&i.MediaType,
			&i.Disposition,
			&i.ContentID,
			&i.SizeBytes,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMessagesAfter = `-- name: ListMessagesAfter :many
SELECT messages.id, messages.thread_id, messages.remote_id, messages.message_id, messages.references_header, messages.sender, messages.recipients, messages.subject, messages.body_text, messages.body_html_sanitized, messages.sent_at, messages.account_id, messages.is_read, messages.is_starred, messages.is_important, messages.deleted_at, messages.created_at, messages.updated_at, messages.in_reply_to, messages.content_updated_at, messages.search_vector
FROM messages
JOIN threads ON threads.id = messages.thread_id AND threads.account_id = messages.account_id
JOIN accounts ON accounts.id = messages.account_id
WHERE messages.thread_id = $1
  AND messages.account_id = $2
  AND accounts.user_id = $3
  AND (
    messages.sent_at > $4
    OR (
      messages.sent_at = $4
      AND messages.id > $5::uuid
    )
  )
ORDER BY messages.sent_at, messages.id
LIMIT $6
`

type ListMessagesAfterParams struct {
	ThreadID     pgtype.UUID        `json:"thread_id"`
	AccountID    pgtype.UUID        `json:"account_id"`
	UserID       pgtype.UUID        `json:"user_id"`
	CursorSentAt pgtype.Timestamptz `json:"cursor_sent_at"`
	CursorID     pgtype.UUID        `json:"cursor_id"`
	PageLimit    int32              `json:"page_limit"`
}

func (q *Queries) ListMessagesAfter(ctx context.Context, arg ListMessagesAfterParams) ([]Message, error) {
	rows, err := q.db.Query(ctx, listMessagesAfter,
		arg.ThreadID,
		arg.AccountID,
		arg.UserID,
		arg.CursorSentAt,
		arg.CursorID,
		arg.PageLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Message
	for rows.Next() {
		var i Message
		if err := rows.Scan(
			&i.ID,
			&i.ThreadID,
			&i.RemoteID,
			&i.MessageID,
			&i.ReferencesHeader,
			&i.Sender,
			&i.Recipients,
			&i.Subject,
			&i.BodyText,
			&i.BodyHtmlSanitized,
			&i.SentAt,
			&i.AccountID,
			&i.IsRead,
			&i.IsStarred,
			&i.IsImportant,
			&i.DeletedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.InReplyTo,
			&i.ContentUpdatedAt,
			&i.SearchVector,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMessagesFirstPage = `-- name: ListMessagesFirstPage :many
SELECT messages.id, messages.thread_id, messages.remote_id, messages.message_id, messages.references_header, messages.sender, messages.recipients, messages.subject, messages.body_text, messages.body_html_sanitized, messages.sent_at, messages.account_id, messages.is_read, messages.is_starred, messages.is_important, messages.deleted_at, messages.created_at, messages.updated_at, messages.in_reply_to, messages.content_updated_at, messages.search_vector
FROM messages
JOIN threads ON threads.id = messages.thread_id AND threads.account_id = messages.account_id
JOIN accounts ON accounts.id = messages.account_id
WHERE messages.thread_id = $1
  AND messages.account_id = $2
  AND accounts.user_id = $3
ORDER BY messages.sent_at, messages.id
LIMIT $4
`

type ListMessagesFirstPageParams struct {
	ThreadID  pgtype.UUID `json:"thread_id"`
	AccountID pgtype.UUID `json:"account_id"`
	UserID    pgtype.UUID `json:"user_id"`
	Limit     int32       `json:"limit"`
}

func (q *Queries) ListMessagesFirstPage(ctx context.Context, arg ListMessagesFirstPageParams) ([]Message, error) {
	rows, err := q.db.Query(ctx, listMessagesFirstPage,
		arg.ThreadID,
		arg.AccountID,
		arg.UserID,
		arg.Limit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Message
	for rows.Next() {
		var i Message
		if err := rows.Scan(
			&i.ID,
			&i.ThreadID,
			&i.RemoteID,
			&i.MessageID,
			&i.ReferencesHeader,
			&i.Sender,
			&i.Recipients,
			&i.Subject,
			&i.BodyText,
			&i.BodyHtmlSanitized,
			&i.SentAt,
			&i.AccountID,
			&i.IsRead,
			&i.IsStarred,
			&i.IsImportant,
			&i.DeletedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.InReplyTo,
			&i.ContentUpdatedAt,
			&i.SearchVector,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listThreadsAfter = `-- name: ListThreadsAfter :many
SELECT threads.id, threads.account_id, threads.remote_id, threads.last_message_at, threads.is_read, threads.is_starred, threads.category, threads.is_important, threads.deleted_at, threads.message_count, threads.unread_count, threads.created_at, threads.updated_at
FROM threads
JOIN accounts ON accounts.id = threads.account_id
WHERE threads.account_id = $1
  AND accounts.user_id = $2
  AND (
    threads.last_message_at < $3
    OR (
      threads.last_message_at = $3
      AND threads.id < $4::uuid
    )
  )
ORDER BY threads.last_message_at DESC, threads.id DESC
LIMIT $5
`

type ListThreadsAfterParams struct {
	AccountID           pgtype.UUID        `json:"account_id"`
	UserID              pgtype.UUID        `json:"user_id"`
	CursorLastMessageAt pgtype.Timestamptz `json:"cursor_last_message_at"`
	CursorID            pgtype.UUID        `json:"cursor_id"`
	PageLimit           int32              `json:"page_limit"`
}

func (q *Queries) ListThreadsAfter(ctx context.Context, arg ListThreadsAfterParams) ([]Thread, error) {
	rows, err := q.db.Query(ctx, listThreadsAfter,
		arg.AccountID,
		arg.UserID,
		arg.CursorLastMessageAt,
		arg.CursorID,
		arg.PageLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Thread
	for rows.Next() {
		var i Thread
		if err := rows.Scan(
			&i.ID,
			&i.AccountID,
			&i.RemoteID,
			&i.LastMessageAt,
			&i.IsRead,
			&i.IsStarred,
			&i.Category,
			&i.IsImportant,
			&i.DeletedAt,
			&i.MessageCount,
			&i.UnreadCount,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listThreadsFirstPage = `-- name: ListThreadsFirstPage :many
SELECT threads.id, threads.account_id, threads.remote_id, threads.last_message_at, threads.is_read, threads.is_starred, threads.category, threads.is_important, threads.deleted_at, threads.message_count, threads.unread_count, threads.created_at, threads.updated_at
FROM threads
JOIN accounts ON accounts.id = threads.account_id
WHERE threads.account_id = $1
  AND accounts.user_id = $2
ORDER BY threads.last_message_at DESC, threads.id DESC
LIMIT $3
`

type ListThreadsFirstPageParams struct {
	AccountID pgtype.UUID `json:"account_id"`
	UserID    pgtype.UUID `json:"user_id"`
	Limit     int32       `json:"limit"`
}

func (q *Queries) ListThreadsFirstPage(ctx context.Context, arg ListThreadsFirstPageParams) ([]Thread, error) {
	rows, err := q.db.Query(ctx, listThreadsFirstPage, arg.AccountID, arg.UserID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Thread
	for rows.Next() {
		var i Thread
		if err := rows.Scan(
			&i.ID,
			&i.AccountID,
			&i.RemoteID,
			&i.LastMessageAt,
			&i.IsRead,
			&i.IsStarred,
			&i.Category,
			&i.IsImportant,
			&i.DeletedAt,
			&i.MessageCount,
			&i.UnreadCount,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lockAccountMailState = `-- name: LockAccountMailState :exec
SELECT pg_advisory_xact_lock(hashtextextended($1::text, 0))
`

func (q *Queries) LockAccountMailState(ctx context.Context, accountID string) error {
	_, err := q.db.Exec(ctx, lockAccountMailState, accountID)
	return err
}

const refreshThreadSummary = `-- name: RefreshThreadSummary :one
UPDATE threads
SET
  last_message_at = COALESCE(summary.last_message_at, threads.last_message_at),
  message_count = summary.message_count,
  unread_count = summary.unread_count,
  is_read = summary.unread_count = 0,
  is_starred = COALESCE(summary.is_starred, false),
  is_important = COALESCE(summary.is_important, false),
  deleted_at = CASE WHEN COALESCE(summary.all_deleted, false) THEN summary.deleted_at ELSE NULL END,
  updated_at = now()
FROM (
  SELECT
    count(*)::integer AS message_count,
    count(*) FILTER (WHERE NOT is_read)::integer AS unread_count,
    bool_or(is_starred) AS is_starred,
    bool_or(is_important) AS is_important,
    bool_and(deleted_at IS NOT NULL) AS all_deleted,
    max(deleted_at) AS deleted_at,
    max(sent_at) AS last_message_at
  FROM messages
  WHERE thread_id = $1
    AND account_id = $2
) AS summary
WHERE threads.id = $1
  AND threads.account_id = $2
RETURNING threads.id, threads.account_id, threads.remote_id, threads.last_message_at, threads.is_read, threads.is_starred, threads.category, threads.is_important, threads.deleted_at, threads.message_count, threads.unread_count, threads.created_at, threads.updated_at
`

type RefreshThreadSummaryParams struct {
	ThreadID  pgtype.UUID `json:"thread_id"`
	AccountID pgtype.UUID `json:"account_id"`
}

func (q *Queries) RefreshThreadSummary(ctx context.Context, arg RefreshThreadSummaryParams) (Thread, error) {
	row := q.db.QueryRow(ctx, refreshThreadSummary, arg.ThreadID, arg.AccountID)
	var i Thread
	err := row.Scan(
		&i.ID,
		&i.AccountID,
		&i.RemoteID,
		&i.LastMessageAt,
		&i.IsRead,
		&i.IsStarred,
		&i.Category,
		&i.IsImportant,
		&i.DeletedAt,
		&i.MessageCount,
		&i.UnreadCount,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateMessageState = `-- name: UpdateMessageState :one
UPDATE messages
SET
  is_read = COALESCE($1, is_read),
  is_starred = COALESCE($2, is_starred),
  is_important = COALESCE($3, is_important),
  deleted_at = CASE
    WHEN $4::boolean IS NULL THEN deleted_at
    WHEN $4::boolean THEN now()
    ELSE NULL
  END,
  updated_at = now()
FROM accounts
WHERE messages.id = $5
  AND messages.thread_id = $6
  AND messages.account_id = $7
  AND accounts.id = messages.account_id
  AND accounts.user_id = $8
RETURNING messages.id, messages.thread_id, messages.remote_id, messages.message_id, messages.references_header, messages.sender, messages.recipients, messages.subject, messages.body_text, messages.body_html_sanitized, messages.sent_at, messages.account_id, messages.is_read, messages.is_starred, messages.is_important, messages.deleted_at, messages.created_at, messages.updated_at, messages.in_reply_to, messages.content_updated_at, messages.search_vector
`

type UpdateMessageStateParams struct {
	IsRead      pgtype.Bool `json:"is_read"`
	IsStarred   pgtype.Bool `json:"is_starred"`
	IsImportant pgtype.Bool `json:"is_important"`
	IsDeleted   pgtype.Bool `json:"is_deleted"`
	ID          pgtype.UUID `json:"id"`
	ThreadID    pgtype.UUID `json:"thread_id"`
	AccountID   pgtype.UUID `json:"account_id"`
	UserID      pgtype.UUID `json:"user_id"`
}

func (q *Queries) UpdateMessageState(ctx context.Context, arg UpdateMessageStateParams) (Message, error) {
	row := q.db.QueryRow(ctx, updateMessageState,
		arg.IsRead,
		arg.IsStarred,
		arg.IsImportant,
		arg.IsDeleted,
		arg.ID,
		arg.ThreadID,
		arg.AccountID,
		arg.UserID,
	)
	var i Message
	err := row.Scan(
		&i.ID,
		&i.ThreadID,
		&i.RemoteID,
		&i.MessageID,
		&i.ReferencesHeader,
		&i.Sender,
		&i.Recipients,
		&i.Subject,
		&i.BodyText,
		&i.BodyHtmlSanitized,
		&i.SentAt,
		&i.AccountID,
		&i.IsRead,
		&i.IsStarred,
		&i.IsImportant,
		&i.DeletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.InReplyTo,
		&i.ContentUpdatedAt,
		&i.SearchVector,
	)
	return i, err
}

const updateMessagesStateByThread = `-- name: UpdateMessagesStateByThread :exec
UPDATE messages
SET
  is_read = COALESCE($1, is_read),
  is_starred = COALESCE($2, is_starred),
  is_important = COALESCE($3, is_important),
  deleted_at = CASE
    WHEN $4::boolean IS NULL THEN deleted_at
    WHEN $4::boolean THEN now()
    ELSE NULL
  END,
  updated_at = now()
WHERE thread_id = $5
  AND account_id = $6
`

type UpdateMessagesStateByThreadParams struct {
	IsRead      pgtype.Bool `json:"is_read"`
	IsStarred   pgtype.Bool `json:"is_starred"`
	IsImportant pgtype.Bool `json:"is_important"`
	IsDeleted   pgtype.Bool `json:"is_deleted"`
	ThreadID    pgtype.UUID `json:"thread_id"`
	AccountID   pgtype.UUID `json:"account_id"`
}

func (q *Queries) UpdateMessagesStateByThread(ctx context.Context, arg UpdateMessagesStateByThreadParams) error {
	_, err := q.db.Exec(ctx, updateMessagesStateByThread,
		arg.IsRead,
		arg.IsStarred,
		arg.IsImportant,
		arg.IsDeleted,
		arg.ThreadID,
		arg.AccountID,
	)
	return err
}

const updateThreadState = `-- name: UpdateThreadState :one
UPDATE threads
SET
  is_read = COALESCE($1, is_read),
  is_starred = COALESCE($2, is_starred),
  is_important = COALESCE($3, is_important),
  deleted_at = CASE
    WHEN $4::boolean IS NULL THEN deleted_at
    WHEN $4::boolean THEN now()
    ELSE NULL
  END,
  updated_at = now()
FROM accounts
WHERE threads.id = $5
  AND threads.account_id = $6
  AND accounts.id = threads.account_id
  AND accounts.user_id = $7
RETURNING threads.id, threads.account_id, threads.remote_id, threads.last_message_at, threads.is_read, threads.is_starred, threads.category, threads.is_important, threads.deleted_at, threads.message_count, threads.unread_count, threads.created_at, threads.updated_at
`

type UpdateThreadStateParams struct {
	IsRead      pgtype.Bool `json:"is_read"`
	IsStarred   pgtype.Bool `json:"is_starred"`
	IsImportant pgtype.Bool `json:"is_important"`
	IsDeleted   pgtype.Bool `json:"is_deleted"`
	ID          pgtype.UUID `json:"id"`
	AccountID   pgtype.UUID `json:"account_id"`
	UserID      pgtype.UUID `json:"user_id"`
}

func (q *Queries) UpdateThreadState(ctx context.Context, arg UpdateThreadStateParams) (Thread, error) {
	row := q.db.QueryRow(ctx, updateThreadState,
		arg.IsRead,
		arg.IsStarred,
		arg.IsImportant,
		arg.IsDeleted,
		arg.ID,
		arg.AccountID,
		arg.UserID,
	)
	var i Thread
	err := row.Scan(
		&i.ID,
		&i.AccountID,
		&i.RemoteID,
		&i.LastMessageAt,
		&i.IsRead,
		&i.IsStarred,
		&i.Category,
		&i.IsImportant,
		&i.DeletedAt,
		&i.MessageCount,
		&i.UnreadCount,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const upsertMessage = `-- name: UpsertMessage :one
INSERT INTO messages (
  id, thread_id, account_id, remote_id, message_id, references_header,
  in_reply_to, sender, recipients, subject, body_text, body_html_sanitized,
  sent_at, is_read, is_starred, is_important, deleted_at, content_updated_at
)
SELECT
  $1, owned_thread.id, owned_thread.account_id, $2,
  $3, $4, $5,
  '{}'::jsonb, '[]'::jsonb, $6, $7,
  $8, $9, $10,
  $11, $12, $13, now()
FROM threads AS owned_thread
JOIN accounts ON accounts.id = owned_thread.account_id
WHERE owned_thread.id = $14
  AND owned_thread.account_id = $15
  AND accounts.user_id = $16
  AND accounts.disabled_at IS NULL
ON CONFLICT (account_id, remote_id) DO UPDATE SET
  thread_id = EXCLUDED.thread_id,
  message_id = EXCLUDED.message_id,
  references_header = EXCLUDED.references_header,
  in_reply_to = EXCLUDED.in_reply_to,
  subject = EXCLUDED.subject,
  body_text = EXCLUDED.body_text,
  body_html_sanitized = EXCLUDED.body_html_sanitized,
  content_updated_at = now(),
  sent_at = EXCLUDED.sent_at,
  is_read = EXCLUDED.is_read,
  is_starred = EXCLUDED.is_starred,
  is_important = EXCLUDED.is_important,
  deleted_at = EXCLUDED.deleted_at,
  updated_at = now()
RETURNING id, thread_id, remote_id, message_id, references_header, sender, recipients, subject, body_text, body_html_sanitized, sent_at, account_id, is_read, is_starred, is_important, deleted_at, created_at, updated_at, in_reply_to, content_updated_at, search_vector
`

type UpsertMessageParams struct {
	ID                pgtype.UUID        `json:"id"`
	RemoteID          string             `json:"remote_id"`
	MessageID         pgtype.Text        `json:"message_id"`
	ReferencesHeader  []string           `json:"references_header"`
	InReplyTo         []string           `json:"in_reply_to"`
	Subject           string             `json:"subject"`
	BodyText          string             `json:"body_text"`
	BodyHtmlSanitized string             `json:"body_html_sanitized"`
	SentAt            pgtype.Timestamptz `json:"sent_at"`
	IsRead            bool               `json:"is_read"`
	IsStarred         bool               `json:"is_starred"`
	IsImportant       bool               `json:"is_important"`
	DeletedAt         pgtype.Timestamptz `json:"deleted_at"`
	ThreadID          pgtype.UUID        `json:"thread_id"`
	AccountID         pgtype.UUID        `json:"account_id"`
	UserID            pgtype.UUID        `json:"user_id"`
}

func (q *Queries) UpsertMessage(ctx context.Context, arg UpsertMessageParams) (Message, error) {
	row := q.db.QueryRow(ctx, upsertMessage,
		arg.ID,
		arg.RemoteID,
		arg.MessageID,
		arg.ReferencesHeader,
		arg.InReplyTo,
		arg.Subject,
		arg.BodyText,
		arg.BodyHtmlSanitized,
		arg.SentAt,
		arg.IsRead,
		arg.IsStarred,
		arg.IsImportant,
		arg.DeletedAt,
		arg.ThreadID,
		arg.AccountID,
		arg.UserID,
	)
	var i Message
	err := row.Scan(
		&i.ID,
		&i.ThreadID,
		&i.RemoteID,
		&i.MessageID,
		&i.ReferencesHeader,
		&i.Sender,
		&i.Recipients,
		&i.Subject,
		&i.BodyText,
		&i.BodyHtmlSanitized,
		&i.SentAt,
		&i.AccountID,
		&i.IsRead,
		&i.IsStarred,
		&i.IsImportant,
		&i.DeletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.InReplyTo,
		&i.ContentUpdatedAt,
		&i.SearchVector,
	)
	return i, err
}

const upsertMessageAttachment = `-- name: UpsertMessageAttachment :one
INSERT INTO message_attachments (
  id, message_id, account_id, position, remote_id, filename,
  media_type, disposition, content_id, size_bytes
) VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10)
ON CONFLICT (message_id, position) DO UPDATE SET
  remote_id = EXCLUDED.remote_id,
  filename = EXCLUDED.filename,
  media_type = EXCLUDED.media_type,
  disposition = EXCLUDED.disposition,
  content_id = EXCLUDED.content_id,
  size_bytes = EXCLUDED.size_bytes,
  updated_at = now()
RETURNING id, message_id, account_id, position, remote_id, filename, media_type, disposition, content_id, size_bytes, created_at, updated_at
`

type UpsertMessageAttachmentParams struct {
	ID          pgtype.UUID `json:"id"`
	MessageID   pgtype.UUID `json:"message_id"`
	AccountID   pgtype.UUID `json:"account_id"`
	Position    int32       `json:"position"`
	RemoteID    pgtype.Text `json:"remote_id"`
	Filename    pgtype.Text `json:"filename"`
	MediaType   string      `json:"media_type"`
	Disposition string      `json:"disposition"`
	ContentID   pgtype.Text `json:"content_id"`
	SizeBytes   int64       `json:"size_bytes"`
}

func (q *Queries) UpsertMessageAttachment(ctx context.Context, arg UpsertMessageAttachmentParams) (MessageAttachment, error) {
	row := q.db.QueryRow(ctx, upsertMessageAttachment,
		arg.ID,
		arg.MessageID,
		arg.AccountID,
		arg.Position,
		arg.RemoteID,
		arg.Filename,
		arg.MediaType,
		arg.Disposition,
		arg.ContentID,
		arg.SizeBytes,
	)
	var i MessageAttachment
	err := row.Scan(
		&i.ID,
		&i.MessageID,
		&i.AccountID,
		&i.Position,
		&i.RemoteID,
		&i.Filename,
		&i.MediaType,
		&i.Disposition,
		&i.ContentID,
		&i.SizeBytes,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const upsertThread = `-- name: UpsertThread :one
INSERT INTO threads (
  id, account_id, remote_id, last_message_at,
  is_read, is_starred, is_important, category, deleted_at
)
SELECT
  $1, owned.id, $2, $3,
  $4, $5, $6,
  $7, $8
FROM accounts AS owned
WHERE owned.id = $9
  AND owned.user_id = $10
  AND owned.disabled_at IS NULL
ON CONFLICT (account_id, remote_id) DO UPDATE SET
  last_message_at = EXCLUDED.last_message_at,
  is_read = EXCLUDED.is_read,
  is_starred = EXCLUDED.is_starred,
  is_important = EXCLUDED.is_important,
  category = EXCLUDED.category,
  deleted_at = EXCLUDED.deleted_at,
  updated_at = now()
RETURNING id, account_id, remote_id, last_message_at, is_read, is_starred, category, is_important, deleted_at, message_count, unread_count, created_at, updated_at
`

type UpsertThreadParams struct {
	ID            pgtype.UUID        `json:"id"`
	RemoteID      string             `json:"remote_id"`
	LastMessageAt pgtype.Timestamptz `json:"last_message_at"`
	IsRead        bool               `json:"is_read"`
	IsStarred     bool               `json:"is_starred"`
	IsImportant   bool               `json:"is_important"`
	Category      string             `json:"category"`
	DeletedAt     pgtype.Timestamptz `json:"deleted_at"`
	AccountID     pgtype.UUID        `json:"account_id"`
	UserID        pgtype.UUID        `json:"user_id"`
}

func (q *Queries) UpsertThread(ctx context.Context, arg UpsertThreadParams) (Thread, error) {
	row := q.db.QueryRow(ctx, upsertThread,
		arg.ID,
		arg.RemoteID,
		arg.LastMessageAt,
		arg.IsRead,
		arg.IsStarred,
		arg.IsImportant,
		arg.Category,
		arg.DeletedAt,
		arg.AccountID,
		arg.UserID,
	)
	var i Thread
	err := row.Scan(
		&i.ID,
		&i.AccountID,
		&i.RemoteID,
		&i.LastMessageAt,
		&i.IsRead,
		&i.IsStarred,
		&i.Category,
		&i.IsImportant,
		&i.DeletedAt,
		&i.MessageCount,
		&i.UnreadCount,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
